### ISSUE TITLE
Ballistic hivebots need rebalanced

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#1061]
Various hivebots which use bullets exist and are intended as weak pushover mobs only dangerous in groups. Since #777, #788, and #877, said hivebots have become extremely deadly. Rebalancing is needed, especially since some of these hivebots are used in POI's.

**Comment by MisterGrimm** [comment]
I would say the easiest way to balance them is to change their projectile type from a bullet to a laser. Maybe give the basic ones the weak or normal laser, and the more different types the scatter laser?

Also while we're talking about this, the abomination blob creature that uses the machine-gun will become god if it is ever spawned. That should be balanced in advance before the entire station gets disintegrated if a admin spawns it.

**Comment by Darlantanis** [comment]
Fixed by #1156
