### ISSUE TITLE
red spacesuit replica broken sprite

### ISSUE THREAD

**Issue by kcin2001** [CHOMPStation2/CHOMPStation2#1171]
#### Brief description of the issue

red spacesuit replica doesnt have a body sprite
#### What you expected to happen
to wear the spacesuit

#### What actually happened
had a default oopsie sprite

#### Steps to reproduce
- (Step 1) get a red spacesuit replica
- (Step 2) wear it

#### Code Revision
- 58e59eaa6b05167b773d672d7d26d2722e03e043
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/16435949/105623454-a94d6580-5dce-11eb-9c2e-78fb6c498cde.png)

**Comment by CommodoreYouth** [comment]
You wore this Suit as a Taur.
Many Taurs do not have Sprites for certain clothing items, because the clothing items generally cover the entire body, legs and feet included.  Taurs have special sprites for their legs and feet that need extra spritework to be compatible with these "missing sprites".

**Comment by kcin2001** [comment]
I thought it defaults to the non taur ver if there is no special sprite?

**Comment by CommodoreYouth** [comment]
Mechanically, suits/helmets that don't need to be cycled, like the Red Space Replica Suit, have a sprite that generally fits all humanoid characters, even if it makes them look odd, like missing tails or ears.  Taurs have the lower half of their body as a completely different sprite, and each Taur choice needs its own spritework done to make the suit fit THE ENTIRE TAUR SHAPE, not just the front legs.  Yes, the entire taur body, in addition to the upper body, needs a sprite.

Without the sprite, most outfits like these default to that ERROR-like greentext of just "suit".

**Comment by kcin2001** [comment]
![image](https://user-images.githubusercontent.com/16435949/110072453-a8dfad00-7d32-11eb-8c7a-82983bdc0b41.png)
its broken for non taurs too...
