### ISSUE TITLE
Cryo eats xenowear

### ISSUE THREAD

**Issue by miniusAreas** [CHOMPStation2/CHOMPStation2#1195]
#### Brief description of the issue
Cryo unselects all xenowear options after going into it, and then leaving it to join a round due to persistance options.

#### What you expected to happen
Expect to leave cryo with my loadout.

#### What actually happened
Leave cryo with everything but my xenowear under the loadout, check loadout, all xenowear is unselected

#### Steps to reproduce
- (Step 1) enter cryo with xenowear selected
- (Step 2) wait for new round to start
- (Step 3) join round, xenowear flips off after entering cryo

#### Code Revision
- (B: D:2021-01-26.)

**Comment by Darlantanis** [comment]
This issue has existed for at least 3 years. It would be great if somebody can finally determine the cause.
