### ISSUE TITLE
exploration can get medical hud nifsoft

### ISSUE THREAD

**Issue by kcin2001** [CHOMPStation2/CHOMPStation2#1208]
#### Brief description of the issue
explorers can get the med hud when i dont think they are supposed to be able to

#### What you expected to happen
access denined

#### What actually happened
purchase successful

#### Steps to reproduce
- be an explorer
- have nif
- buy med hud nifsoft

#### Code Revision
- b7d964f87abba276359e99fd2e060452f399e74d
 
#### Anything else you may wish to add:
- theres no reason they should have this, health bars are displayed with the civ hud as well it just errorously lets them view med record and such

**Comment by kcin2001** [comment]
explorers do not have ANY med access so i dont know why they can purchase it

**Comment by xnqm8h** [comment]
In server revision: `B:4971-suspension-field-sprite-missing D:2022-09-21` explorers, pathfinder in my testing, was not able to purchase medical HUD from the NIFSoft vendor.
