### ISSUE TITLE
Air pressure in disposals.

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPStation2/CHOMPStation2#122]
Because of the lack of airtight plastic flaps in cargo's mailroom, the room can get overpressurized by people throwing things away multiple things in quick succession. Just add some in front of the disposal outlet, and it shouuuuld fix it. Maybe.

How to reproduce: Throw things away in the trashcans a bunch. A lot.

Watch pressure in mailroom rise.

**Comment by TheFurryFeline** [comment]
Mapping issue, easily resolved.
