### ISSUE TITLE
Red Slime rage gives code

### ISSUE THREAD

**Issue by InsanityKitten** [CHOMPStation2/CHOMPStation2#123]
#### Brief description of the issue
Hitting red slimes with a baton produces code

#### What you expected to happen
Slimes to enrage normally when hit

#### What actually happened
While they did actually enrage it gave some code when it said they went into a rage

#### Steps to reproduce
- (Step 1) spawn a red slime
- (Step 2) hit them with an active xeno taser or xeno baton

#### Code Revision
- Server revision: master - 2020-01-10
f568be89d9ef79856dbd4550032263f6586ef5f1

**Comment by TheFurryFeline** [comment]
Screenshot/more info, please.

**Comment by ExabyteDiscord** [comment]
After asking them on the discord, it seems that Red Slimes still work as intended, it's just that it appears to show a file path whenever they become enraged.

**Comment by TheFurryFeline** [comment]
Resolved with https://github.com/PolarisSS13/Polaris/pull/6890 that's since made its way down here. https://github.com/CHOMPStation2/CHOMPStation2/commit/f95db1f5bd4287fa888b09660a28f3ba04271f25

**Comment by Darlantanis** [comment]
Fixed.
