### ISSUE TITLE
Remove Demon Laughter upon clicking demons (or make it toggable)

### ISSUE THREAD

**Issue by Dinnel** [CHOMPStation2/CHOMPStation2#1241]
#### Brief overview of the feature
I get the spooky demon laughter is there to make them scary or when you bap them but it's a bit annoying when it happens every time they're petted, consume something even as something simple as a glass of water.

#### What you want to happen
Disable demon laughter or make it happen in less situations... least not as frequent!
 
#### Anything else you may wish to add:
- AI Demons it's fine but player controlled ones it can be a bit annoying.

**Comment by Darlantanis** [comment]
Fixed by #1263
