### ISSUE TITLE
Make resleeving more private

### ISSUE THREAD

**Issue by HatArchAzel** [CHOMPStation2/CHOMPStation2#130]
#### Brief overview of the feature
The resleeving room is... very unusually open and visible to the public, which is pretty counter-intuitive to anyone in Medical wanting to have scenes with freshly-resleeved crew (ESPECIALLY in regards to vore) as well as the general policy of the station in general. The current layout is counterintuitive from a patient privacy perspective: you'd realistically probably want to have the resleeving process be fairly discreet since it has the potential to be so personally impactful for someone, or at LEAST not have the majority of the room _actively visible to non-medical personnel from the medbay lobby._

#### What you want to happen
Close the room off more with actual doors where the emergency shutters to the left currently are, and change the windows to polychromatic ones that can be blacked out. This way, patients can have the privacy and respect they deserve when being resleeved... 
...and hungry medical personnel have a much easier time toying with their vulnerable victims, opening up the potential for a lot of fun teasing.
 
#### Anything else you may wish to add:
The resleeving room as it is, and proof that most of it can be seen from the lobby.
![image](https://user-images.githubusercontent.com/23587781/72212934-593d8280-349b-11ea-8c52-2e933bfa63ad.png)
![image](https://user-images.githubusercontent.com/23587781/72212945-7b370500-349b-11ea-9d9a-a977d51efa44.png)

**Comment by Kazzc** [comment]
I finally solved this. :o 
Resleeving is a tad more private now.
