### ISSUE TITLE
Impliment Explorer Icons for AR.

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPStation2/CHOMPStation2#132]
The explorers currently do not have any icon above their head when looked at in any sort of AR, and they show up almost as visitors. Might be portable from virgo.

**Comment by TheFurryFeline** [comment]
This is a known issue that's been around since before the rebase. Example: Off-duty icons. I know where the icons are in the sprites but not how to make them get called....

**Comment by TheFurryFeline** [comment]
Resolving with #200
