### ISSUE TITLE
ID Card Modification program in NTOS consoles only show manifest

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#1322]
#### Brief description of the issue
Card modification program in the NTOS console should be like a normal HoP ID console, but instead it only shows a crew manifest.

#### What you expected to happen
Card modification screen pops up so you can change ID access and jobs.

#### What actually happened
Brings up crew manifest only.

#### Steps to reproduce
- Open up NTOS console
- Download Card Modification Program in NTOS
- Open the program.
 
#### Anything else you may wish to add:
- N/A

**Comment by Sharkmare** [comment]
Just like the actual console theres a crew manifest tab and an edit tab, simply swap tabs.

**Comment by MisterGrimm** [comment]
Console disables edit tab if the console does not have a ID slot, just figured that out.
