### ISSUE TITLE
MRE items not compatible with Trash Eater

### ISSUE THREAD

**Issue by HatArchAzel** [CHOMPStation2/CHOMPStation2#134]
#### Brief description of the issue
Trash Eater doesn't let you eat anything out of an MRE except the food itself.

#### What you expected to happen
Being able to use Trash Eater to swallow the MRE packets, especially when they're empty, given that they're just plastic-wrapped trash then.

#### What actually happened
You can't.

#### Steps to reproduce
- (Step 1) Have trash eater as a trait
- (Step 2) Obtain MRE
- (Step 3) Big sad

#### Code Revision
Server revision: master - 2020-01-13
271b293a63a3497a558acc478f9035823a5c5510 
 
#### Anything else you may wish to add:
- More of an oversight than a bug, but it's disappointing regardless.

**Comment by ExabyteDiscord** [comment]
Tested, seems to work by now.
