### ISSUE TITLE
.45 Pistol Resprites Are All Invisible

### ISSUE THREAD

**Issue by LackingDecency** [CHOMPStation2/CHOMPStation2#1353]
#### Brief description of the issue
When you attempt to resprite the .45 pistol, the sprite disappears entirely, regardless of the option you choose. The pistol is still there but is invisible in your hand and when you drop it, as if there is no sprite.

#### What you expected to happen
The sprite to change to whatever is selected and appear in your hand or when dropped.

#### What actually happened
There is no sprite.

#### Steps to reproduce
- (Step 1) Right-click .45 pistol while held in hand and select "Resprite".
- (Step 2) Choose any option.
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Razgriz1032** [comment]
Fixed
