### ISSUE TITLE
Serenity Armor Plates bug

### ISSUE THREAD

**Issue by InsanityKitten** [CHOMPStation2/CHOMPStation2#145]
#### Brief description of the issue
When finishing Serenity, the requirement for external armor is 5 plasteel sheets. However, if you're holding a stack that has more than 5 armor plates, the serenity will take all plasteel in that stack. Attempting to remove external armor with a crowbar produces gygax armored plates instead of the stack.

#### What you expected to happen
The serenity to not EAT my plasteel stack

#### What actually happened
The serenity ate my stack of plasteel and gave me gygax armor plates when I attempted to remove it.

#### Steps to reproduce
- Build Serenity up to the point were you need to install external plates (last step)
-  Apply more than 5 plasteel sheets
- Attempt to remove the plasteel
- Get Gygax armored plates instead of plasteel

#### Code Revision
Server revision: master - 2020-01-14
6be7d7e75a85e217e5c829764184b6510c0dfc68 
 
#### Anything else you may wish to add:
When I did this on server, I believe it may have caused a massive lag spike until I finished the serenity.

**Comment by ExabyteDiscord** [comment]
This can likely be avoided temporarily by making sure you only apply 5 plasteel sheets. As for the lag, if the case is constructing the serenity, this'll likely need to be fixed sooner rather than later, but I'll leave it as Low Priority for now.

**Comment by Rykka-Stormheart** [comment]
This is resolved by https://github.com/CHOMPStation2/CHOMPStation2/pull/182
and https://github.com/VOREStation/VOREStation/pull/6477 from upstream, as well as
https://github.com/PolarisSS13/Polaris/pull/6641 further upstream. Close pls <3
