### ISSUE TITLE
Cyborg Content Update

### ISSUE THREAD

**Issue by CommodoreYouth** [CHOMPStation2/CHOMPStation2#1469]
#### Brief overview of the feature
Surgical and Engineering Borg Modules would benefit from minor updating for current content.

#### What you want to happen
Surgical Modules get a Bioregenerator tool for their inventory, to allow them to perform Bioregeneration Surgeries.
Engineering Modules have their Gripper modified to allow picking up of fuel rod assemblies, to start the R-UST on the Outpost.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Armyguy** [comment]
If i may add to this.

**What you want to happen**

The Surgical dogborg is more or less done, and outside of makeing a new "belly" or removeing the one it has its good to go.
liquid bellys don't "really" work on borgs, as they have no way of filling them up outside of eating mobs ircc.
