### ISSUE TITLE
Making tacos also makes meatballs

### ISSUE THREAD

**Issue by radiantAurora** [CHOMPStation2/CHOMPStation2#1482]
#### Brief description of the issue
Cooking tacos also makes meatballs

#### What you expected to happen
To just cook tacos

#### What actually happened
The tacos were accompanies by a flood of meatballs

#### Steps to reproduce
- Cook some tacos in a microwave
- You now have meatballs out of nowhere too

#### Code Revision
964ca6e909a018c5770484439cd3effb503d29d1

**Comment by EtheoBoxxman** [comment]
This also happens with breakfast muffins btw.

**Comment by radiantAurora** [comment]
My best guess is that it's mixing the reagents inside the ingredients as well as cooking them into the resulting food.
