### ISSUE TITLE
Characters with cold-adapted take damage when spawning

### ISSUE THREAD

**Issue by radiantAurora** [CHOMPStation2/CHOMPStation2#1494]
#### Brief description of the issue
When a character with cold-adapted spawns in they take burn damage whilst loading in. There really should be something in place to prevent a mob taking damage before it's fully loaded in.

#### Code Revision
0cd046d8e68135e6634b7dd5abab1cd04feab3bf

**Comment by MisterGrimm** [comment]
Coffee and most forms of alcohol will also attempt to kill you with cold adapted, only takes about 15 units to down most people if you don't guzzle ice while drinking it. Seems a bit silly that drinking someone as mundane as alcohol ends up killing people with cold adapted.

**Comment by SolanAsasora** [comment]
Slight clarification: only drinks that explicitly increase your body heat will cause damage, e.g. Sbiten or hot chocolate. This can be counteracted with drinks that lower body temperature, but there are comparatively few of them (mint julep and iced beer are the only two I've found). Confirming that this issue still exists in current codebase as of 3/26/21 ( 1dfc45839d4b79dd98f8681a3238c335f23544d6 ); my character takes slight burn damage during spawn regardless of loadout.
