### ISSUE TITLE
carbon mobs issue

### ISSUE THREAD

**Issue by oooO0W0Oooo** [CHOMPStation2/CHOMPStation2#1533]
#### Brief description of the issue
through one of the updates, the ability to vore any and all carbon based mobs has been disabled 

#### What you expected to happen

for mobs to not be effected by this
#### What actually happened

mobs were effected by this
#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
i just want this to be fixed

**Comment by LuciusWorna** [comment]
Working the issue now
