### ISSUE TITLE
RUST Core, Gyrotron, and Injectors Unlinked

### ISSUE THREAD

**Issue by ZVB334** [CHOMPStation2/CHOMPStation2#1564]
All the RUST components are unlinked from the terminals roundstart requiring you to manually enter them in on each respective terminal. This is a bit of an issue if you don't know what each is already pre tagged with.

**Comment by ZVB334** [comment]
As a further note, the TGUI for the three terminals prints debug messages directly to VChat.

**Comment by ZVB334** [comment]
Suppose just as an update to this, the fusion core is still unlinked at round start.

**Comment by Razgriz1032** [comment]
Whoops, this actually got fixed by https://github.com/CHOMPStation2/CHOMPStation2/pull/1672
