### ISSUE TITLE
Water makes you wet!

### ISSUE THREAD

**Issue by Rykka-Stormheart** [CHOMPStation2/CHOMPStation2#160]
#### Brief overview of the feature

Stepping into a shower, being in the rain, or swimming in water will all apply various stacks of "soak" - these are how the system tracks how wet you are. Being above a certain soak will incur penalties, and if you're too cold, you'll get constant nag messages (possibly harmed?).

You'll also have a dripping water sound effect (possibly sprite graphic) play. Pace is dependent on your soak levels. Other people nearby can hear this, too.

#### What you want to happen

Being in a shower that's on, in the rain, or swimming (walking) on water tiles applies a "soaked" var to you. This var scales from 0-200.
0-25 is "damp". Not a big deal, no major temp changes.
25-50 is "wet". Slight temp changes, minor nag messages.
50-100 is "moderately soaked". Stronger temperature changes, non-constant nag messages.
100-200 is "completely/severely soaked". Extreme temperature changes (you'll be fucking freezing if your clothes are soaked through), and you'll have constant nag messages.
 
#### Anything else you may wish to add:
Perhaps add a method of drying off using an air dryer, standing on an air vent, etc.

**Comment by Darlantanis** [comment]
Nobody is going to work on this.
