### ISSUE TITLE
Science lacks a chemical dispenser on the station

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#174]
Title. This requires xenobotanists to rely on medical for unstable mutagen or trek to the chemical dispenser in xenooarchaeology and hope to god you won't need to make a second trip.

**Comment by InsanityKitten** [comment]
There actually is one in Xeno Biology. However, I agree, there should be more.

**Comment by Darlantanis** [comment]
On that note, it also lacks a chem master. Both would make xenobotany more convenient.
