### ISSUE TITLE
[QoL] Warn users for potential vore panel overwrites

### ISSUE THREAD

**Issue by ExabyteDiscord** [CHOMPStation2/CHOMPStation2#176]
Many times we've had users overwrite their vore panel due to accidentally hitting save when put into a mob. Suggestion is that if your current character isn't equal to the one in currently selected in the character creator, it'll give you a pop-up saying something like "WARNING: This will overwrite your vore panel" to hopefully help prevent stuff like that from happening accidentally.

**Comment by TheFurryFeline** [comment]
This'd be something to best implement for Virgo, not just for us. Probably isn't hard to code it, but can't think of a way right now.

**Comment by SpadesNeil** [comment]
Didn't this get implemented?
