### ISSUE TITLE
Shadekin traits appear to be "broken"

### ISSUE THREAD

**Issue by Saisni** [CHOMPStation2/CHOMPStation2#1763]
#### Brief description of the issue
At least one shadekin trait - Shadekin's Yellow Adaptation is broken when applied to a carbon shadekin character. 
Probably other ones are broken as well

#### What you expected to happen
The trait should hasten your energy regeneration while in the dark and apparently slow down or "drain" it when in light. 

#### What actually happened
Your energy is drained in the dark and you're able to regenerate energy only in light. 

#### Steps to reproduce
- Make a shadekin character by picking a Shadekin species in character setup
- Get yourself a neutral trait for Shadekin's Yellow Adaptation.
- "spawn" yourself on the map ingame or ask an admin. 
- Fidget around, the darkness drains energy very fast.

#### Code Revision
 Server revision: B:-Using TGS- D:-Using TGS-
Commit: 23af41589b0467eeb9c49649bca6231127453b7d
TGS version: 4.10.1
DMAPI version: 5.3.0 

#### Anything else you may wish to add:
- Without the trait you regenerate like a "normal" shadekin.

**Comment by Razgriz1032** [comment]
What the heck is this, we don't even use carbon shadekin.

**Comment by Saisni** [comment]
What do you mean? There's actual species of "Shadekin" you can pick and play as if an admin spawns you in.

**Comment by Saisni** [comment]
![Shadeboy](https://user-images.githubusercontent.com/71731828/114080182-c2d15a00-98b3-11eb-9611-296bf154ffd6.jpg)

**Comment by Razgriz1032** [comment]
We don't allow them to be spawned here, and any problems with them are likely from Virgo. Are you a downstream?

**Comment by Saisni** [comment]
Bruh
