### ISSUE TITLE
Mecha Phoron Bore not showing up in MechFab

### ISSUE THREAD

**Issue by InsanityKitten** [CHOMPStation2/CHOMPStation2#178]
#### Brief description of the issue
The Mecha mounted phoron bore I made is not showing up in the mechfab.

#### What you expected to happen
For it to be printable.

#### What actually happened
It's not there.

#### Steps to reproduce
- (Step 1) Get research to 5 in phoron, matierals, and power manip
- (Step 2) sync with mechfab
- (step 3) look for PB-23 "Phobos" Phoron bore and not find it

#### Code Revision
Server revision: master - 2020-01-19
9aaaa44acea3213d51d2ff8bd33d0d23399af177 
 
#### Anything else you may wish to add:
When setting up a test server with unedited code, I can see the mechfab design just fine. This leads me to believe that the server is not recognizing mechfab_designs_ch.dm.

**Comment by Rykka-Stormheart** [comment]
Should be resolved by https://github.com/CHOMPStation2/CHOMPStation2/pull/182

**Comment by ExabyteDiscord** [comment]
Issue was resolved!
