### ISSUE TITLE
Blood from syringes doesn't appear in glasses/carafe's.

### ISSUE THREAD

**Issue by GuiltyBeans** [CHOMPStation2/CHOMPStation2#1798]
While bartending, I attempted to use a syringe to inject blood into a drink mix to create Demon's Blood. Both blood from Pun-Pun, and my own character. Each time, a total of four tries, no units of blood appeared in the carafe, or glass, that it was attempted in. 

What you expected to happen:
Blood to be transferred from syringe to glass/container.

What actually happened:
No units of blood were transferred when injected into the aforementioned containers.

Steps to reproduce:
- (Step 1): Grab a syringe and draw blood from a living creature that contains blood.
- (Step 2) Try and inject the full syringe into a proper container, IE: Glass, Carafe, Cup or Beaker.

Addendum: With help from Mango we tested blood from an alternate source, a chemical dispenser cartridge - blood. The blood from the cartridge worked, even when injected via syringe. Seems to be a case of blood from bodies?

**Comment by Saisni** [comment]
It doesn't work in general. You can't add blood from beakers too, but you can mix a drink in a beaker.

**Comment by GuiltyBeans** [comment]
That doesn't make much sense to me, because not a month ago, or a few weeks, I was able to inject blood into cups using a syringe. No beaker mixing required, just straight into a cup. And the blood could come from any source.
