### ISSUE TITLE
Transforming deletes NIFs

### ISSUE THREAD

**Issue by zamizu** [CHOMPStation2/CHOMPStation2#195]
#### Brief description of the issue
Basically I was doing a scene involving transformation vore, and apparently changing a player's race also made their NIF vanish.

#### What you expected to happen
No consequences for transforming species

#### What actually happened
The player being transformed had their NIF removed.

#### Steps to reproduce
- Vore a person
- Transform into changing species
- Bam, NIF gone.

**Comment by TheFurryFeline** [comment]
This is a years old longstanding bug from Virgo..... Usually just fine to throw out an ahelp to get the NIF restored but as for fixing it, your guess is as good as mine on how.
