### ISSUE TITLE
Emote commands do not work for certain borgs

### ISSUE THREAD

**Issue by RedFoxChatterBox** [CHOMPStation2/CHOMPStation2#2064]
#### Brief description of the issue
Dogborgs do not have access to many emotes any more such as *yes, *no and the obvious *bark gestures.  Given they are dogborgs, *bark would make sense!

What is stranger is that other borg modules like the Drake can still do them.

#### What you expected to happen
Not sure why these were removed to begin with but can we get them back pretty please?

#### What actually happened
They went poof!

#### Steps to reproduce
- (Step 1)
- Become a Dogborg
- (Step 2)
- Type *bark or *yes
- (Step 3)
- Cry

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 513c6475541fd63afe06a077b48afb77d7b8655a
TGS version: 4.10.1
DMAPI version: 5.3.0 
 
#### Anything else you may wish to add:
None

**Comment by ZVB334** [comment]
*yes needs to be done as *yess for some reason because it ignores an S at the end of the prompt.
