### ISSUE TITLE
drinks require porting

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPStation2/CHOMPStation2#208]
old drinks from chompstation n' stuff haven't been ported yet. give me the drugs, please.

**Comment by Shadowfire117** [comment]
Will do with second casino phase!

**Comment by Shadowfire117** [comment]
Decided to do on its own and make a system so metaglass can use sprites from different dmi files. Once merged or already now this issue can be closed!

**Comment by Razgriz1032** [comment]
This has been completed
