### ISSUE TITLE
Mortemol does not function

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#211]
Judging by the code, mortemol is meant to temporarily revive dead carbons when splashed onto them (then drop them back to death when it wears off). This does not happen and no effects are observed.

This was tested with splashing, injecting then splashing, using a dermal patch, and attempting to apply the reagent via chemical smoke.

Splashing carbons generates the following runtime:
[2020-02-02T20:45:57] Runtime in phororeagent.dm,447: list index out of bounds

**Comment by Shadow-Quill** [comment]
Last time I tested this upstream, it functioned as intended

**Comment by Shadow-Quill** [comment]
And data should get set by this line here: https://github.com/CHOMPStation2/CHOMPStation2/blob/ab9e1f1c4c430c0064be58e5ba0f00567fd837ec/code/modules/Phorochemistry/phororeagent.dm#L438

**Comment by ExabyteDiscord** [comment]
We removed phorochem stuff so this shouldn't be a big deal for us anymore
