### ISSUE TITLE
Port Chompstation couches

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#215]
Couches from Chompstation before the rebase had as many possible colors as comfy chairs. Currently implemented couches allow you to choose between steel grey and steel grey (maybe more if you can craft couches out of more than steel).

There was also that ugly brown couch if we want that one back for some reason.

**Comment by Shadowfire117** [comment]
Just ported the old sofa a few hours ago in my code since my casino ship uses them, but I'll make sure that the modular sofa that can be made from different materials also gets ported properly.

**Comment by Darlantanis** [comment]
Fixed by #218
