### ISSUE TITLE
"Pilot" and "Field medic" jobroles toggle their priority together,

### ISSUE THREAD

**Issue by Raeschen** [CHOMPStation2/CHOMPStation2#2189]
![image](https://user-images.githubusercontent.com/30182250/121799354-e904d480-cc2b-11eb-8e7f-7ed5b41a0ac9.png)

As shown in image.
Valid at date of bugreport.

**Comment by Razgriz1032** [comment]
Duplicate of https://github.com/CHOMPStation2/CHOMPStation2/issues/1676
