### ISSUE TITLE
Torta's in-hand sprite is a pink square

### ISSUE THREAD

**Issue by radiantAurora** [CHOMPStation2/CHOMPStation2#2190]
#### Brief description of the issue
Picking Torta up TFs you into a pink square

#### What you expected to happen
See an armadillo in my hand

#### What actually happened
I'm now a pink square

#### Steps to reproduce
- Pick up Torta (and presumably any other armadillo)

#### Code Revision
Commit: b6dbf2cbb5ae2072de74c5a000a2f146718e1373
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/80002839/121814027-cc39c280-cc66-11eb-8808-10a9ad3fb9cd.png)

**Comment by Darlantanis** [comment]
Dug a bit, I missed this because it only occurs with the left-hand sprite. Right-hand defaults to a blank sprite while left defaults to a pink square.
