### ISSUE TITLE
Mining Material Processor alloys every subset of nested alloy recipes

### ISSUE THREAD

**Issue by Anomorphous** [CHOMPStation2/CHOMPStation2#221]
#### Brief description of the bug
Title. Putting in durasteel or plasteel, or borosillicate glass, as the alloy set for the processor creates every nested alloy. Durasteel creates regular steel, plasteel, and durasteel, and plasteel creates regular steel and plasteel.

#### What you expected to happen
The alloy to only create one sheet of the input alloy.

#### What actually happened
Every 'nested' recipe is output at once.

#### Steps to reproduce
Go mining
pick up hematite, carbon, platinum, and diamonds
put the durasteel recipe into the processor interface and turn it on

#### Code Revision
Running server on 2/10/20
 
#### Anything else you may wish to add:
https://media.discordapp.net/attachments/405257702663782400/676599440944922643/unknown.png
screenshot including overlay of multiple sheets

**Comment by TheFurryFeline** [comment]
Intended as stated in discord public dev channel
