### ISSUE TITLE
Drills VS Dismantling steel walls

### ISSUE THREAD

**Issue by JesusChristItsJasonBourne** [CHOMPStation2/CHOMPStation2#247]
#### Brief description of the issue
when you dismantle a steel wall following the proper deconstruction procedure, you lose material, but when you drill a wall with a drill, you keep all the steel sheets

#### What you expected to happen
the drill would lose steel sheets and leave shrapnel as it damages it, while actual dismantling would keep all the materials for re-use

#### What actually happened
the opposite of what makes sense

#### Steps to reproduce
- (Step 1) spawn in as engineer, grab tools and drill
- (Step 2) dismantle one wall properly, and smash open another with a drill
- (Step 3) cry because you're mechanically punished for doing your job properly

**Comment by ExabyteDiscord** [comment]
Both drills and welders now will leave behind 2 sheets. Partly fixed?
