### ISSUE TITLE
Dislocated legs and feet do not prevent someone from moving

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#248]
#### Brief description of the issue
Dislocating both legs and feet will not prevent the target from getting up and moving. The only thing that keeps them down is the occasional pain being too much and causing them to collapse for a few moments. This could be a big problem if you are trying to non-lethally subdue someone without cuffs, due to the fact that dislocation only disables and causes pain until it is fixed.

#### What you expected to happen
- Dislocate someone's legs and feet
- Watch them scream and flail on the floor, being unable to move.

#### What actually happened
- Dislocate someone's legs and feet
- Proceed to watch them get up on two dislocated legs and feet and run away slowly.

#### Steps to reproduce
- Dislocate both legs and feet
- Try to stand up and move around

**Comment by ExabyteDiscord** [comment]
Still not fixed. Likely due to the fact that general leg damage doesn't cause as much pain and won't make it impossible to walk if you break a leg or foot.
