### ISSUE TITLE
Jetpack Issue

### ISSUE THREAD

**Issue by YellowCloak** [CHOMPStation2/CHOMPStation2#249]
#### Brief description of the issue
It is not possible to use the jetpack to navigate when in deep space. By this, I mean that when there are no objects around, such as walls or floors, one loses the ability to control their movement in space, despite having a jetpack.

#### What you expected to happen
I expected to have full control over my movement in space, at the cost of jetpack fuel, despite having no gravity or flooring to move on.

#### What actually happened
Once I got a certain distance away from objects, likely after my momentum from moving off of them was used, I ended up flying in one direction, without stopping, until I reached another landmass and got near it. The jetpack was on and making particle effects the whole time.

#### Steps to reproduce
- (Step 1) Get a jetpack from the EVA near Security and attach it to a voidsuit.
- (Step 2) Walk out into space with the jetpack turned on, both thrusters and stabilizers.
- (Step 3) Go far enough into space that there are no objects nearby, such as grilles or latices. Having none on the screen should be enough, but the distance seemed arbitrary.
- (Step 4) Fly off into space and regret all life choices, sparkly trail marking the way.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Razgriz1032** [comment]
Unable to replicate issuse.
Softsuit https://i.gyazo.com/8e2d49c0d9105acd31bc142c2af079a6.gif
Voidsuit https://i.gyazo.com/bd74f68728bbf698685b2ec9b8657d66.gif

**Comment by Razgriz1032** [comment]
Issue was replicated by putting the jetpack in the suit item slot. The jetpack seems to work correctly when it is in the backpack slot.

This issue is found all the way upstream to Polaris, and has been a prevalent issue since two years ago, I now realize. (I thought it was only a problem with hardsuits.)

As a band-aid fix, I have enabled it so that you can put your backpack on all spacesuit suit item slots. You may put your backpack in your backpack slot.

**Comment by ExabyteDiscord** [comment]
Given the fix Raz mentioned, may as well close the issue. I'd assume this already has an issue up at Polaris, but if not, might be good to put one up there.
