### ISSUE TITLE
Security Outpost has no wire knot, thus depowers every shift without intervention.

### ISSUE THREAD

**Issue by Holdelta** [CHOMPStation2/CHOMPStation2#2511]
#### Brief description of the issue
The APC to the Security Outpost has no powered wire connected to it.

#### What you expected to happen
Most outpost rooms to be powered that have functioning devices.

#### What actually happened
This one room is depowered and gives power alerts every shift.

#### Steps to reproduce
- Step 1: Join game.
- Step 2: Check the APC in the Security Outpost
- Step 3: No power!

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 796c58e062c41191f999a65f14b7d701041ffc2c
TGS version: 4.11.1
DMAPI version: 5.3.0 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/7005665/125209558-700a9400-e24e-11eb-878b-5f336ec03711.png)

**Comment by Rykka-Stormheart** [comment]
Issue can safely be closed, this is fixed on master:
![](https://i.imgur.com/lDSx8Dc.png)

**Comment by Holdelta** [comment]
Confirming fix.
