### ISSUE TITLE
Sec officers can break into warden's office

### ISSUE THREAD

**Issue by JesusChristItsJasonBourne** [CHOMPStation2/CHOMPStation2#253]
#### Brief description of the issue
security officers that are otherwise blocked from warden's office can actually just enter it perfectly fine

#### What you expected to happen
not to be able to get into the warden's office

#### What actually happened
I realized that I can open the window and climb over the table

#### Steps to reproduce
- (Step 1) spawn in as security officer
- (Step 2) walk into warden doors
- (Step 3) get told no by warden doors
- (Step 4) walk into warden's front window
- (Step 5) realize you can just open the window
- (Step 6) host a party in the warden's office

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: master - 2020-03-04
d0ec2cc91129451b141cd69298f2375c57c77bfb

**Comment by Rykka-Stormheart** [comment]
Have been officer, can confirm.

**Comment by Razgriz1032** [comment]
> (Step 6) host a party in the warden's office

I FREAKING DIED

**Comment by Razgriz1032** [comment]
That's a map issue. Thanks for letting us know!
