### ISSUE TITLE
Falling onto a goat from the first floor that's located on the ground floor causes a loop

### ISSUE THREAD

**Issue by grz01** [CHOMPStation2/CHOMPStation2#2577]
Climb the rail on first floor, you normally drop down onto the ground floor and onto/into the mob/character below. With the goat it loops indefinately with '<char name> falls onto the goat!'

#### What you expected to happen
To it not to loop, to do an action.

#### What actually happened
With the goat it loops indefinitely with '<char name> falls onto the goat!'

#### Steps to reproduce
- put goat in chair around large table in bar.
- go to room above bar (can't remember name)
- climb onto rail adjacent to the chair the goat is in.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by CommodoreYouth** [comment]
This happens with more entities than just Goats.
