### ISSUE TITLE
Sprites for standard borg and ERT borg are broken

### ISSUE THREAD

**Issue by User-U-U** [CHOMPStation2/CHOMPStation2#2652]
#### Brief description of the issue
The sprites for ERT and standard borg are broken

#### What you expected to happen
Be an ERT borg

#### What actually happened
Oops sprite

#### Steps to reproduce
- Wait for Code red
- Become ERT
-  Oops Sprite
#### Code Revision
Commit:21534eef24a7e792afa0fe2b250fb1dd0b2a6ce4
TGS version: 4.11.1
DMAPI version: 5.3.0
 
#### Anything else you may wish to add:
Nope

**Comment by Razgriz1032** [comment]
What are the specific model names? (Not the job)

**Comment by User-U-U** [comment]
> What are the specific model names? (Not the job)

It is called ERT

**Comment by User-U-U** [comment]
Proper file for it is icons/mobs/64x64robot_vr.dmi

**Comment by Razgriz1032** [comment]
Fixed
