### ISSUE TITLE
Micro Mechs

### ISSUE THREAD

**Issue by InsanityKitten** [CHOMPStation2/CHOMPStation2#27]
#### Brief description of the bug
Micro mechs are configured wrong and are unable to equip anything. After checking a Ripley, there seems to be a different setup for equipment.

#### What you expected to happen
To plug equipment such as drill and mounted ore box onto a gopher

#### What actually happened
I got a message saying "you are unable to equip onto mech"

#### Steps to reproduce
- Build a mech for a micro. (Weasel, Polecat, or Gopher)
- Attempt to plug any equipment into it.

#### Code Revision
Server revision: master - 2019-12-28
d1ade01fbbc6501d5a76f93789d94b0e9eac11fd

**Comment by Razgriz1032** [comment]
No. This is working as intended. There are micro drills and hydraulic clamps that you must build instead. "Miniature Drill" is the title of the drill specifically.
https://github.com/CHOMPStation2/CHOMPStation2/blob/f914803532654806fc0004d85a937c6c5c86bcc3/code/game/mecha/micro/mechfab_designs_vr.dm#L43
