### ISSUE TITLE
Language implant not working

### ISSUE THREAD

**Issue by 123MrMango321** [CHOMPStation2/CHOMPStation2#2719]
The language implant gives you a prompt to use the *smile emote to activate it. However, using the emote causes nothing to happen. I've spawned several language implants and tried them to no success

**Comment by 123MrMango321** [comment]
Poked around a bit more and it seems the implant did work. Just languages don't show up in my known language page. I can understand other languages I do not have selected

**Comment by Razgriz1032** [comment]
I think it's not working for any implant
