### ISSUE TITLE
Placing tiles over lava results in the floor literally being lava

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#272]
Placing floor tiles over lava will result in the tile being placed (and looking like a normal floor) but otherwise still being lava. This results in ordinary floors which rapidly cause you to burn to death if you step on them.

Ideally either you shouldn't be able to place floor tiles on lava (probably an easier solution) or placing floor tiles on lava should create an ordinary floor which doesn't set you on fire.

**Comment by Darlantanis** [comment]
https://cdn.discordapp.com/attachments/415394551302324224/691067744451428474/unknown.png

**Comment by ExabyteDiscord** [comment]
This has since been partly fixed. You can't build on lava anymore, but it'll still use your materials. Lava still looks like lava when this happens.
