### ISSUE TITLE
Circuit Kits are Empty

### ISSUE THREAD

**Issue by ZVB334** [CHOMPStation2/CHOMPStation2#2723]
The roundstart circuit kits in the circuit lab are empty.

**Comment by CommodoreYouth** [comment]
Circuit Kits are currently affected by a code bug that renders their contents unable to be seen.
Roundstart Circuit Kits are mechanically still full, and have all of their usual contents, but their inventories will not show up no matter how you try to open them like you would a box in your other hand, or a backpack.

Currently, you can dump their contents on the floor by using the Circuit Kit in your active hand.  The various circuit containers inside of the kits are also affected by this same bug, and need to be dumped out on the floor the same way.

Luckily, clicking a Circuit Kit or Circuit box on a tile occupied by what goes into the container in question will collect all of the items off that tile back into the container, much like a Rapid Part Exchange Device does with components, IE dumping out a Power Circuit box, then clicking it on the tile where the items are will put them all back into the box.

**Comment by xnqm8h** [comment]
In version `B:4971-suspension-field-sprite-missing D:2022-09-21` of Chompstation circuit kits seem to be rendering correctly. Suggesting this issue to be closed. @Darlantanis @Razgriz1032

**Comment by ZVB334** [comment]
> In version `B:4971-suspension-field-sprite-missing D:2022-09-21` of Chompstation circuit kits seem to be rendering correctly. Suggesting this issue to be closed. @Darlantanis @Razgriz1032

The contents of the circuit kits, not their actual sprites. Like if you click on it like a box it won't show its contents.
