### ISSUE TITLE
Crafting button doesn't work

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#2729]
#### Brief description of the issue
Crafting button does nothing.

#### What you expected to happen
Press crafting button, get crafting menu.

#### What actually happened
Nothing.

#### Steps to reproduce
Press crafting button.
 
#### Anything else you may wish to add:
Apparently works upstream so we're likely either missing something of have conflicting code elsewhere.

**Comment by Razgriz1032** [comment]
Finally fixed after 1000 years
