### ISSUE TITLE
No Mining redemption machine on planet

### ISSUE THREAD

**Issue by Cabbagesushi** [CHOMPStation2/CHOMPStation2#28]
There is no Mining Redemption machine on planetside mining, making them take the shuttle up to cargo to get any rewards from mining. Not to mention it is also outside in the cargo lobby for some reason as well.

**Comment by lowpowermia** [comment]
ALSO. No voidsuit cycler.

**Comment by Razgriz1032** [comment]
Need a mapper to look at this.
