### ISSUE TITLE
Outpost medical won't let anyone without medical access in, +suggest

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPStation2/CHOMPStation2#281]
Title, and also a suggestion: Keep cryo blocked off from those without medical access, but keep the sleeper out for those without it to use. It can keep someone alive for a long while while they wait for a paramedic or something to arrive.

Another thing might be for backups to be out for people to use down there, as well. Leaving out a white medkit or two, or have the supply of medkits be out for regular crewmembers might be good as well, due to the encounters that can happen out in the wilderness. Bleeding, burning, and radiation, etc. They need at least a white medkit.

Vitals scanner would also have to be behind the window, though.

**Comment by Kazzc** [comment]
Easy fix. Will get around working on this.
