### ISSUE TITLE
Buckling to chairs and ATVS don't mix

### ISSUE THREAD

**Issue by lowpowermia** [CHOMPStation2/CHOMPStation2#282]
#### Brief description of the issue
If you buckle someone to a chair and ram them with an ATV, you fucking execute them.

#### What you expected to happen
I expected to run over four monkeys in a row.

#### What actually happened
I committed a warcrime. I slammed a monkey 300 times in the chest, with vehicular manslaughter strapped across my breast.
#### Steps to reproduce
- (Step 1) Get ATV
- (Step 2) Get your not-so-close friends
- (Step 3) Buckle 'friend' to chair.
- (Step 4) Gently apply ATV to friend
- (Step 5)
![image](https://user-images.githubusercontent.com/19172834/77814592-ab4c7800-7088-11ea-9572-94be837221ea.png) Warcrimes.

#### Code Revision
iunno
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/19172834/77814602-c8814680-7088-11ea-938d-7fe187944f61.png)
Monkey squad five has been slain.

**Comment by Razgriz1032** [comment]
Won't fix, best bug

**Comment by ExabyteDiscord** [comment]
![image](https://user-images.githubusercontent.com/24572022/132263442-eddf3502-ba97-40da-a239-c7711c268a13.png)
absolute not fixed. This is fine, closing anyways

**Comment by lowpowermia** [comment]
new smite idea
