### ISSUE TITLE
Light replacer in engineering and/or large light tubes for spotlights in lathe

### ISSUE THREAD

**Issue by storesund98** [CHOMPStation2/CHOMPStation2#287]
It is really annoying when we get an overload and engineering cannot replace all its lights quickly... And we cant fix the spotlights in Atmos because we cant print the tubes for those.
Could we please have a light replacer in engineering?

**Comment by Razgriz1032** [comment]
No, replacing lights is a janitorial job. Janitor gets a light replacer in their lockers.
