### ISSUE TITLE
Trying to welder bomb calls you gay

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#29]
Title

**Comment by Razgriz1032** [comment]
I only see four files that mention the word gay, and none of them are welder bombs.
https://github.com/CHOMPStation2/CHOMPStation2/search?q=gay&unscoped_q=gay

**Comment by Razgriz1032** [comment]
It calls you gaypwned, which is why I couldn't find it. You gotta be specific. Changed now tho.
