### ISSUE TITLE
Suit cyclers do not work

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#290]
#### Brief description of the issue
Using a suit cycler to cycle voidsuits results in the cycler being infinitely stuck on the "Please wait..." screen. As a result, only humans can use voidsuits. 

#### What you expected to happen
Suit cycler properly cycles voidsuits.

#### What actually happened
Suit cycler freezes on "Please wait..."

#### Steps to reproduce
1. Place any voidsuit in a suit cycler.
2. Cycle the voidsuit.
3. Cry.

#### Code Revision
bd466fcc18525e3014d5b3ad25dc07837bb2f2ed 
 
Runtime:
[2020-04-08T21:57:46] Runtime in suit_storage_unit.dm,934: bad index
   proc name: finished job (/obj/machinery/suit_cycler/proc/finished_job)
   usr: (the floor) (113,156,2) (/turf/simulated/floor/tiled) (nadyr)
   usr.loc: (the floor) (113,156,2) (/turf/simulated/floor/tiled) (nadyr)
   src: Engineering suit cycler (/obj/machinery/suit_cycler/engineering)
   src.loc: the floor (113,157,2) (/turf/simulated/floor/tiled/dark)
   call stack:
   Engineering suit cycler (/obj/machinery/suit_cycler/engineering): finished job()
   Engineering suit cycler (/obj/machinery/suit_cycler/engineering): Topic("src=\[0x2008f8e];apply_paintjo...", /list (/list))

**Comment by Razgriz1032** [comment]
Fixed by #293
