### ISSUE TITLE
Wildlife on Sif not hostile - it should be

### ISSUE THREAD

**Issue by Rykka-Stormheart** [CHOMPStation2/CHOMPStation2#2967]
#### Brief description of the issue

Spiders, kuruaks, etc are non-hostile, and allowed me to pet them.
Mercs were still hostile, as were viscerators.

#### What you expected to happen
To come across spiders and get brutally murdered

#### What actually happened
Sonya Valyruska pets the giant spider. x2
Sonya Valyruska pets the giant spider. x2

#### Steps to reproduce
- Go to Sif Wilds
- Pet spooder

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 98d69a0cddd3e268bf4cd9b399991ac6562acd5c
TGS version: 4.14.3
DMAPI version: 5.3.0

**Comment by Tsybal** [comment]
It was a nest outside of a building, several giant spiders that seemed to be more interested in webbing red candles than doing anything.

a cave of Kuruaks also were not hostile, it was snowing at the time, these were all in the Wilderness.

a merc outpost, and a second spider den WERE hostile, and mobs in the mines were behaving normally.

**Comment by VictorZisthus** [comment]
Was this the wilderness chapel POI by chance? I think there is an override just for the chapel spiders. Pacified by design. No idea WHY, but it WAS intentional by whoever did it.

**Comment by Rykka-Stormheart** [comment]
Might've been, but there's been other non-hostile wildlife too. I'll review the wilderness POIs later today and confirm

**Comment by VictorZisthus** [comment]
If ya find anything lmk and I can fix it in the map PR I have open
