### ISSUE TITLE
Ghosts can steal bullet casings

### ISSUE THREAD

**Issue by JesusChristItsJasonBourne** [CHOMPStation2/CHOMPStation2#2992]
#### Brief description of the issue
Ghosts can gain access to an object interactions tab that only pops up in context and use it to have unexpected interactions with bullet casings

#### What you expected to happen
for the pick up object verb to do nothing because I am a ghost

#### What actually happened
every single bullet casing that was on my visible screen is now gone.

#### Steps to reproduce
- (Step 1) Spectate
- (Step 2) Find a crime/combat scene
- (step 3) notice the extra tab
- (step 4) click on pick up object via the new tab
- (step 5) the evidence is now deleted, detectives BTFO

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:-Using TGS- D:-Using TGS-
Commit: a0f76219c341ce46a6dd4f36364990079c14d356
(this occurred live)
#### Anything else you may wish to add:
- crab

**Comment by JesusChristItsJasonBourne** [comment]
it may also not be limited to the ghost's screen size, as every spent casing on the map vanished.

**Comment by cadyn** [comment]
> 
> 
> it may also not be limited to the ghost's screen size, as every spent casing on the map vanished.

This may be caused by the cleanup subsystem, which is a new addition and automatically cleans up a few unnecessary objects such as bullet casings. In this case, it's not a bug, and an intended feature.

**Comment by JesusChristItsJasonBourne** [comment]
closing this issue, bug was unable to be recreated and is presumably coincidence to the cleanup subsystem.
