### ISSUE TITLE
My new guns added are kinda broke tho

### ISSUE THREAD

**Issue by SilencedMP5A5** [CHOMPStation2/CHOMPStation2#3068]
https://github.com/CHOMPStation2/CHOMPStation2/pull/3037
related pr

When Cadyn added my new gats, they didn't really finish them. 
Bunch of issues, here's a list.

- ~Kord 6P50 does not function, nor have a sprite.~
- ~PKM functions but also does not have its sprite ingame.~
- ~RPD is same as above~
- ~AKM does not change to the correct sprite when it has an RPK drum loaded~
- ~Plamya Mk. 1 and Mk. 3 are backwards spritewise, Mk. 1 has the Mk. 3 sprite, Mk. 3 has the Mk. 1 sprite.~
- ~Uzi does not use the new sprite~
- Sec pistols, same as above 
- Energy gun, same as above
- ~C20r, same as above~
- Energy sniper, same as above
- L6 SAW, same as above
- Ion rifle, same as above
- ~Z8 bulldog, same as above~
- ~WT-550, same as above~
- ~Spas 35's sprite disappears when it is emptied~
- ~T-12 uses M41A magazines for some reason?? And, can't load them back into the gun once removed.~
- ~T-12 is also supposed to be caseless~
- ~M41A and M41A/2 also supposed to be caseless~
- ~FAL cannot be reloaded with its own magazines.~
- The Stetchkin wasn't added
- ~The TP23 also wasn't added~
- PPK and PPK light also weren't added
- ~The shorty shotgun only has 4 shells~

#### What you expected to happen
things to not be broken and everyone to have a good time with shiny new gats

#### What actually happened
things were broken because cadyn got mad and just yeeted what was done at github and left

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: ed39a7f0b802760fb69c7e0ad13a959d2d603442
TGS version: 4.14.3
DMAPI version: 5.3.0
The following pull requests are currently test merged:
https://github.com/CHOMPStation2/CHOMPStation2/pull/2893">#2893: 'Cleanup subsystem' by cadyn at commit 924422685f
https://github.com/CHOMPStation2/CHOMPStation2/pull/2965">#2965: 'New Teleporter Pad System. Removing Shuttle 1 and 2' by Enzo-Leon at commit 12845f29a3 
####
~if you go to fix this, contact me on discord for the descriptions on the stetchkin, tp23, and ppk's~

 i unbroke a bunch of things myself but this is still relevant

**Comment by Razgriz1032** [comment]
Actually I think it is due to #3037
