### ISSUE TITLE
CE hardsuit missing teshari sprites

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#310]
CE hardsuit no longer has teshari sprites when worn by a teshari. This was probably broken by the upstream PR.

#### Code Revision
0e6b75205830d84aca89351e3642d72a036a071c

**Comment by TheFurryFeline** [comment]
RIGs also giving me issues.  Vulp tail doesn't show when wearing CE RIG as Sam,  RD RIG doesn't show Sergal tail when wearing as Lillian.
