### ISSUE TITLE
CE RIGS - Vulp Edition

### ISSUE THREAD

**Issue by TheFurryFeline** [CHOMPStation2/CHOMPStation2#317]
#### Brief description of the issue
CE RIGs for Vulp bodies are borked, goes invisible with chestplate

#### What you expected to happen
Vulp Tail, full body coverage.

#### What actually happened
No tail sprite, basically nothing happening with the chestpiece going invisible.

#### Steps to reproduce
- (Step 1) Be a Vulp or have a custom char with base Vulp sprite
- (Step 2) Wear CE RIG
- (Step 3) HELP! I HAVE NO TAIL!

#### Code Revision
- [eb3d14a9fef3c15711e9bb986a19e3c1470cbfd8]
 
#### Anything else you may wish to add:
- 
![image](https://user-images.githubusercontent.com/38586851/80431335-3191ef00-88bf-11ea-8c95-6b32e7ecbd5f.png)

**Comment by Razgriz1032** [comment]
My mistake, this will be fixed already.
