### ISSUE TITLE
Ar projection spam

### ISSUE THREAD

**Issue by Azurachi** [CHOMPStation2/CHOMPStation2#3196]
#### Brief description of the issue

i was clicking the ar projection button while in a soul catcher and it made FOUR OF ME
#### What you expected to happen
for one ar projection to appear

#### What actually happened
multiple appeared

#### Steps to reproduce
- (Step 1) server lagging
- (Step 2) push button a bit too many times

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:-Using TGS- D:-Using TGS-
Commit: fcf2ddfc9d95629edae2d04a070493c2f616add1
TGS version: 4.14.3
DMAPI version: 5.3.0
The following pull requests are currently test merged:
https://github.com/CHOMPStation2/CHOMPStation2/pull/2965">#2965: 'New Teleporter Pad System. Removing Shuttle 1 and 2' by Enzo-Leon at commit 12845f29a3

**Comment by radiantAurora** [comment]
To note as a witness; the excess AR projections did not remove themselves when Azura ended AR projection and had to be cleaned up by an admin.
