### ISSUE TITLE
Rags can smother through face protection

### ISSUE THREAD

**Issue by Dinnel** [CHOMPStation2/CHOMPStation2#340]
#### Brief description of the issue
I read the rag code on here and didn't see any checks for face protection so I decided to test them by getting myself smothered by a rag with chloral hydrate. I immediately get knocked down and pass out soon after, despite having a security voidsuit on, internal being on, AND wearing a breathing mask beneath it all.

#### What you expected to happen
Rag full of sleep juice harmlessly gets rubbed in my face.

#### What actually happened
Inhaled sleep juice from the rag **through my metal suit**... **_with internals on_**.

#### Steps to reproduce
- Take rag filled with favorite chemical
- Wear (or find someone with) face protection
- Watch them turn horizontal... or magically heal.

#### Code Revision
- 2020-05-08
 
#### Anything else you may wish to add:
- I believe it's because there isn't any check for face protection that the rag can penetrate but I'm no expert.

**Comment by Draycu** [comment]
You were right, there was no check!  Made a pull request~!

**Comment by Darlantanis** [comment]
Fixed by #440
