### ISSUE TITLE
Autolathe converts plasteel put into it into steel and platinum.

### ISSUE THREAD

**Issue by Cyrelius** [CHOMPStation2/CHOMPStation2#3509]
#### Brief description of the issue
Whenever you insert plasteel into an autolathe, it converts it immediately into platinum and steel.

#### What you expected to happen
It to take plasteel into its own inventory, like any other machine.

#### What actually happened
It splits the plasteel, when it should not.  This prevents you from making durasteel, or other materials that use plasteel as an ingredient, in the autolathe.

#### Steps to reproduce
- put plasteel into autolathe
- check inventory of autolathe

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 699cbd8689eb818bb18885f18398c70ac75a4b24
TGS version: 4.15.7
DMAPI version: 5.3.0
The following pull requests are currently test merged:
https://github.com/CHOMPStation2/CHOMPStation2/pull/3203">#3203: 'Porting a hefty chunk of Citadel mobs.' by BlackMajor at commit 6b4ccac9db
https://github.com/CHOMPStation2/CHOMPStation2/pull/2965">#2965: 'New Teleporter Pad System. Removing Shuttle 1 and 2' by Enzo-Leon at commit f279880a3a 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Razgriz1032** [comment]
Upstream issue https://github.com/PolarisSS13/Polaris/issues/8363
