### ISSUE TITLE
Slimes in Xenobio not eating properly

### ISSUE THREAD

**Issue by Tsybal** [CHOMPStation2/CHOMPStation2#3515]
#### Brief description of the issue
Slimes don't properly go after monkeys when presented. Sometimes they can be 'prompted' into attacking a monkey by passively grabbing them.

Slime Friendship Agent (not docility) seems to prevent them attacking monkeys at all, preventing them being bred unles you reset them by eating them and ejecting them again.

#### What you expected to happen
Monkeys to be attacked on sight by slimes regardless of whether they have been friendshipped or not.

#### What actually happened
they just sit there, even when grabbed or shaken.

#### Steps to reproduce
- (Step 1)
- Make slimes
-
- (Step 2)
- Breed out slimes, occasionally they will just refuse to eat a monkey, but can be jogged by passively grabbing.

(step 3)
get to pinks and light pinks, use a Friendship (not docility agent), slimes refuse to interact with monkeys at all, until vored and ejected, which seems to reset them.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 Server revision: B:-Using TGS- D:-Using TGS-
Commit: 7582ceaab497e8c35e863f9df961798eb0a7a20d
TGS version: 4.15.7
DMAPI version: 5.3.0
The following pull requests are currently test merged:
https://github.com/CHOMPStation2/CHOMPStation2/pull/3203">#3203: 'Porting a hefty chunk of Citadel mobs.' by BlackMajor at commit 6b4ccac9db
https://github.com/CHOMPStation2/CHOMPStation2/pull/2965">#2965: 'New Teleporter Pad System. Removing Shuttle 1 and 2' by Enzo-Leon at commit f279880a3a 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cyrelius** [comment]
I can confirm this, and it's irritating.
