### ISSUE TITLE
Can no longer generate liquids via 'processing' creatures.

### ISSUE THREAD

**Issue by Dinnel** [CHOMPStation2/CHOMPStation2#355]
#### Brief description of the issue
Woke up with a weird idea to see what would happen if I gurgl'd someone at 0 in both fields and as I tried to see how much it would take, I discovered I couldn't generate ANYTHING from processing someone.

#### What you expected to happen
Gain fluid from 'processing' characters

#### What actually happened
Nothing (besides getting fat)

#### Steps to reproduce
- Nom someone
- Make sure all fluid modes are turned on (besides production)
- Process them via any of the respective modes.
- Notice no fluid is being made.

#### Code Revision
- 2020-05-14
 
#### Anything else you may wish to add:
- I'm guessing the update broke more than just fluid production. Technically you could use the nutrition gained to convert into fluid so it isn't a big issue, but it's there.

**Comment by Darlantanis** [comment]
Fixed by #974
