### ISSUE TITLE
barricades.dm code errors

### ISSUE THREAD

**Issue by NK1605** [CHOMPStation2/CHOMPStation2#3558]
#### Brief description of the bug
the file code\game\objects\structures\barricades.dm has multiple errors when compiling

#### What you expected to happen
it should compile without errors nor warnings

#### What actually happened
the compiling of the environment failed with an error on code\game\objects\structures\barricades.dm line 153, when attempting to fix multiple errors showed up on line 154 of the same file

#### Steps to reproduce
- dowload the repo
- compile the environment file

**Comment by Rykka-Stormheart** [comment]
Which version of BYOND are you on? Older versions have an error compiling, I'm on 514.1569 and have no such issue on compile.
