### ISSUE TITLE
Missing piping and cabling

### ISSUE THREAD

**Issue by YellowCloak** [CHOMPStation2/CHOMPStation2#367]
#### Brief description of the issue
There is a tile, outside operating room 2 in medical, that has no piping nor power cable under it. This results in failing atmos and power in the area to the east. The tile is the one directly south of Recovery Ward Vent Pump 3.
#### What you expected to happen
The atmos piping and a power cable to be under the tile I pulled up, connecting all sides.

#### What actually happened
I pulled up the tile to reveal nothing beneath.

#### Steps to reproduce
- (Step 1) Go to medical and proceed to the designated tile.
- (Step 2) Pull up the tile with a crowbar.
- (and so on) Bask in the nothingness beneath.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![Capture](https://user-images.githubusercontent.com/60055070/82788213-dbac5a80-9e1c-11ea-920c-9980efd97140.PNG)

**Comment by Razgriz1032** [comment]
Where did that nanomed come from? I didn't even touch that one, reeeee

**Comment by Razgriz1032** [comment]
Resolved
