### ISSUE TITLE
Permanently broken syringe for borgos after accidental harm poke

### ISSUE THREAD

**Issue by Movler** [CHOMPStation2/CHOMPStation2#370]
#### Brief description of the issue
syringe permanently broken after use

#### What you expected to happen
hopefully it not break

#### What actually happened
it broke

#### Steps to reproduce
Accidentally harm syringe someone

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: f40addcd37a84ed34fa4c90dbdec9c79dc906080
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0

**Comment by Darlantanis** [comment]
Fixed by #513
