### ISSUE TITLE
Icon charge meter vanishing after recharging

### ISSUE THREAD

**Issue by Movler** [CHOMPStation2/CHOMPStation2#371]
#### Brief description of the issue
When you go recharge yourself as a borgo your charge meter icon dissapears

#### What you expected to happen
the charge meter icon to stay

#### What actually happened
it went away when charging in the pod

#### Steps to reproduce
Enter charge pod
Get charged
it vanishes

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: f40addcd37a84ed34fa4c90dbdec9c79dc906080
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0

**Comment by Arokha** [comment]
Hi Movler. Also I think this is intentional, after the move to /tg/ style alerts, that the screen only shows alerts rather than having permanent hunger/charge/etc bars. Could be wrong, though!

**Comment by Kazzc** [comment]
That is correct.
As a carbon, once their hunger has been satiated the hunger icon vanishes, if you continued to eat you get the "stuffed stomach" icon for over eating.

Same applies with Synths, as one can over-charge and get the "stuffed icon" for over eating. So don't be a fatty. ;p
