### ISSUE TITLE
Aurora caelus event is pointlessly intrusive

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#392]
Title. The excessive fully narrated opening paragraph, background music, and fully narrated closing paragraph take what could have been an intriguing random occurrence and make it obnoxious. The simplest fix will be disabling it.

I'll also note the event itself does not always fit. 
![image](https://user-images.githubusercontent.com/41974248/87500988-f4bad600-c62b-11ea-884c-86586808ece8.png)

**Comment by Rykka-Stormheart** [comment]
I'd suggest simply disabling the voiceline (relatively easy to do, I can PR that in a sec.). Regarding the 'fitting', it uses ion storm code, so if there's something wonky with that, that's likely the reason.

**Comment by Rykka-Stormheart** [comment]
If it's also happening commonly, I'd again advise that you look at tuning the rarity further if you're worried about it
