### ISSUE TITLE
Which branch do i compile for the weekly update?

### ISSUE THREAD

**Issue by Tollaway** [CHOMPStation2/CHOMPStation2#396]
#### Brief description of the issue
I cannot find the latest working weekly version

#### What you expected to happen
to compile without errors

#### What actually happened
I get 2 errors

#### Steps to reproduce
- Try to compile any of the recent branches
- See the error

**Comment by ExabyteDiscord** [comment]
You may want to make sure that your byond version is up to date, as having an older version tends to cause compilation errors for inexplainable reasons.

**Comment by Razgriz1032** [comment]
Only use master branch.

Also there are no weekly updates. Stuff just comes and goes all the time.
