### ISSUE TITLE
AI can track crew outside of camera range even if it can't see them

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#40]
#### Brief description of the issue
The AI seems to be capable of tracking players anywhere on the map, even if the players cannot be seen (i.e. the area is just static on the screen). This is problematic as anything visible (turfs, objects, etc.) can provide context clues about the players' location which can be abused during events/antag.

#### What you expected to happen
Players are only trackable when in camera range

#### What actually happened
Players are trackable everywhere

#### Steps to reproduce
1. Be AI
2. Track players

**Comment by VictorZisthus** [comment]
The AI can do this only if suit sensors are set to tracking, IIRC.
