### ISSUE TITLE
No join announcement when spawning on shuttle

### ISSUE THREAD

**Issue by ExabyteDiscord** [CHOMPStation2/CHOMPStation2#401]
#### Brief description of the issue
Whenever someone joins the station through the shuttle, their join announcement doesn't get played to the station.

#### What you expected to happen
You'd hear when someone joins via shuttle, while you're on station

#### What actually happened
The join announcement only gets played to them and maybe other people on the shuttle, and not to everyone on the station.

#### Steps to reproduce
- Exist on station
- Have someone join station through shuttle
- Be disappointed that you'll never know they showed up unless they speak

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Darlantanis** [comment]
Fixed by #502
