### ISSUE TITLE
Z8 Battle Rifles turning invisible upon magazine removal

### ISSUE THREAD

**Issue by icowom** [CHOMPStation2/CHOMPStation2#4037]
#### Brief description of the issue
 Z8 rifles go invisible and can't ne interacted with when I take out the magazine from the rifle.

#### What you expected to happen
Weapon sprite to be visible in hand and on surface, and also interactable.

#### What actually happened
https://cdn.discordapp.com/attachments/313725433780633612/962025588854497300/unknown.png

Printscreen of which hand the weapon is supposed to be. Ammo counter registers it there.. But nothing else. Even the character sprite shows it existing but nothing happens

#### Steps to reproduce
- (Step 1) Gun sprite is on char, and it fired one last chambered round. But invisible in hand and on the ground/surfaces

- (Step 2)can't be further interacted with
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Rykka-Stormheart** [comment]
https://github.com/CHOMPStation2/CHOMPStation2/pull/4034

Should fix this once it's merged.
