### ISSUE TITLE
SECURE BREIFCASE CAN BE OPENED WITHOUT USING CODE AT ALL

### ISSUE THREAD

**Issue by Azurachi** [CHOMPStation2/CHOMPStation2#4053]
#### Brief description of the issue

Alt clicking on a secure breifcase bypasses the entire process of having to put a code in
#### What you expected to happen
for it to not open

#### What actually happened
it opened.

#### Steps to reproduce
alt click on a secure breifcase 
#### Code Revision
Was unable to get but it was on the test server for the new map.

**Comment by VictorZisthus** [comment]
Can confirm, works on the wall-mounted safes too. Not very secure!

**Comment by VictorZisthus** [comment]
Right. Dug through the code a bit on my lunch break. Putting this comment here to remind me.

TO TEST:
Can this bug be performed on the access restricted Medal lockbox?

If not, a temporary fix may involve putting a maintenance access requirement on safes. Don't know how well that would go over with the code though.

When I get home I'll have to see what the alt+click calls on and why it does not check for locked items.

A great fix would be to have the alt+click simply check for access. A less optimal fix would be to put in code for every hand storage item that can be locked.

Will look into this more when I get home.

https://github.com/CHOMPStation2/CHOMPStation2/blob/master/code/game/objects/items/weapons/storage/lockbox.dm

**Comment by VictorZisthus** [comment]
I still need to look into this.

Mapping is a drug.

**Comment by VictorZisthus** [comment]
TIME FLIES.

Reminder boop for myself.

**Comment by VictorZisthus** [comment]
Here we go. I think this is the culprit...
https://github.com/CHOMPStation2/CHOMPStation2/blob/61419e598b92c558892ac005dfb43965a064a4ee/code/game/objects/items/weapons/storage/storage.dm#L161
