### ISSUE TITLE
Free Conversion to Other Glass Types

### ISSUE THREAD

**Issue by ZVB334** [CHOMPStation2/CHOMPStation2#4059]
#### Brief description of the issue
Placing down a single piece of one type of glass down onto a near full stack of another type of glass turns it into the type of glass dropped.

#### What you expected to happen
Placing some reinforced glass on the same tile as normal glass to have one stack of normal glass and one stack of reinforced glass.

#### What actually happened
I went from having 40 sheets of regular glass and 10 sheets of reinforced glass to having 50 sheets of reinforced glass and no normal glass.

#### Steps to reproduce
- Place normal glass on the ground.
- Drop any other form of glass that isn't regular glass. For best results, drop reinforced borosilicate for free additional sheets.
- Marvel at mastering alchemy and converting glass types to other glass types.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: [4b557a9dc9bbda44bc55eea0acfc1b5f6f69c57d]
TGS version: 4.15.7
DMAPI version: 5.3.0

**Comment by VictorZisthus** [comment]
I can't seem to replicate this on live. Any update on if this is still a thing?
