### ISSUE TITLE
Alcowomy bug involving tiles 

### ISSUE THREAD

**Issue by Azurachi** [CHOMPStation2/CHOMPStation2#4069]
#### Brief description of the issue
So any floor tile can be merged into another so say you have one steel tile but 8 wood floor tiles if you click on the 8 floor wood tiles with the single steel floor tile  it will now be converted into 9 steel floor tiles.

#### What you expected to happen
For them not to merge.

#### What actually happened
The tiles merged.

#### Steps to reproduce
get floor of choice
get second floor of choice 
apply which one to which one you want to merge
bam tiles merged
#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 217ca36
TGS version: 4.15.7
DMAPI version: 5.3.0
#### Anything else you may wish to add:
https://cdn.discordapp.com/attachments/405257702663782400/964103066569830460/alchemy.mp4

**Comment by Rykka-Stormheart** [comment]
Pre-existing issue, likely related to this:
https://github.com/CHOMPStation2/CHOMPStation2/issues/4059

My guess is the stack PR from /tg/ was not implemented correctly by us or upstream.
