### ISSUE TITLE
Aurora Cooking Feedback Thread

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#409]
OOC channel is getting cluttered so I'm directing people here for feedback regarding aurora cooking. Plus also helps to keep everything in one place in the event we end up with several PR's.

If you're posting feedback please check if the issue(s) still exists in the current code.

**Comment by Rykka-Stormheart** [comment]
Thank you! <3

**Comment by Darlantanis** [comment]
Nevermind I guess.
