### ISSUE TITLE
Change Item Size of Autoinjectors

### ISSUE THREAD

**Issue by xnqm8h** [CHOMPStation2/CHOMPStation2#4097]
#### Brief description of the issue
Autoinjectors are too big to fit in the syringe case where it's stated the intent is that they should indeed fit. I believe this is because they are too large and need to be item size: tiny.

#### What you expected to happen
To be able to put autoinjectors in the syringe case.

#### What actually happened
It does not accept autoinjectors.

**Comment by VictorZisthus** [comment]
A good fix for this could be to add the auto injectors to that items whitelist and see if that helps.

I'll have to see if I can get my local server back up and running to test this.

**Comment by xnqm8h** [comment]
They are already whitelisted @VictorZisthus
