### ISSUE TITLE
Denectrotising a dragon makes he sprite do am funny

### ISSUE THREAD

**Issue by Raeschen** [CHOMPStation2/CHOMPStation2#4100]
#### Brief description of the issue
denectrotise a dragon. Spride go oof

#### What you expected to happen
sprite not go oof

#### What actually happened
sprite did this
![image](https://user-images.githubusercontent.com/30182250/163729355-364c0d1b-e680-4c19-97b4-d19abf2d1283.png)

#### Steps to reproduce
- get denecrotiser
- use on dead 'Large dragon" 
- observe an oof

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: [414b01d8bc4245af0d37eac3761e1cf9d4002e93](http://127.0.0.1:49527/tmp5644/%3Ca%20href=%22https://github.com/CHOMPStation2/CHOMPStation2/commit/414b01d8bc4245af0d37eac3761e1cf9d4002e93%22%3Ehttps://github.com/CHOMPStation2/CHOMPStation2/commit/414b01d8bc4245af0d37eac3761e1cf9d4002e93%3C/a%3E)
TGS version: 4.15.7
DMAPI version: 5.3.0
The following pull requests are currently test merged:
[https://github.com/CHOMPStation2/CHOMPStation2/pull/3064](http://127.0.0.1:49527/tmp5644/%3Ca%20href=)">#3064: 'Update Ambient Sounds 3.0' by Rykka-Stormheart at commit cd4434db7a

**Comment by ExabyteDiscord** [comment]
schrodinger's drgn
