### ISSUE TITLE
X-ray guns have no sprite

### ISSUE THREAD

**Issue by R3dtail** [CHOMPStation2/CHOMPStation2#4101]
#### Brief description of the issue

X-ray guns have no sprite
#### What you expected to happen

Open an  experimental energy weapon crate, and see guns
#### What actually happened
Spriteless guns

#### Steps to reproduce
Get an x-ray gun, marvel at no sprite

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by VictorZisthus** [comment]
**There was a miscommunication between the manufacturer and NT. The guns work fine, but they are unfortunately completely invisible, especially to X-rays.

We apologize for the inconvenience.

_ - Have a secure day.**_


I can totally see that exchange happening.
