### ISSUE TITLE
Back up batteries don't have a sprite

### ISSUE THREAD

**Issue by R3dtail** [CHOMPStation2/CHOMPStation2#4115]
#### Brief description of the issue
https://puu.sh/IVre5/fbe0a8e765.png

#### What you expected to happen
Have a sprite

#### What actually happened
Booted up gmod

#### Steps to reproduce
Be a synthetic crew member
Open emergency supply box

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by xnqm8h** [comment]
As of revision `B:4971-suspension-field-sprite-missing D:2022-09-21` the backup battery in the synthetic supply box has a sprite. Recommending this issue be closed. @Darlantanis @Razgriz1032 

![image](https://user-images.githubusercontent.com/91218429/191621030-a6687dfb-4e0c-43a9-b51b-ce5512052387.png)
