### ISSUE TITLE
Grills can not be moved or deconstructed.

### ISSUE THREAD

**Issue by VictorZisthus** [CHOMPStation2/CHOMPStation2#4172]
#### Brief description of the issue
Grills cannot be moved or deconstructed after being placed.

#### What you expected to happen
It to be wrenchable, at the very least. SHOULD be able to be deconstructed.

#### What actually happened
Greytide gimmikman's worst nightmare. A machine that won't budge.

#### Steps to reproduce
- (Step 1) Find any Grill.
- (Step 2) Try to move it.
- (Step 3) Lie down.
- (Step 4) Try not to cry.
- (Step 5) Cry a lot.

#### Code Revision
- TGS version: 4.15.7
- DMAPI version: 5.3.0

**Comment by xnqm8h** [comment]
I'd recommend reopening this issue.

**Comment by VictorZisthus** [comment]
> I'd recommend reopening this issue.

Still broken?
