### ISSUE TITLE
Translator Earpiece translates while sleeping

### ISSUE THREAD

**Issue by xnqm8h** [CHOMPStation2/CHOMPStation2#4177]
#### Brief description of the issue
What people are saying around you while sleeping is still translated to the chat.

#### What you expected to happen
> ...You almost hear someone talking... 

#### What actually happened
> ...You almost hear someone talking... 
> The translator earpiece translates, "Internal bleeders. "

**Comment by VictorZisthus** [comment]
That's a robust piece of translation equipment if it's able to translate audio waves straight to brain waves!

I think it might be worth documenting this bug for future medical tech. Something that allows medical to talk to someone in a coma. That would he neat!

**Comment by xnqm8h** [comment]
I can already see the lovely addition of playing elevator music through that medical tech to a patient who's going through surgery.
