### ISSUE TITLE
Better handling for communicator calls between entities that share a tile

### ISSUE THREAD

**Issue by xnqm8h** [CHOMPStation2/CHOMPStation2#4198]
Those made between a predator and a prey can be annoying to play about as it will repeat the post multiple times. One post that is the original and then once more for each communicator in ear shot. If there was a check to see if one entity was inside the other and then drop the repeat posts that would be helpful.

![image](https://user-images.githubusercontent.com/91218429/166614504-4629f7ef-010a-4f06-b496-69ccbc839867.png)

**Comment by VictorZisthus** [comment]
Is there a way to mute one side of the call? Could do that until we get a more technical fix.

**Comment by xnqm8h** [comment]
If there was a mute option for calls that would probably work.
