### ISSUE TITLE
Hostile mobs can attack from inside of bellies (this issue seems to exist on virgo)

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#42]
If you eat an aggressive mob, it will continue to attack from inside of you.

Ideally this should be removed or players should be able to attack mobs (specifically mobs, not carbons and ideally not player-controlled mobs) from the inside.

**Comment by ExabyteDiscord** [comment]
This was fixed at some point, tested with carp.
