### ISSUE TITLE
Mining Drill Battery Shortage (Low Priority)

### ISSUE THREAD

**Issue by Draycu** [CHOMPStation2/CHOMPStation2#421]
#### Brief overview of the feature
With mining drills now starting the round without batteries installed, there are only two available in the map area for three total drills.  I wanted to make a hopefully quick and easy change request to the map to include at least three batteries, so all three drills can be used for more resource output.

#### What you want to happen  
Just for at least one more standard high cap battery to be added to the table, a quick map edit.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
Mining drills at the mining tunnel entrance with only two batteries:
![image](https://user-images.githubusercontent.com/28820640/88253424-899a8080-cc77-11ea-8aa9-ca856f413c7c.png)

**Comment by Kazzc** [comment]
Alright, I can fix this myself. Will do a map-edit on this regard.
Will add 2 additional high-capacity batteries to make up for the ones that are currently missing from within the drills.

Fairly I think a total of 6 batteries should suffice but for now we will stick with 4 on total.
