### ISSUE TITLE
Add way to track shuttle locations

### ISSUE THREAD

**Issue by Razgriz1032** [CHOMPStation2/CHOMPStation2#426]
With the removal of shuttle announcements, we should devise a way to track the location and status of shuttles.

My suggestion is a public terminal that just tells you where it is and maybe how long it's gonna take before it departs from its current location.

**Comment by Kazzc** [comment]
My only vague guess is to use the same system that it's used on Cargo.

Or use its current system but instead of outputting a msg just outpost the msg to a screen on the docks?. :V

**Comment by Kazzc** [comment]
This has been fixed with Nadiers PR that I helped fixed the issue.
