### ISSUE TITLE
Vore bump is only partially functional (Virgo issue)

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#43]
#### Brief description of the issue
In most cases, vore bump does not function properly. Activating vore bump and switching places with the mob (as happens most of the time in help intent) prevents the mob from eating the player. Pushing the mob against a wall in any other intent will allow vore bumps to work as long as the mob doesn't move before eating the player.

#### What you expected to happen
Mobs to eat you when vore bump activates.

#### What actually happened
Mob procs the vore bump message but doesn't actually eat you.

**Comment by Darlantanis** [comment]
Vore bump works now but still isn't quite as functional as before. Going to leave open as a reminder if I ever feel like working on mob vore code.

**Comment by ExabyteDiscord** [comment]
Seems to work now, mobs will enter a different intent when vorebump occurs so you don't push them away.
