### ISSUE TITLE
Advanced SMGs, Somatatrays and phoron pistols are missing sprites

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#4311]
#### Brief description of the issue
Advanced SMGs and Somatatrays printed via protolathe are missing sprites (may be more)

#### What you expected to happen
I get gun that I can see

#### What actually happened
I don't see gun I get. Reloading the guns with a mag via the turf examine ALT click fixes the sprite.

#### Steps to reproduce
- (Step 1) Spawn the gun in via printer or adminspawn
- (Step 2) Remove the magazine/battery (if applicable)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
- Server revision: B:-Using TGS- D:-Using TGS-
Commit: [52e04e52326259eec2a8929c5f6ac16d98c22243](http://127.0.0.1:51520/tmp7928/%3Ca%20href=%22https://github.com/CHOMPStation2/CHOMPStation2/commit/52e04e52326259eec2a8929c5f6ac16d98c22243%22%3Ehttps://github.com/CHOMPStation2/CHOMPStation2/commit/52e04e52326259eec2a8929c5f6ac16d98c22243%3C/a%3E)
TGS version: 4.15.7
DMAPI version: 5.3.0
The following pull requests are currently test merged:
[https://github.com/CHOMPStation2/CHOMPStation2/pull/4176](http://127.0.0.1:51520/tmp7928/%3Ca%20href=)">#4176: 'Protean rework part 2 (WIP)' by BlackMajor at commit 5ece102a02
 
#### Anything else you may wish to add:
https://i.imgur.com/T1AuEKz.png

**Comment by xnqm8h** [comment]
There is already an open issue for floral somatoray open. See #4151

Perhaps this should exclude the somatoray or they should be merged.
