### ISSUE TITLE
Geneticist PDA is missing its icon

### ISSUE THREAD

**Issue by Cyrelius** [CHOMPStation2/CHOMPStation2#444]
#### Brief description of the issue
as title.  The PDA lacks an icon regardless of if it's held or otherwise.

#### What you expected to happen
It to have an icon.

#### What actually happened
It doesn't have one.

#### Steps to reproduce
- (Step 1)  Spawn in as a geneticist.
- (Step 2)  Note that PDA is missing (though it's actually in one of your pockets.)

#### Code Revision
Server revision: B: D:2020-08-04
Commit: ba0c0f11e8faf5718e387eac0f7a8f62d6fd05e9 

#### Anything else you may wish to add:

![image](https://user-images.githubusercontent.com/69184203/89256346-c13eec00-d5d8-11ea-9c26-587d31c47a14.png)

**Comment by cadyn** [comment]
I believe this is patched by now.

**Comment by ExabyteDiscord** [comment]
patched.
