### ISSUE TITLE
[GENERAL]  - Spiders making right click bombs

### ISSUE THREAD

**Issue by Tsybal** [CHOMPStation2/CHOMPStation2#4446]
Brief description of the bug
Noticed that on one of the POI's, a giant spider has encountered another giant spider and is trying to web it in a cocoon, the cocoon is generated each try but the spider doesn't go into the cocoon, resulting in a loop that generates an inordinate amount of cocoons all in a single tile that lags / crashes the client if you dare right click on it.

What you expected to happen
The spider should go into the cocoon, meaning there's nothing for the spider to try to cocoon afterwards.

What actually happened
The spider is spinning cocoons forever, resulting in hundreds, if not thousands of cocoons if left unchecked.

Steps to reproduce
Not sure about reproducing, just spotted this in the wilds, will test to see what a giant spider does with a dead giant spider to see if this always affects it or what.

 Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: [e2227297a5060c653abf6901c838c5f9c43cb01d](http://127.0.0.1:64010/tmp10512/%3Ca%20href=%22https://github.com/CHOMPStation2/CHOMPStation2/commit/e2227297a5060c653abf6901c838c5f9c43cb01d%22%3Ehttps://github.com/CHOMPStation2/CHOMPStation2/commit/e2227297a5060c653abf6901c838c5f9c43cb01d%3C/a%3E)
TGS version: 4.15.7
DMAPI version: 5.3.0
The following pull requests are currently test merged:
[https://github.com/CHOMPStation2/CHOMPStation2/pull/4176](http://127.0.0.1:64010/tmp10512/%3Ca%20href=)">#4176: 'Protean rework part 2 (WIP)' by BlackMajor at commit d74d15fa72
 
![Spooder infinite cocoons](https://user-images.githubusercontent.com/88085232/176475352-b78a0e34-b932-4df0-8bb5-f2a1066f0c39.jpg)

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Tsybal** [comment]
Note that this also seems to happen with one of the crushed life-shuttle poi
![infinite cocoons](https://user-images.githubusercontent.com/88085232/180625530-08dcbb62-359e-42d7-a0da-a227d5e5726b.jpg)
s

**Comment by VictorZisthus** [comment]
![image](https://user-images.githubusercontent.com/56660717/180905928-9ef4a294-4e92-465b-9ad5-7f0cb5d77aa0.png)
Pain.
