### ISSUE TITLE
Updating the Drone Fabricators used on map

### ISSUE THREAD

**Issue by Sharkmare** [CHOMPStation2/CHOMPStation2#445]
#### Brief overview of the feature
Replacing the old Drone Fabricators with the unify Variants.
/obj/machinery/drone_fabricator/unify
#### What you want to happen
Replacing the old Drone Fabricators with the unify Variants.
/obj/machinery/drone_fabricator/unify

**Comment by Kazzc** [comment]
elaborate?

**Comment by Sharkmare** [comment]
> elaborate?

The map currently has regular drone fabricators instead of the unify drone fabricators.

The difference being that the unify fabricators use a system that allows you to select a drone type from a list of types, either the default set in the drone unify file or a hard coded selection that can be set when adding it to the map.

The file handling this fabricator is drone_manufacturer_unify.dm

**Comment by Kazzc** [comment]
Sound like a mapping issue, I can easily fix this.

**Comment by Kazzc** [comment]
I don't think we have those drone fabricators.
![image](https://user-images.githubusercontent.com/48134871/90070944-b8c66f80-dcc2-11ea-854f-63c5d7f69c10.png)
Unless we have it in the code I can't place them.

**Comment by Sharkmare** [comment]
> I don't think we have those drone fabricators.
> ![image](https://user-images.githubusercontent.com/48134871/90070944-b8c66f80-dcc2-11ea-854f-63c5d7f69c10.png)
> Unless we have it in the code I can't place them.

Looked at the DME for why this is the case and as I suspected it's simply not turned on, you have to enable the unify file i mentioned above otherwise you won't see unify fabricator.

**Comment by Shadow-Quill** [comment]
Filepath for unify drones is:
`code\modules\mob\living\silicon\robot\drone\drone_manufacturer_unify.dm`
File **is** unticked.

**Comment by Kazzc** [comment]
Oh, This should be easy fix then. I will make a PR then.

**Comment by Kazzc** [comment]
this is solved.

**Comment by Darlantanis** [comment]
This is not solved.
