### ISSUE TITLE
Teshari Base Custom Species Eyes are Mispositioned.

### ISSUE THREAD

**Issue by Renthur** [CHOMPStation2/CHOMPStation2#447]
#### Brief description of the issue
The eye pixels of Custom Species using the Teshari base remain in the same spot they would be for humans, rather than moving down to Tesh eye position.

#### What you expected to happen
Eyes to be on the tesh face, instead of just a floating pixel.

#### What actually happened
The eye remains as a pixel, floating in place over the teshari's head.

#### Steps to reproduce
- Create custom species character
- Set base icon to Teshari
- 

#### Code Revision
- B: D:2020-08-05
 
#### Anything else you may wish to add:
- Will attach screenshot of preview screen and ghost sprite with eye pixel floating. The actual yellow eyes on the face are due to using the 'Teshari Large Eyes' marking and are visibly not the eye color. Colors were changed slightly in character preview for visibility.
![TeshIssue](https://user-images.githubusercontent.com/20745732/89371476-bc456f80-d6a0-11ea-923a-debc0244898f.jpg)

**Comment by ExabyteDiscord** [comment]
This has since been fixed.
