### ISSUE TITLE
[UI] Midround popups appear blank

### ISSUE THREAD

**Issue by Lonewolf23319** [CHOMPStation2/CHOMPStation2#4477]
#### Brief description of the bug
Midround popups  (ie ghost pod spawn asks) appear blank

#### What you expected to happen
there to be text and maybe buttons on popup

#### What actually happened
it be blank

#### Steps to reproduce
- (Step 1) Be ghost
- (Step 2) Get midround popup for goo (or anything else that prompts a popup
- (Step 3) Cry because it is blank and you have to spend three more seconds to spawn in as thing.

**Comment by VictorZisthus** [comment]
This still happening? It seems to have been fixed as far as I can tell.
