### ISSUE TITLE
EVA lacks CO2 for jetpack refill, GPSes

### ISSUE THREAD

**Issue by KotetsuRedwood** [CHOMPStation2/CHOMPStation2#448]
#### Brief description of the issue
The EVA department is lacking CO2 gas to refill the jeptacks as well as GPSes to allow space co-ordination.

#### What you expected to happen
I expected to have non-important gas to fill up a jetpack to max and GPSes to help make my location known

#### What actually happened
There's no CO2 canister or GPSes, so I had to go outside with a non-full tank in my jetpack.

#### Steps to reproduce
- Go to EVA
- Look for CO2 gas for jetpack
-Fail to find CO2 canister

#### Code Revision
Server revision: B: D:2020-08-05
Commit: 73b0da99cd2e0842e0988f6f41e6a46160213b67 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by KotetsuRedwood** [comment]
I would map this in myself, but it sounds like Nadyr's working on the map and I'm not sure they're using mapmerge, so I'm waiting until they're done and merged

**Comment by Kazzc** [comment]
This should be easy to fix, I will keep note and edit it accordingly
