### ISSUE TITLE
No more space inertia

### ISSUE THREAD

**Issue by Dinnel** [CHOMPStation2/CHOMPStation2#457]
#### Brief description of the issue
When you move in space, you float one tile into the void and go still. Throwing objects will move you one tile but that's it. It used to not be like this, did something change the last few updates?

#### What you expected to happen
Float off into the abyss.

#### What actually happened
Float 1 foot away from the station and be stuck in space.

#### Steps to reproduce
- Step away from station in space
- Fail to go anywhere
- Noticing throwing an object only helps you move an additional 1 tile rather than help you float back or away.

#### Code Revision
- Server revision: B: D:2020-08-08
- Commit: 83630d8eaa1308202fa18dec2d7dbe2d5332bf4b
 
#### Anything else you may wish to add:
- This has gone a lot longer, probably for a week or two without being reported.

**Comment by Kazzc** [comment]
This has been fixed.
