### ISSUE TITLE
"Old" borgs missing.

### ISSUE THREAD

**Issue by Suhayll** [CHOMPStation2/CHOMPStation2#46]
Old borgs from the old station are now missing.

•Recently added **service borgs** and **booze borgs** are gone.
•V-3 Sprites for security and medical doggo borgs are missing.
•Medical borgs missing Medical grabber from their loadout. Required to work with phoron and use beakers outside internal beaker.

I'd add them myself but I haven't done this in a long time and im worried i might delete something important.

**Comment by Razgriz1032** [comment]
Check 'widerobot_ch' for sprites.

**Comment by Razgriz1032** [comment]
Boozeborg has been ported.

**Comment by JesusChristItsJasonBourne** [comment]
tested on live server, to test - create a human character and assign them the borg job role, spawn in and click the panel button to select a role (choose dog named/related roles, not department names)
you can only select one department per spawn, and get about 9 or so chances to pick a sprite. 

- all Service borgs as far as accounted for are available and visible
- all Boozeborgs were available but were invisible, after selecting more than 9 sprites and using your last chance to change sprites, it resets to 9 chances and all boozeborgs become visible
- V3 medihounds are not even a selection, one of the vale sprites for medihounds in the DMI is not being used and is likely what's missing
- V3's in the K9 category (security dog borgs) are missing entirely, and the secvale sprites are unused while the secborg sprites are the V2's

**Comment by JesusChristItsJasonBourne** [comment]
new PR made
V-3 medihounds, V-3 K9's (aka vale's sprites) are now added and functional
medical grabber now functional

remaining issue: YW's semi-functional boozeborg ports
