### ISSUE TITLE
Aurora Cooking Sucks Absolute Ass (In it's current state)

### ISSUE THREAD

**Issue by Somememeguy** [CHOMPStation2/CHOMPStation2#460]
#### Brief description of the issue

Title. Aurora cooking, while being a good concept, currently sucks ASS. 
#### What you expected to happen

Turn on fryer, heat up in like, 5-10 minutes.
Leave oven door open for a tiny bit, heat doesn't escape that fast
Put 10 lemons and 10 limes inside of a candy maker, get a decently sized lollipop or other candy.
Hell, do that in the cereal maker too, or the oven as well.
#### What actually happened
Fryer takes half an hour to heat up.
Leaving the oven door open for more then 10 seconds makes it drop by like, 50 Celsius.
You always get a tiny item from the candy maker.
Same goes for cereal maker or oven as well (when it's on bread/pizza/etc mode).
Many other issues. Will list in 'Anything else you may wish to add'.

#### Steps to reproduce
Fryer: Turn on the fryer.
Oven: Leave the oven door open for 30 seconds.
Candy Maker: Put 10 lemons and 10 limes inside of a candy maker
Oven/Cereal maker: Repeat candy maker.
Other issues: Too many to say.

#### Code Revision
Server revision: B: D:2020-08-09
 
#### Anything else you may wish to add:
Aurora cooking has so much potential behind it, but I feel like it's just. So. S L O W. Mass cooking is nice, when it WORKS. Sometimes it doesn't even work! And when going to the aurora's wiki, it says that food items will absorb leftover reagents after everything it cooks. But that doesn't actually happen when you cook something in the oven, or in the fryer- though I wonder if that could even work due to how multi-cooking works. I just feel like there's major issues with the port atm. Sure it's nice, but it doesn't seem to fully work.

**Comment by Rykka-Stormheart** [comment]
The item size is related to the size bit, iirc. The code is essentially the same as it is on Aurora minus tweaks to make it compatible with us, and there's more fixes coming in from upstrea,.

Fryer should not be taking a half hour, I tested the new times manually and it should be in around 8 minutes. I'll check, but if the resistance changes are in that shouldn't be the case?

**Comment by Rykka-Stormheart** [comment]
Checked, resistance is correct for fryer and it should take ~around~ 10 minutes to reach optimal temperature, as it's got a 2 KW advantage over the resistance.

**Comment by Rykka-Stormheart** [comment]
`Now grill heats in at 6:50, fryer at 10:35, and oven at 12:10 to reach peak/cap temperatures!`

**Comment by Rykka-Stormheart** [comment]
Also, if you're leaving the oven door open for 30 seconds, that's... not intended at all, you're supposed to open it, pull the item out, and close it. The wiki specifically states to do so to keep from losing heat.

**Comment by Somememeguy** [comment]
Okay but here's the thing.
We're in the year 2564.
Why does it have to take forever to cook food.
Why should fryers take over 10 minutes to reach it's cap temp.
Why should ovens immediately lose it's heat within 15 seconds.
What year are these kitchen appliances from, 2000?

**Comment by Poojawa** [comment]
> We're in the year 2564
> why does it take forever to cook food

Because you might as well just have a food replicator at this point. But you still want to cook? Part of cooking is doing prep work while stuff's coming to temp. Be it the oil in the pan, the oven, or anything else.

The oven losing temp that quickly is the only actual legit thing that could be changed, because ovens come back to heating up pretty quickly once warmed. it should be more forgiving about being opened.

**Comment by Somememeguy** [comment]
> Because you might as well just have a food replicator at this point. But you still want to cook? Part of cooking is doing prep work while stuff's coming to temp. Be it the oil in the pan, the oven, or anything else.

I just want to cook man, I don't care about having to deal with prepping shit. I come here to have fun not wait ages for stuff to pre-heat, and then have to worry about a power surge happening and whoops, time to re-heat everything!

This isn't real life, we're years in the future- why should it take ages to heat up stuff.

Also there's still the issue of the candy maker, etc, but at least there's more fixes. Also currently, at tiny size, it doesn't even have a nutrient value in it. Eating a tiny candy just says 'whoops none left'.
