### ISSUE TITLE
Work Gloves for Removing Lights

### ISSUE THREAD

**Issue by xnqm8h** [CHOMPStation2/CHOMPStation2#4620]
#### Brief overview of the feature
Work gloves should be able to let you remove a hot light bulb just like black gloves and similar. They're work gloves. Imagine not being able to work with them. :P

#### What you want to happen
Unscrew a light bulb when wearing a work gloves instead of "Owwie too hot."

**Comment by CMDRYouth** [comment]
Did you know:  Evening Gloves, IE those from the loadout, can also remove hot light bulbs.
