### ISSUE TITLE
Shadekin Bugs

### ISSUE THREAD

**Issue by KodaSoda** [CHOMPStation2/CHOMPStation2#464]
When playing as a shadekin, they seem to have a massive box in which they can be clicked or interacted with. Almost 3 blocks wide. So it's difficult for them in interact with most other objects such as grabbing something(one) and such. 

Secondly, they don't have access to some emotes. Such as the *mar which plays the sound they make. 
 

The second part isn't as much of an issue as the first part, as it causes problems when trying to interact with the world and other players. Just hope to see it fixed soon.

**Comment by Razgriz1032** [comment]
Unable to replicate.

**Comment by Darlantanis** [comment]
Unable to replicate. This may be reopened if somebody can reliably replicate it.
