### ISSUE TITLE
Rolls of Gauze should disinfect.

### ISSUE THREAD

**Issue by xnqm8h** [CHOMPStation2/CHOMPStation2#4655]
https://github.com/CHOMPStation2/CHOMPStation2/blob/1abb07e90ab80b5c54eb087a6f8daabd93726655/code/game/objects/items/stacks/medical.dm#L212

They are made with spaceacillin. Why wouldn't they disinfect wounds? See here:https://github.com/CHOMPStation2/CHOMPStation2/blob/6ba98067860500cf666510f819d811feb22d0d27/code/modules/reagents/reagents/medicine.dm#L1285-L1296

and here:
https://github.com/CHOMPStation2/CHOMPStation2/blob/988d70f72916fe86a484190b7c1d449519d3fb1d/code/modules/reagents/reactions/distilling/distilling.dm#L96-L101

**Comment by CMDRYouth** [comment]
Sounds like someone forgot their disinfecting Ointment.
But it's a good point.  If it's made with Spaceacillin, maybe that's to sterilize the bandages prior to application.  Though, that might not necessarily disinfect a wound that's already deep.  It would only be treating the surface.  Ointment usually soaks into a wound deep enough, being liquid, to reach where a surface bandage might not.
