### ISSUE TITLE
[GENERAL] Invisible sprites

### ISSUE THREAD

**Issue by SarmentiCampbell** [CHOMPStation2/CHOMPStation2#4678]
#### Brief description of the bug
Several sprites are missing

#### What you expected to happen
For items or cyborgs to have their sprites

#### What actually happened
Straight up invisible or Orange honk item happen

#### Which one
Literally a few of the cyborgs's non-dogborgs modules sprites are invisible and a example for clothes would be the tactical wetsuit and wetsuit

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by FoxglovePurpur** [comment]
I can't magically fix all s prites that I don't know about, but the ones you listed I can work on adding sprites for.
