### ISSUE TITLE
[GENERAL]  Vore panel belly fx busted

### ISSUE THREAD

**Issue by Echopsychotic** [CHOMPStation2/CHOMPStation2#4681]
#### Brief description of the bug
Belly FX/visuals for prey are no longer all able to be seen by myself because of an inability to scroll and even moving the screen out all the way doesn't show all the FX. 

#### What you expected to happen
To see all Belly visual fx via scroll wheel downward

#### What actually happened
opening up vore pannel and going to visuals to see the new belly PR that was added, I then saw the inability to see the other belly FX

#### Steps to reproduce
- Open vore pannel
- go to visuals
- see that you cannot scroll down the visual fx for the prey belly visual stuff

#### Anything else you may wish to add:
-
![image](https://user-images.githubusercontent.com/58645053/184048826-e162c62c-d895-482d-abdb-fb82e979a4ee.png)

**Comment by TheGreatKitsune** [comment]
Yup, working on fixing this now.
