### ISSUE TITLE
Internet Doesn't Reach the Whole Station.

### ISSUE THREAD

**Issue by YellowCloak** [CHOMPStation2/CHOMPStation2#470]
#### Brief description of the issue
Previously, the internet abilities of the station, spread using the exonet nodes I believe, would be reachable anywhere on the station. Now, you only get connection to the network on the first floor.

#### What you expected to happen
I expected to open my laptop in engineering and download all the apps to it that were afforded me by my job while I turned on the engine.

#### What actually happened
I opened the laptop and found it useless as I can't access the network to download such apps. I instead had to take it to the first floor to download everything.

#### Steps to reproduce
- (Step 1) Get an exonet applicable device.
- (Step 2) Try to access the download service on the device, on any floor BUT the first, be it a tablet or a laptop. 
- (and so on) Recieve a message saying you can't connect to the network to use the feature.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cyrelius** [comment]
The same issue applies to medical suit sensor monitoring.  It only works on the z level you're currently on, assuming it works at all.  Only the NIF version can connect.  Even consoles like atmospherics control only work on things on the same Z level as them.

**Comment by Cyrelius** [comment]
This I believe has also largely broken the functionality of the AI as well.  They can't interface with things they should be able to.

**Comment by YellowCloak** [comment]
This issue also extends to being unable to utilize the NiF network to talk with people anywhere in space or on Sif.
