### ISSUE TITLE
EVA hardsuit ordered from cargo is missing.

### ISSUE THREAD

**Issue by Cyrelius** [CHOMPStation2/CHOMPStation2#475]
#### Brief description of the issue
Ordered EVA hardsuit from cargo.
Container arrives, but is empty.

#### What you expected to happen
Would expect that container would actually contain hardsuit as ordered.

#### What actually happened
Contents field got nullified for some reason.

#### Steps to reproduce
- (Step 1) Order EVA hardsuit from cargo.
- (Step 2) Check crate delivered, it's not there.
- (and so on)

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 3cf28401bedb16ec4e62a82761c8db908f75670d
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0 

#### Anything else you may wish to add:
https://discordapp.com/channels/180538463655821312/405257702663782400/742919851776933960

**Comment by Razgriz1032** [comment]
[2020-08-11T18:06:29] Runtime in supply.dm,208: Cannot execute null.Cut().
   proc name: buy (/datum/controller/subsystem/supply/proc/buy)
   src: Supply (/datum/controller/subsystem/supply)
   call stack:
   Supply (/datum/controller/subsystem/supply): buy()
   Supply (/datum/shuttle/autodock/ferry/supply/cargo): short jump(Station (/obj/effect/shuttle_landmark/southern_cross/supply_station))

**Comment by Darlantanis** [comment]
Fixed by #513
