### ISSUE TITLE
NERF BRAZIL

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#478]
help
![image](https://user-images.githubusercontent.com/41974248/89977250-aacc0c80-dc38-11ea-8e26-bba3fb91fecb.png)
help
![image](https://user-images.githubusercontent.com/41974248/89977260-b0295700-dc38-11ea-9f3e-1b8d8a7cd12a.png)
help
![image](https://user-images.githubusercontent.com/41974248/89977269-b91a2880-dc38-11ea-8972-86206ca41878.png)
help
help 
help
help

**Comment by Darlantanis** [comment]
;help maint

**Comment by Darlantanis** [comment]
maint help

**Comment by SplinterGP** [comment]
why blame me :c
