### ISSUE TITLE
Responsive Filter does not work on all flashes.

### ISSUE THREAD

**Issue by Renthur** [CHOMPStation2/CHOMPStation2#487]
#### Brief description of the issue
NIF Responsive Filter module does not work against floor-mounted flashes.

#### What you expected to happen
Assuming it was meant to work like glasses, and considering it doesn't mention it would not work on floor mounted flashes, that it would block them like it does standard flashes.

#### What actually happened
Floor flashes stunned with Responsive Filter active.

#### Steps to reproduce
- Acquire NIF
- Acquire Responsive Filter for it
- Activate a floor-mounted flash.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 5ca559ff7224a10c1736d45d334cdbaa0ab510d3
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0
The following pull requests are currently test merged:
https://github.com/CHOMPStation2/CHOMPStation2/pull/474">#474: 'Adding bluespace to our universe.' by Kazzc at commit 0d9022a678
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Darlantanis** [comment]
Fixed by #513
