### ISSUE TITLE
Engineering Cyborg Cannot Remove Lead Wall Plating

### ISSUE THREAD

**Issue by crabcube** [CHOMPStation2/CHOMPStation2#4913]
#### Brief description of the bug
Engineering Cyborg Cannot peel plating off of lead walls. It just pushes on them with lit torch and plasma cutter.

#### What you expected to happen
What is expected to happen is the loading bar to appear and the plating of the wall to be cut off.

#### What actually happened
Approach a lead wall with your cutting tool of choice. Ignite the tool if applicable. Click on the wall. You will push the wall if it is lead, and cut if it is steel.

#### Steps to reproduce
- (Step 1) Arrive on station as engineering cyborg
- (Step 2) build a lead wall 
- (step 3) try and unbuild the wall

**Comment by xnqm8h** [comment]
Can you detail the steps you took? Did you create a normal lead wall?

I was able to use the `steel synthesizer` to create a girder. Then I added lead to finish the wall.

To dismantle I used the `mounted plasma cutter` and was able to dismantle the lead wall without issue.

I also tried dismantling the lead wall with the `electric welding tool` and that succeeded as well.
