### ISSUE TITLE
Field Medic outfits

### ISSUE THREAD

**Issue by Chargae** [CHOMPStation2/CHOMPStation2#4976]
#### Brief overview of the feature
Field medics spawn in with a generic jumpsuit. Considering they're _essentially_ Paramedic But Outside, would be nice if they could have similar loadout options for looking the part.

#### What you want to happen
Field medics to have access to Paramedic loadout options for uniforms, or at the very least a starting uniform that isn't a generic utility suit. Alternatively, Paramedic alt uniforms to be added to the map, as they don't exist outside of loadout options.

**Comment by xnqm8h** [comment]
There is actually a field medic utility suit that could be utilized here: `/item/clothing/under/explorer/utility/medical`.

Another interesting piece of clothing might be '/item/clothing/suit/storage/hooded/explorer/medic` as it's an explorer hooded chest piece with a medic band attached to it.

Maybe these could be used to make a new field medic locker if there isn't one available.

**Comment by VictorZisthus** [comment]
I could probably tackle this one! I'll put it on my to-do.
