### ISSUE TITLE
Borg breaks tool with planters

### ISSUE THREAD

**Issue by T-E-R-A** [CHOMPStation2/CHOMPStation2#501]
#### Steps to reproduce
- (Step 1): Go up to a planter
- (Step 2): Put a module in the planter
- (Step 3): Have someone take the module out of the planter
- (Step 4): Try to use or do anything with module.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: d43f1fd9a80e0f582ef477b618225331523e1049
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0 
 
#### Anything else you may wish to add:
- GIF: https://gyazo.com/db47ee82b14084b43db98aa3ca6a4bea

**Comment by Darlantanis** [comment]
Fixed by #513
