### ISSUE TITLE
Mining is broken due to https://github.com/CHOMPStation2/CHOMPStation2/pull/5042

### ISSUE THREAD

**Issue by Cyrelius** [CHOMPStation2/CHOMPStation2#5055]
#### Brief description of the bug
Mining is broken due to the 'mining adjustments' in this: https://github.com/CHOMPStation2/CHOMPStation2/pull/5042

#### What you expected to happen
A normal amount of ore to be given by the big drills.

#### What actually happened
Some ores are flatly missing, Hematite, platinum, and mhydrogen to name a few.

#### Steps to reproduce
- (Step 1)  Set up Big drill where there's supposedly exotic matter.
- (Step 2)  unload big drill, get nothing that would be considered exotic besides pure phoron.
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Cameron653** [comment]
Fixed upstream. https://github.com/VOREStation/VOREStation/pull/13827/files

**Comment by Raeschen** [comment]
Fixed by this: #5069

**Comment by VictorZisthus** [comment]
This should be closed if it is no longer a problem.
