### ISSUE TITLE
TGUI ahelp ticket system lacks actions (resolve, close, handle, etc)

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#5190]
New(ish) TGUI adminhelp ticket system lacks actions for tickets (resolve, close, handle, etc.), the actions section remaining blank rather than offering actions. Non-critical as the old UI works as intended.
![image](https://user-images.githubusercontent.com/41974248/198516551-dbfdde48-d6d8-4e69-a140-ae1c0d4650f0.png)

#### Code Revision
147769dc37428ac8371d0b63167465b58cd63705

**Comment by Verkister** [comment]
Seems the proc just before the lines that add these buttons is runtiming here so it fails to add the closure links https://github.com/CHOMPStation2/CHOMPStation2/blob/master/code/modules/admin/verbs/adminhelp.dm#L242
