### ISSUE TITLE
Autolathes are dumb

### ISSUE THREAD

**Issue by Admiralkosmov** [CHOMPStation2/CHOMPStation2#531]
#### Brief description of the issue
Autolathes are janky as hell.

#### What you expected to happen
autolathe uses only metal and glass to produce things
#### What actually happened
autolathe has an invisible source of plasteel, plastic, ready-made autoinjectors that don't require any materials, platinium and, for some reason, waste(???)

#### Steps to reproduce
Go to any autolathe and inspect the materials required for production of items (for example, plastic pitcher, hatchet, empty autoinjector, infrared sensor)

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 6b112133d5bae75c48c8b354811ccf600ac99ec4
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0 
 
#### Anything else you may wish to add:
Also, matter cartridges are fucking expensive. I mean, come the hell on, 625000 steel? Really? Really now. Also, deconstructing a wall uses 15 of matter units. Yes, you read that correctly, DECONSTRUCTING walls USES MATTER. You are literally evaporating 20 sheets of steel with a click of a button, plus 4 sheets of steel that went into making the wall you are trying to erase! Who the heck thought THAT would be a good idea?

**Comment by DerBlitzkrieg** [comment]
Just make all the items use steel and glass in my opinion. Having to shove another 3 (4??) materials in the autolathe to make a very limited amount of items would be quite bothersome.

**Comment by Shadow-Quill** [comment]
Matter carts are expensive because haha RCD goes brr
