### ISSUE TITLE
Fire Assist Mainframe Circuit Board Unable To Be Printed

### ISSUE THREAD

**Issue by LuciusWorna** [CHOMPStation2/CHOMPStation2#537]
#### Brief description of the issue
In order to control Point Defense Batteries, they have to be linked to a Fire Assist Mainframe using a multitool. Currently, the circuit board for the Fire Assist Mainframe cannot be printed from the circuit printer, unlike the Point Defense Battery.

#### What you expected to happen
Fire Assist Mainframe circuit board to be available when the Point Defense Battery circuit board becomes available at the circuit printer.

#### What actually happened
Fire Assist Mainframe circuit board is not present in the list.

#### Steps to reproduce
Complete research up to requiring materials.
Point Defense Battery Circuit Board becomes available but not the controlling Fire Assist Mainframe circuit board.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 53733a06fcea711fcb0d9c989093b01fc8c32df8
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by cadyn** [comment]
Pretty sure this should be resolved by now
