### ISSUE TITLE
New airlocks not functioning

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#542]
Basically building airlocks in new areas result in the airlock being uninteractable and generating runtimes when powered. 

Runtimes (ckeys removed)
[2020-09-09T22:26:19] Runtime in airlock.dm,1137: Cannot execute null.is cut().
   proc name: can open (/obj/machinery/door/airlock/can_open)
   usr: Loni Nesumi (/mob/living/carbon/human) @ (the floor) (22,163,2) (/turf/simulated/floor/airless) (ckey=[REDACTED])
   usr.loc: (the floor) (22,163,2) (/turf/simulated/floor/airless)
   src: the External Airlock (/obj/machinery/door/airlock/external)
   src.loc: the floor (22,162,2) (/turf/simulated/floor/airless)
   call stack:
   the External Airlock (/obj/machinery/door/airlock/external): can open(0)
   the External Airlock (/obj/machinery/door/airlock/external): open(0)
   the External Airlock (/obj/machinery/door/airlock/external): open(null)
   the External Airlock (/obj/machinery/door/airlock/external): bumpopen(Loni Nesumi (/mob/living/carbon/human))
   the External Airlock (/obj/machinery/door/airlock/external): bumpopen(Loni Nesumi (/mob/living/carbon/human))
   the External Airlock (/obj/machinery/door/airlock/external): Bumped(Loni Nesumi (/mob/living/carbon/human))
   the External Airlock (/obj/machinery/door/airlock/external): Bumped(Loni Nesumi (/mob/living/carbon/human))
   Loni Nesumi (/mob/living/carbon/human): Bump(the External Airlock (/obj/machinery/door/airlock/external))
   Loni Nesumi (/mob/living/carbon/human): Bump(the External Airlock (/obj/machinery/door/airlock/external))
   Loni Nesumi (/mob/living/carbon/human): Bump(the External Airlock (/obj/machinery/door/airlock/external))
   Loni Nesumi (/mob/living/carbon/human): Bump(the External Airlock (/obj/machinery/door/airlock/external))
   the floor (22,162,2) (/turf/simulated/floor/airless): Enter(Loni Nesumi (/mob/living/carbon/human), the floor (22,163,2) (/turf/simulated/floor/airless))
   the floor (22,162,2) (/turf/simulated/floor/airless): Enter(Loni Nesumi (/mob/living/carbon/human), the floor (22,163,2) (/turf/simulated/floor/airless))
   Loni Nesumi (/mob/living/carbon/human): Move(the floor (22,162,2) (/turf/simulated/floor/airless), 2, 3)
   Loni Nesumi (/mob/living/carbon/human): Move(the floor (22,162,2) (/turf/simulated/floor/airless), 2, 3)
   Loni Nesumi (/mob/living/carbon/human): SelfMove(the floor (22,162,2) (/turf/simulated/floor/airless), 2, 3)
   Loni Nesumi (/mob/living/carbon/human): SelfMove(the floor (22,162,2) (/turf/simulated/floor/airless), 2, 3)
   [REDACTED] (/client): Move(the floor (22,162,2) (/turf/simulated/floor/airless), 2)
   [REDACTED] (/client): .movedown()

[2020-09-09T22:26:24] Runtime in airlock.dm,904: Cannot execute null.Interact().
   proc name: attack hand (/obj/machinery/door/airlock/attack_hand)
   usr: Loni Nesumi (/mob/living/carbon/human) @ (the floor) (23,163,2) (/turf/simulated/floor/airless) (ckey=[REDACTED])
   usr.loc: (the floor) (23,163,2) (/turf/simulated/floor/airless)
   src: the External Airlock (/obj/machinery/door/airlock/external)
   src.loc: the floor (22,162,2) (/turf/simulated/floor/airless)
   call stack:
   the External Airlock (/obj/machinery/door/airlock/external): attack hand(Loni Nesumi (/mob/living/carbon/human))
   the External Airlock (/obj/machinery/door/airlock/external): attackby(the multitool (/obj/item/device/multitool), Loni Nesumi (/mob/living/carbon/human), 1, "icon-x=30;icon-y=25;left=1;scr...")
   the multitool (/obj/item/device/multitool): resolve attackby(the External Airlock (/obj/machinery/door/airlock/external), Loni Nesumi (/mob/living/carbon/human), 1, "icon-x=30;icon-y=25;left=1;scr...")
   Loni Nesumi (/mob/living/carbon/human): ClickOn(the External Airlock (/obj/machinery/door/airlock/external), "icon-x=30;icon-y=25;left=1;scr...")
   the External Airlock (/obj/machinery/door/airlock/external): Click(the floor (22,162,2) (/turf/simulated/floor/airless), "mapwindow.map", "icon-x=30;icon-y=25;left=1;scr...")

**Comment by cadyn** [comment]
**scream**

**Comment by cadyn** [comment]
I'll look into tomorrow

**Comment by cadyn** [comment]
Fixed yeet
