### ISSUE TITLE
Pathfinder's invisable wristbound PDA

### ISSUE THREAD

**Issue by 123MrMango321** [CHOMPStation2/CHOMPStation2#554]
#### Brief description of the issue
When joining the game as a Pathfinder with the wristbound version of the PDA selected, you get an invisable PDA that borks up your pockets somehow.

#### What you expected to happen
To have a PDA and working pockets on spawn as Pathfinder when wrist bound PDA is selected

#### What actually happened
You get an invisible PDA that possesses your pockets, keeping you from putting anything in them until you strip and reclothe and get rid of the PDA. You must then find a new PDA

#### Steps to reproduce
- Join as Pathfinder with the wristbound PDA selected
- Look at your belt slot and see that it's been possessed by an unholy invisible entity that possesses your pockets as well

#### Code Revision
- Server revision: B:-Using TGS- D:-Using TGS-
Commit: 08f491fa1cde36f948a729bb9e7c6a9f4402947e
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by xnqm8h** [comment]
I just tested this on `Server revision: B:4971-suspension-field-sprite-missing D:2022-09-21` and spawning in as the pathfinder with a wrist-bound PDA does have a sprite now.

![image](https://user-images.githubusercontent.com/91218429/191616698-c70526c5-c4e5-441c-be12-a94a546ffdb1.png)

Suggesting that this issue gets closed. @123MrMango321 @Darlantanis @Razgriz1032
