### ISSUE TITLE
[GENERAL] Blindness in a wheelchair

### ISSUE THREAD

**Issue by xnqm8h** [CHOMPStation2/CHOMPStation2#5542]
#### Brief description of the bug
If someone is blind in a wheelchair and they are being pushed, going through an airlock damages them as it says they run into it instead of just opening the airlock normally.

#### What you expected to happen
For the airlock to open without issue.

#### What actually happened
**bonk** 💥

**Comment by CMDRYouth** [comment]
Switch to Walking Intent.
Running into walls/airlocks when blind is entirely dependent on movement intent.
