### ISSUE TITLE
[Vore Belly] Vore

### ISSUE THREAD

**Issue by xnqm8h** [CHOMPStation2/CHOMPStation2#5543]
#### Brief description of the bug
Vore belly sprites don't render on Diona.

#### What you expected to happen
Chonky plant

#### What actually happened
Sad flat plant

#### Steps to reproduce
- Eat
- Eat
- Eat
- Flat

**Comment by CMDRYouth** [comment]
You are a tree.  You are made of Wood.
If you are expanding, you are in danger of fracturing.
You are not made of soft, stretchy flesh.
