### ISSUE TITLE
[GENERAL] 

### ISSUE THREAD

**Issue by FluffMedic** [CHOMPStation2/CHOMPStation2#5584]
#### Brief description of the bug
With heat adapted, die, (then possibly enter ghost), your body will start freezing despite you having warm clothes, and active internals moments before, toasting them rather quickly.

#### What you expected to happen
For medical to retrieve the body with whatever injuries the character had when they died.

#### What actually happened
-> Died with 12 brute, and 150 resp damage.
-> When the retrieval team arrived, has 12 brute, 150 resp, and 300+ burn.

#### Steps to reproduce
- Chose Heat adapt
- Go exploring
- Die through some various means
-(Debatable) Enter ghost mode.
-Sit at a crew moniter and watch your burn rise.

**Comment by Demintika** [comment]
Also happens to Unathi when dying in the cold, even with warm clothes and internal.
