### ISSUE TITLE
[GENERAL] Pupdozer Cybrogs have redundant RPED's

### ISSUE THREAD

**Issue by RedFoxChatterBox** [CHOMPStation2/CHOMPStation2#5615]
#### Brief description of the bug
Pupdozer cyborgs have two RPED's in their inventory, both functional but rather redundant

#### What you expected to happen
There to be only one RPED!

#### What actually happened
There were two RPED's! (Sorry, there really isn't much more to it than this!)

#### Steps to reproduce
- Step 1, login as cyborg
- Step 2, set module to pupdozer
- Step 3, select any model
- Step 4, open inventory and observe redundant RPED's

**Comment by VictorZisthus** [comment]
**THERE ARE THREE NOW!**

![image](https://user-images.githubusercontent.com/56660717/216857128-e3bf6421-9d5b-43f1-acf3-9ede5765a2bd.png)

**Comment by FoxglovePurpur** [comment]
Sending a comment here while I try to code dive and fix things. I'd rather this issue not go stale as it's still, well, an issue.
