### ISSUE TITLE
[GENERAL]  Jetpacks not properly function in the suit slot

### ISSUE THREAD

**Issue by FluffMedic** [CHOMPStation2/CHOMPStation2#5640]
#### Brief description of the bug
You cannot fly with a jetpack while it is in the suit slot.

#### What you expected to happen
To be able to fly around with the jetpack in the suitslot.

#### What actually happened
You get the particle effect, except you just move in a straight line.

#### Steps to reproduce
- Put the jetpack in the suit slot.
- Fly into the void. Or hopefully not to avoid serb crashes.

**Comment by Seris02** [comment]
non-issue
you aren't supposed to be able to use it in the suit slot, only the backpack

**Comment by CMDRYouth** [comment]
Mhm.  You exchange inventory for space mobility.  That's how it's supposed to go.
You can also carry your bag in one hand.

**Comment by Rykka-Stormheart** [comment]
Slight issue with this - this means Protean RIGs will interfere unless they've had jetpack upgrades installed.
But, frankly, chalk it up to learning lesson and a requirement for your Protean to get upgraded prior. Same with your RIG.
