### ISSUE TITLE
[GENERAL] Halloss does not tick down while Prometheans are in blobform.

### ISSUE THREAD

**Issue by Rykka-Stormheart** [CHOMPStation2/CHOMPStation2#5643]
#### Brief description of the bug
As described. Halloss does not reduce when a promethean is in blobform, resulting in a perma-stunlocked prommie if they blob at the wrong time, somehow.

#### What you expected to happen
 Blob, not die.
#### Steps to reproduce
- Be in pain
- blob
- agony

**Comment by CMDRYouth** [comment]
Well stop trying to Gamer the combat mechanics with your species then, you dork.

**Comment by Rykka-Stormheart** [comment]
> Well stop trying to Gamer the combat mechanics with your species then, you dork.

I wasn't. This was a report made on someone else's behalf while I was dev and working on their broken form.

**Comment by VictorZisthus** [comment]
I'll look into this tonight and see if I can't find some kind of fix.
