### ISSUE TITLE
Colony director items not spawning with site manager/overseer.

### ISSUE THREAD

**Issue by Cyrelius** [CHOMPStation2/CHOMPStation2#565]
#### Brief description of the issue
Spawned as Overseer (site manager alternate title), got these messages with regards to loadout:

Your current species, job or whitelist status does not permit you to spawn with AR-B glasses (CD, HoP, BSG)! 
Your current species, job or whitelist status does not permit you to spawn with nullsuit, cmd! 

#### What you expected to happen
I used to be able to have both of those before the change of Colony director to Site manager/Overseer.  I expected to spawn with these items.  Tried the alternate title, site manager, no difference.

#### What actually happened
It doesn't believe i'm allowed to start with those items as the site manager/overseer.  

#### Steps to reproduce
- Pick item you should be able to start with in your loadout.
- spawn in as site manager/overseer, or appropriate for other jobs.
- notice that it doesn't let you have them.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 54da828983792ade47ff5e461797547251fff190
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0 
 
#### Anything else you may wish to add:
- There are probably a LOT of items like that that need fixing in the loadout.

**Comment by Cyrelius** [comment]
Site manager is also missing an AR symbol for their job.
![image](https://user-images.githubusercontent.com/69184203/94998701-b963df80-0568-11eb-86bd-722af769ce91.png)

**Comment by cadyn** [comment]
Should be fixed now.

**Comment by Shadow-Quill** [comment]
Is this confirmed to be fixed?
