### ISSUE TITLE
Medical Computer crash when opening any medical file.

### ISSUE THREAD

**Issue by r4d6** [CHOMPStation2/CHOMPStation2#583]
#### Brief description of the issue
I open the medical laptop available in the lobby, I try to open a medical file of a player, it does a blue screen.

#### What you expected to happen
To open the medical file

#### What actually happened
Crashed with a blue screen and an error message.

#### Steps to reproduce
- Open the medical laptop
- Try to open the file of a player
- Laptop Crash
 
#### Anything else you may wish to add:
![2020-10-14 10_52_56-](https://user-images.githubusercontent.com/50276533/96006421-77aa2300-0e0b-11eb-9062-ffbe467d3590.png)

**Comment by cadyn** [comment]
Should be fiiixed

**Comment by Shadow-Quill** [comment]
@cadyn Fixed?

**Comment by r4d6** [comment]
Fixed
