### ISSUE TITLE
[GENERAL] Nitrogen Breathers(also maybe Phoron) dying in under ten seconds from toxic shock.

### ISSUE THREAD

**Issue by Crystal9156** [CHOMPStation2/CHOMPStation2#5862]
Playing as a Nitrogen breather, if you need to switch tanks or have them off for a half a second, you immediately go into toxic shock even if you have your nitrogen tank back on, racking up 10+ toxin damage per tick until you succumb to it, with no med being able to help in time due to the amount of damage.

Switching tanks or breathing oxygen for a split second kills you with no chance for you to mitigate the effects. You go into immediate toxic shock and are unable to heal yourself/get healed in time to do anything about it.

Have a slight grace period where you gasp or hold your breath like an oxygen breather, or take less damage because almost instantly dying with no way for medical intervention to help is nuts.

#### Steps to reproduce
Choose Nitrogen Breather in char setup.
Spawn ingame.
Switch tanks or turn yours off for a single half second or second.
Begin taking hundreds of toxin damage in under five to ten seconds and die.
Be a drain on everyone else's time and resources and hope they don't forget to put your nitrogen tank back on otherwise they need to do the whole thing over again.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 71a2ad8d9cffbc6ea31c9944ccbb2b44db65043e 
TGS version: 4.15.7
DMAPI version: 5.3.0
The following pull requests are currently test merged:
#5706: 'Wilds Expansion - The Valley' by FluffMedic at commit 306acb4d19 
#5714: 'Energy Weapons Balance Pass.' by Cyrelius at commit d6f084007d 
#5772: 'Shadekin Hideout, Dark Tunneling, Shadekin death changes' by TheGreatKitsune at commit 3ad663e685 

 

#### Anything else you may wish to add:
If this /isn't/ changed at all and is intended, I recommend changing nitrogen breather up in points from -2 because this is 
low endurance tier, a -4 or -6 quirk because you die if you or anyone else touches your tank wrong and there's no safe places to do so. I know taking the trait is optional but I want to play my nitrogen breathing bug without having to be scared of ever changing/refilling/being stripped/etc by myself or someone else.

**Comment by VictorZisthus** [comment]
I'll look into this tonight. I'd say this is definitely not intended.

**Comment by VictorZisthus** [comment]
I've done some testing on the current state of the traits and determined that the toxins you take from breathing the bad are far from immediately lethal in the current build in the game. My test subject survived well over a minute in the standard airmix and only took 10 toxin damage in that time, with no organ damage. Not sure if this was stealth patched or what, but the issue does not seem to remain.

Phonon breather did get the worse end of the deal, taking massive oxy damage that resulted in death in about 1m 30s from brain damage, but toxins were still very low at 10.

If you have evidence to the contrary however, I'd be happy to test things out with ya 1 on 1 on live at anytime!
