### ISSUE TITLE
TTV Bombs not detonating properly

### ISSUE THREAD

**Issue by LuciusWorna** [CHOMPStation2/CHOMPStation2#587]
#### Brief description of the issue
TTV Bomb placed in the mines was detonated, resulting in a 1x1 radius instead of the normal 7x7. It seems like something is broken with explosions.

#### What you expected to happen
Big boom.

#### What actually happened
Tiny boom

#### Steps to reproduce
- Weld and fill phoron tank with 10,000 C phoron
- Weld and fill oxygen tank with 100 K oxygen
- Make TTV bomb using remote signaller
- Deploy bomb, detonate using PDA signaller

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 0942ad31ba560a8968f08a7bdbb9e5f944cc991b
TGS version: /tg/station 13 Server v3.2.6.2
DMAPI version: 3.2.1.0 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![1](https://user-images.githubusercontent.com/70927658/96075195-85e25880-0e78-11eb-8827-6c0b10214e10.png)
![2](https://user-images.githubusercontent.com/70927658/96075197-87138580-0e78-11eb-9228-1529ec8c68a3.png)

Contacted a moderator about the issue, they saw the detonations on their UI.
ADMIN LOG: Bomb valve opened in POI - Mine Vault with the remote signaling device attacher: Ronove Arder()(?) Last touched by: (?)
ADMIN LOG: Bomb valve opened in Depths with the remote signaling device attacher: Ronove Arder()(?) Last touched by: (?)
ADMIN LOG: Bomb valve opened in Depths with the remote signaling device attacher: Ronove Arder()(?) Last touched by: (?)
ADMIN LOG: Bomb valve opened in Tunnels with the remote signaling device attacher: Ronove Arder()(?) Last touched by: (?)
ADMIN LOG: Bomb valve opened in Depths with the remote signaling device attacher: Ronove Arder()(?) Last touched by: (?)
ADMIN LOG: Bomb valve opened in Depths with the remote signaling device attacher: Ronove Arder()(?) Last touched by: (?)
ADMIN LOG: Explosion with non-shaped size (0, 2, 5) in area POI - Mine Vault (151,25,5) (JMP)
ADMIN LOG: Explosion with size (7) in area POI - Mine Vault (151,25,5)
ADMIN LOG: Explosion with non-shaped size (0, 2, 5) in area Tunnels (160,63,5) (JMP)
ADMIN LOG: Explosion with size (7) in area Tunnels (160,63,5)
ADMIN LOG: Explosion with non-shaped size (0, 2, 5) in area Depths (14,115,5) (JMP)
ADMIN LOG: Explosion with size (7) in area Depths (14,115,5)
ADMIN LOG: Explosion with non-shaped size (0, 2, 5) in area Depths (21,169,5) (JMP)
ADMIN LOG: Explosion with size (7) in area Depths (21,169,5)
ADMIN LOG: Explosion with non-shaped size (0, 2, 5) in area Depths (31,116,5) (JMP)
ADMIN LOG: Explosion with size (7) in area Depths (31,116,5)
ADMIN LOG: Explosion with non-shaped size (0, 2, 5) in area Depths (24,106,5) (JMP)
ADMIN LOG: Explosion with size (7) in area Depths (24,106,5)

**Comment by cadyn** [comment]
Honestly find it more likely a step was mistaken here

**Comment by LuciusWorna** [comment]
Or you can read the admin logs. Size was 7, not 1.

**Comment by LuciusWorna** [comment]
It would seem that my procedure doesn't work anymore. It used to make large bombs but now they are pathetic. Something happened with balance and, if it is intended, TTV bombs aren't broken.
