### ISSUE TITLE
[GENERAL] Digitigrade legs cause issues with most uniforms

### ISSUE THREAD

**Issue by HatArchAzel** [CHOMPStation2/CHOMPStation2#5947]
#### Brief description of the bug
Characters marked as digitigrade seem to experience some sprite layering issues, particularly around the hands. Hands seem to be layered _under_ all other sprites beyond the torso, including worn bags and more importantly most clothes the character in question is wearing. This happens with most job uniforms as far as I can tell, but not all worn clothing.

#### What you expected to happen
Being able to see my character's hands from the sides when not wearing gloves as a digitigrade character.

#### What actually happened
The character's hands disappear under their uniform on the side views. When not wearing a uniform, the hands display completely properly, however, causing me to believe it's a bug with sprite layering.

#### Steps to reproduce
- Make any custom species character
- Mark them as digitigrade
- Show their job gear as most jobs with their own jumpsuit (tested with Exploration for example) or load into the game with job gear equipped

#### Anything else you may wish to add:
- Spriting issue. Seemingly a sprite layering issue?

**Comment by HatArchAzel** [comment]
Further testing shows that overwear such as the winter coats does _not_ also create this issue, which has me even more confused.

**Comment by HatArchAzel** [comment]
![image](https://user-images.githubusercontent.com/23587781/225163709-1cab319e-63ec-49e7-b10e-5d074c6d547f.png)
Example of what it looks like on plantigrade characters, where things work properly


<img width="133" alt="Screenshot 2023-03-14 144937" src="https://user-images.githubusercontent.com/23587781/225163842-d6b2e94e-14ac-4079-99fa-0bdb6108f634.png">
And example of what it looks like on digitigrade characters, using the basic human base to show it occurs regardless of sprite base/isn't a matter of the synthetic limbs specifically being weird or anything like that. Tested this with some other icon bases as well and got the same results there too

**Comment by Seris02** [comment]
this is just an issue with the sprites themselves, since the uniform renders above the body.

![image](https://user-images.githubusercontent.com/49109742/225177783-c2c40d9a-1aa3-4688-ab08-eac6caee729f.png)

![image](https://user-images.githubusercontent.com/49109742/225177803-b78f4137-f2b0-4aaf-b71c-eb622c15eed8.png)

the digi sprites have no space for hands

**Comment by FoxglovePurpur** [comment]
I do plan on going through eventually and added/fixing all digitigrade sprites.  Seeing as how this is mostly a spriting issue. 
Though, as you can imagine, it's going to take awhile.
