### ISSUE TITLE
Thrown Egg Runtime

### ISSUE THREAD

**Issue by LunarFleet** [CHOMPStation2/CHOMPStation2#603]
#### Brief description of the issue
Throwing an egg 'through' a window creates a runtime. Note, I tested this with normal eggs from the kitchen. 

#### What you expected to happen
The egg to splat in a normal manner

#### What actually happened
The egg splats normally, but the server console decides it has no mouth and must scream runtimes.

#### Steps to reproduce
- (Step 1)
Grab an egg, whether it be from the kitchen, spawning it in, etc
- (Step 2)
Set your intent to throw, click past a window. The egg will hit the window, the egg will splat accordingly, then spew runtimes in the log. 

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
3a772c37eefbed453ce68ae7cb9aa17e34c4cc95

**Comment by cadyn** [comment]
I have so many questions

**Comment by Darlantanis** [comment]
what are the runtimes

**Comment by LunarFleet** [comment]
Runtime in snacks.dm,884: Cannot read null.total_volume
