### ISSUE TITLE
Heads of staff cannot change alert levels

### ISSUE THREAD

**Issue by Darlantanis** [CHOMPStation2/CHOMPStation2#604]
Heads of staff can no longer change alert levels. While I have not extensively tested which heads of staff this applies to the text implies this is now limited to the Colony Director only.

This is probably intentional upstream but is not suitable for our server.

#### Code Revision
3a772c37eefbed453ce68ae7cb9aa17e34c4cc95

**Comment by Shadow-Quill** [comment]
This will be fixed when #707 is merged.

**Comment by Darlantanis** [comment]
Closed by #707
