### ISSUE TITLE
Compiling Error [GENERAL] 

### ISSUE THREAD

**Issue by griffbeeks** [CHOMPStation2/CHOMPStation2#6204]
#### Brief description of the bug
Coding error when trying to compile Sever. 

loading vorestation.dme
code\game\objects\structures\barricades.dm:153:error: expected ':'
vorestation.dmb - 1 error, 0 warnings (5/18/23 1:37 pm)

#### What you expected to happen
Sever should Compile properly to make the executable. 

#### What actually happened

Compiling threw the following error 

loading vorestation.dme
code\game\objects\structures\barricades.dm:153:error: expected ':'
vorestation.dmb - 1 error, 0 warnings (5/18/23 1:37 pm)

#### Steps to reproduce
Click Build on the compiler, then hit compile, throws the error every time.

 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Aroliacue** [comment]
I don't have this error on my branch. Have you made **any** edits to the files, specifically that file in particular? (code\game\objects\structures\barricades.dm)

**Comment by Razgriz1032** [comment]
Skill issue. You're compiling Chomp 1. Download chomp 2

**Comment by griffbeeks** [comment]
my byond was out of date

**Comment by Razgriz1032** [comment]
Oh, yeah that's the other problem if it's not working.
