### ISSUE TITLE
Reset Slot Pressing X on the dialog is seen as YES

### ISSUE THREAD

**Issue by kcin2001** [CHOMPStation2/CHOMPStation2#6248]
#### Brief description of the bug
when you hit reset slot and hit X on the dialog that comes up is a Yes instead of logically it should be a no

#### What you expected to happen
for it to stop the process

#### What actually happened
my character slot was deleted

#### Steps to reproduce
- click reset slot
- click X on the dialog

#### Code Revision
- [5f07c2a1521de36dfde16bfab27070c6bc9f91e5](http://127.0.0.1:53387/tmp27892/%3Ca%20href=%22https://github.com/CHOMPStation2/CHOMPStation2/commit/5f07c2a1521de36dfde16bfab27070c6bc9f91e5%22%3Ehttps://github.com/CHOMPStation2/CHOMPStation2/commit/5f07c2a1521de36dfde16bfab27070c6bc9f91e5%3C/a%3E)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by theXDkidoflol** [comment]
god someone please fix this
