### ISSUE TITLE
[GENERAL] Wizoff & EGY Deck has missing card sprites when drawn

### ISSUE THREAD

**Issue by GigglingRaven** [CHOMPStation2/CHOMPStation2#6325]
#### Brief description of the bug
Whenever you draw the face side of a Wizoff or EGY card, the entire card becomes invisible and unable to select save for right clicking due to the missing texture. (The backside still has a sprite)

#### What you expected to happen
I expected to be able to see the sprites for the Wizoff and EGY cards when drawn.

#### What actually happened
Whenever I drew from a card from the either deck or turned it from it's hidden side to it's visible side, the card becomes invisible with no sprite.

#### Steps to reproduce
- Draw a card, any Wizoff/EGY card

**Comment by FoxglovePurpur** [comment]
This was fixed by #6508 which was merged!

**Comment by FoxglovePurpur** [comment]
@Raeschen Could I get this issue closed? I hadn't realised adding the tag after the fact wouldn't close the issue.
