### ISSUE TITLE
[GENERAL] Alien Saw Missing Sprite

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#6377]
#### Brief description of the bug
The alien saw is missing a sprite

#### What you expected to happen
See-saw

#### What actually happened
No Saw

#### Steps to reproduce
- (Step 1) Spawn Alien saw or come across it
- (Step 2) No See
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/10555869/7c67005a-6520-4686-aa63-8f7701ee3d33)

**Comment by CMDRYouth** [comment]
Thanks for making this issue, the rest of us were too lazy.
