### ISSUE TITLE
Spray Bottles spray contents when placed in a outer clothing's storage.

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#64]
#### Brief description of the issue
Title above.

#### What you expected to happen
- Place spray bottle in apron.
- Bottle does not spray.
- Bottle goes into one of the storage slots in the apron.

#### What actually happened
- Place spray bottle in apron.
- Gets a face full of whatever chemical was inside of the bottle.
- Bottle goes into one of the storage slots in the apron.

#### Steps to reproduce
- Grab a spray bottle of any kind
- Place it in a apron, or other outer clothings with storage capacity.

**Comment by ExabyteDiscord** [comment]
This has since been fixed.
