### ISSUE TITLE
Xenobotany has a beekeeping crate to set up a bee hive, but no beekeeping suit or helmet.

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#65]
#### Brief description
Title above. I would think someone would like to make a beehive while not getting stung to death by bees.

**Comment by TheFurryFeline** [comment]
This, apparently, isn't actually a thing in the code. Never had anything that went with said beekeeping crate for protection against bees. Have people been stung before by the bees? Either way, this is, at present, more of a feature request than a mapping issue.

**Comment by ExabyteDiscord** [comment]
Beekeeper outfits don't exist here as bees aren't physical mobs that sting you. This could be corrected if someone deems necessary? Leaving open
