### ISSUE TITLE
[GENERAL] Diona can "split" in VR, thus losing their ability to leave. Be that from Ghosting to VR or Playing in VR.

### ISSUE THREAD

**Issue by FoxglovePurpur** [CHOMPStation2/CHOMPStation2#6565]
#### Steps to reproduce
- Go into VR as a Diona, ghost or otherwise
- Use the Split verb

**Comment by xnqm8h** [comment]
Have you tried having the diona make a new gestalt in VR after splitting?

**Comment by FoxglovePurpur** [comment]
Ah, sorry! I have not. Mostly because I'm not fully certain _how_ to gather into a gestalt.
