### ISSUE TITLE
[GENERAL] Tactical AR Visor lacks AR

### ISSUE THREAD

**Issue by CMDRYouth** [CHOMPStation2/CHOMPStation2#6683]
#### Brief description of the bug
The Tactical AR Visor does not have AR Vision; IE seeing AR Projections of people and the NIFSoft Vendor effects, etc.

#### What you expected to happen
Be able to see people in AR and actually have Augmented Reality.

#### What actually happened
Job Icons.  Just Job Icons.

#### Steps to reproduce
- (Step 1) Select Tactical AR Visor in Loadout
- (Step 2) Spawn
- (Step 3) Observe as you cannot see AR Projections with these Visors

#### Code Revision
 Server revision: B:-Using TGS- D:-Using TGS-
Commit: [4e50bd8fdfa252ac296e804b30fcc6294a2984ca](http://127.0.0.1:57723/tmp12800/%3Ca%20href=%22https://github.com/CHOMPStation2/CHOMPStation2/commit/4e50bd8fdfa252ac296e804b30fcc6294a2984ca%22%3Ehttps://github.com/CHOMPStation2/CHOMPStation2/commit/4e50bd8fdfa252ac296e804b30fcc6294a2984ca%3C/a%3E)
TGS version: 4.15.7
DMAPI version: 5.3.0

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by FoxglovePurpur** [comment]
This was changed in #6690 with commit [19b0eb807d9200168d95e1b3d627c1b7f105149e](https://github.com/CHOMPStation2/CHOMPStation2/pull/6690/commits/19b0eb807d9200168d95e1b3d627c1b7f105149e)!
I never noticed you opened an issue on github sadly, sorry~

**Comment by FoxglovePurpur** [comment]
Gonna mention @Raeschen just cuz they're the maintainer I know is checking git. :3
