### ISSUE TITLE
Discord Bot That Makes GitHub Issues

### ISSUE THREAD

**Issue by FoxglovePurpur** [CHOMPStation2/CHOMPStation2#6827]
#### Brief overview of the feature
Literally I want a Discord bot that allows people to make GitHub Issues, Suggestions, Reports, Etc, all without making an account since it is mind numbing to know what is and isn't a pressing issue when so few use the Issues system GitHub has.

#### What you want to happen
Using Discord's bot api thingy, make a layout to fill that will format a GitHub Issue prompt.

**Comment by ItsSelis** [comment]
If such a bot gets implemented it should also have some kind of search (or maybe cache?) of already open issue titles or maybe even their content of sorts to let the user view it to check if such an issue already exists.

Otherwise duplicate issues migth occur on GitHub and clutter the list.
