### ISSUE TITLE
[GENERAL] Vore belly damage affects item digestion.

### ISSUE THREAD

**Issue by Jesseman1** [CHOMPStation2/CHOMPStation2#6833]
#### Brief description of the bug
When editing vore belly damage controls, the damage types selected have an impact on item digestion effectiveness.
I'm not sure if this is intended or an oversight, but it does make some flavor vore belly mechanics difficult to achive.

#### What you expected to happen
I expect item digestion to work separately from prey digestion, allowing different processes to take place in the belly at once.

#### What actually happened
I moved a prey into a belly with digest mode on, but the digestion damage was limited to only suffocation damage, this belly is intended as a fluff mechanic as a result from resisting. At the same time, I turned item digestion on, to start damaging worn items as also part of a fluff mechanic, but no damage was dealt to clothing or items.

#### Steps to reproduce
- Select a vore belly and set all digestion damage types except suffocation to 0. Set suffocation damage to 6(the value I used)
- Turn on digestion and item digestion.
- Swallow a prey(preferably a prommie so they don't suffocate.) to that belly and hold them there. Their items are unaffected.

#### Code Revision
- Server revision: B:-Using TGS- D:-Using TGS-
Commit: [Link](http://%3Ca%20href%3D%22https//github.com/CHOMPStation2/CHOMPStation2/commit/b9e34f07464804729c13efacbc12e67c8dc596dd">https://github.com/CHOMPStation2/CHOMPStation2/commit/b9e34f07464804729c13efacbc12e67c8dc596dd</a>)
TGS version: 4.15.7
DMAPI version: 5.3.0

**Comment by CMDRYouth** [comment]
What're you expecting to happen with Suffocation on items?
It's not like the clothes are gonna get strangulated out of existence.
You can't **SUCK** the air out of them and they just disappear.

Brute and Burn work because they simulate mulching and melting respectively.

**Comment by Verkister** [comment]
It's intended. Only brute/burn damages affect items due to the other types kind of requiring metabolism and genetics. I've kinda been planning to add a setting for item damage multiplier though, so you can expect that to work when such setting button eventually shows up in the vorepanel.
