### ISSUE TITLE
[GENERAL] Engineering accessory banned from engineer role.

### ISSUE THREAD

**Issue by Jesseman1** [CHOMPStation2/CHOMPStation2#6839]
#### Brief description of the bug
The AR-E glasses designed for the engineering department listed in the loadout accessories tab are for some reason restricted from the engineering job role, but not for the atmospherics job role.

#### What you expected to happen
When I select the engineering AR-E glasses in my loadout, I expect to spawn with the glasses on me when playing as either engineer or atmospheric technician.

#### What actually happened
I get a message saying that the AR-E glasses are restricted for the Engineering job, HOWEVER, the glasses WILL spawn on me if I select the Atmospherics job. I also want to point out that these glasses are freely available for engineers from the Engi-vend machine in the engineering storage room. So it makes no sense for these glasses to be allowed on the Atmos job but restricted for the engineering job.

#### Steps to reproduce
- Select the AR-E glasses from the accessories tab in loadout.
- Select the engineer job role
- Spawn in.

**Comment by FoxglovePurpur** [comment]
That's odd, though, a relatively easy fix.
Give me some time and I may be able to get that fixed for you.

**Comment by JesusChristItsJasonBourne** [comment]
I have tested this live, it is no longer the case, this was fixed nov 25 by https://github.com/CHOMPStation2/CHOMPStation2/pull/7276
