### ISSUE TITLE
[GENERAL] Muffle vore belly addon does not muffle emotes

### ISSUE THREAD

**Issue by Jesseman1** [CHOMPStation2/CHOMPStation2#6881]
#### Brief description of the bug
The Muffle addon to vore bellies does muffle speech, but it does not muffle emotes, they will still display clearly to anyone within viewing distance of the predator.

#### What you expected to happen
I expect the muffle addon to muffle both speech and emotes, either limiting them to adjacent tiles or the exact tile the predator is standing on.

#### What actually happened
Emotes are still 'seen' from a distance away from the predator, as if the muffling affect is not on at all.

#### Steps to reproduce
- Have a predator swallow you into a belly with the muffle addon
- Use ! to emote something.

**Comment by Sharkmare** [comment]
this seems works as intended. Speech is audible emotes largely are visual. a seperate belly addon for that would be an idea

**Comment by SpringSkipper** [comment]
> > this seems works as intended. Speech is audible emotes largely are visual. a seperate belly addon for that would be an idea
> 
> If emotes are intended to be visual and not audible, why are deafened players unable to see emotes? That's a clear contradiction in base game code. If emotes are considered the same as speech by the deafness trait, then emotes should be considered the same as speech by the muffle addon.

This is an issue with blind, not with muffling. Blind is known to be almost unplayable due to this.
