### ISSUE TITLE
[GENERAL] Default nutrition examine texts are outdated and need to be revamped.

### ISSUE THREAD

**Issue by SpadesNeil** [CHOMPStation2/CHOMPStation2#7121]
#### Brief description of the bug
Go to `var/list/nutrition_messages` in these two files and replace all of those messages with new ones.
https://github.com/CHOMPStation2/CHOMPStation2/blob/c673607f898a1df448e480136a236fff16f21faf/code/modules/vore/eating/vore_vr.dm#L89C2-L89C2
https://github.com/CHOMPStation2/CHOMPStation2/blob/c673607f898a1df448e480136a236fff16f21faf/code/modules/vore/eating/living_vr.dm#L67C1-L68C1

The reason this is necessary is that these examines were created during the very earliest days of Vorestation code and it was made way way way way way way way before persistent weight gain or customizable belly emotes or any of the stuff we have now was ever a thing. There was no vore panel. Bellies were unchangeable. This code is long overdue for an update and it should be revamped.

The way this code functions is way more consistent with showing other players how hungry a predator is; not how big their belly is full of food. We also have liquid options for that which do a stupidly better job. A lot of players just entirely disable these texts once they know how, as they always get in the way of superior current systems.

Here's what you should replace each line with for now. I don't know how to do this, but it should also be made compatible so you can write %pred in the screen to reference yourself. The goal of these lines is to be gender neutral, to be vague enough to work on most player anatomy, and to serve as a less contradictory baseline that still works regardless of if they visibly have prey or not.

```
"They are positively famished and must have skipped a few meals! You can hear their gut snarling from across the room, and they're noticeably fatigued.",
"They are definitely hungry at the moment. A needy growl occasionally rumbles from their aching tummy.",
"",
"They're looking pleasantly full at the moment without being too overly stuffed.",
"They're looking a bit overly full at the moment, having stuffed themselves more than necessary.",
"Judging by all that churny glorpling that emenates from their digestive system, they've definitely eaten too much today.",
"You can hear their belly gushing and groaning as it struggles to work through all the calories they've consumed.",
"You can hear constant boiling and burbling as their digestive system strains with everything that's pumping through it.",
"You can tell by their lethargic body language and somewhat queasy expression that they've seriously overindulged on the snacking today. It's way more than their digestive system was built to handle in one go.",
"After gorging themselves like the complete glutton that they are, they've reached their absolute limit on how much their body can take. Anything crammed in after this is only going to make them sick."
```

Hopefully this is an improvement over the current system. It doesn't have to be exactly this but these text lines were seriously in need of replacement.

#### Code Revision
- https://github.com/CHOMPStation2/CHOMPStation2/commit/c673607f898a1df448e480136a236fff16f21faf

**Comment by SpadesNeil** [comment]
1. They are positively famished and must have skipped a few meals! You can hear their gut snarling from across the room, and they're noticeably fatigued.
2. They are definitely hungry at the moment. A needy growl occasionally rumbles from their aching tummy.
3. (blank on purpose)
4. They're looking pleasantly full at the moment without being too overly stuffed.
5. They're looking a bit overly full at the moment, having stuffed themselves more than necessary.
6. Judging by all that churny glorping that emanates from their digestive system, they've definitely eaten too much today.
7. You can hear their belly gushing and groaning as it struggles to work through all the food they have consumed.
8. You can hear constant boiling and burbling as their gut strains to process everything that's pumping through it.
9. You can tell by their lethargic body language and somewhat queasy expression that they've seriously overindulged on the snacking today. It's way more than their digestive system was built to handle in one go.
10. After gorging themselves like the complete glutton that they are, they've just about reached their absolute limit on how much their body can take. They are definitely going to be sick if they keep eating.

**Comment by SpadesNeil** [comment]
I'd still like to have this changed. It's an easy change if only I knew how Github worked.

**Comment by RandoGuy999** [comment]
given up on this?

**Comment by RandoGuy999** [comment]
> I still intend to change this.

This statement still true?

**Comment by SpadesNeil** [comment]
> This statement still true?

Yes. And now the power of Github is finally unlocked for me. It is only a matter of time now. :>

**Comment by SpadesNeil** [comment]
a
