### ISSUE TITLE
Gem Encrusted Voidsuit Sprites borked. 

### ISSUE THREAD

**Issue by crabcube** [CHOMPStation2/CHOMPStation2#7297]
#### Brief description of the bug
Gem encrusted voidsuit is missing a Tajaran body sprite.

#### What you expected to happen
The voidsuit to match the helmet when configured to the Tajaran body.

#### What actually happened
The helmet configuration changed but the suit does not show on the sprite.

#### Steps to reproduce
- (step 0) Be a tajara
- (Step 1) Find a gem encrusted voidsuit 
- (Step 2) find a suit cycler (not possible as science)
- (step 3) put the suit and helmet into the cycler and set the tajara body
- (step 4) Enjoy

#### Code Revision
- Server revision: B:-Using TGS- D:-Using TGS-
Commit: [4a34d7d3f44152b02888995f6a3ca804cbd3de6b](http://127.0.0.1:58942/tmp20192/%3Ca%20href=%22https://github.com/CHOMPStation2/CHOMPStation2/commit/4a34d7d3f44152b02888995f6a3ca804cbd3de6b%22%3Ehttps://github.com/CHOMPStation2/CHOMPStation2/commit/4a34d7d3f44152b02888995f6a3ca804cbd3de6b%3C/a%3E)
TGS version: 4.15.7
DMAPI version: 5.3.0

**Comment by crabcube** [comment]
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/88477406/c33095e2-3d9e-4f3d-9989-9d83b2bf4e3e)
![2](https://github.com/CHOMPStation2/CHOMPStation2/assets/88477406/567058a8-6a1c-47f9-8585-9f6adcd3507c)

**Comment by SpadesNeil** [comment]
Not fixed, afaik
