### ISSUE TITLE
Some tabs in whitemode (in the verbpanel) have white text

### ISSUE THREAD

**Issue by ItsSelis** [CHOMPStation2/CHOMPStation2#7400]

**Comment by Kashargul** [comment]
which tabs? Would be good to get their names.

**Comment by Kashargul** [comment]
https://github.com/CHOMPStation2/CHOMPStation2/blob/5af5b337b78dcf0575f038b19a81a2d36f5faaf9/code/modules/admin/verbs/SDQL2/SDQL_2.dm#L673

**Comment by Kashargul** [comment]
Should be resolved in the new panel?
