### ISSUE TITLE
Custodial Locator crash when opened

### ISSUE THREAD

**Issue by r4d6** [CHOMPStation2/CHOMPStation2#741]
Brief description of the issue
I open the custodial locator app in my PDA

What you expected to happen
To open the app

What actually happened
Crashed with a blue screen and an error message.

Steps to reproduce
Open the PDA (With the correct cartridge)
Try to the custodial locator app
PDA Crash
Anything else you may wish to add:
![2020-10-21 13_41_16-](https://user-images.githubusercontent.com/50276533/96757509-85c7e880-13a3-11eb-9cb5-f9a514eaf3a0.png)

**Comment by r4d6** [comment]
Turns out that Virgo [had it](https://github.com/VOREStation/VOREStation/issues/8387), [solved it](https://github.com/VOREStation/VOREStation/issues/8387), and apparently something reverted it for us.

**Comment by Shadow-Quill** [comment]
> Turns out that Virgo [had it](https://github.com/VOREStation/VOREStation/issues/8387), [solved it](https://github.com/VOREStation/VOREStation/issues/8387), and apparently something reverted it for us.

It looks like that fix was pre-TGUI. I recommend that you open an issue report on Polaris.
