### ISSUE TITLE
[UI] TGUI consistent crash (Memory-related?)

### ISSUE THREAD

**Issue by Aroliacue** [CHOMPStation2/CHOMPStation2#7432]
#### Brief description of the bug
TGUI consistently crashes at random intervals, citing out-of-memory. System memory's at 16gb, Byond barely uses 3gb.
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/96730930/bf430f45-afe0-4b71-96f2-6af2737942da)

#### What you expected to happen
TGUI to not crash.

#### What actually happened
TGUI crashes.

#### Steps to reproduce
Unsure.

#### Code Revision
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/96730930/d6dedf13-4f10-4295-932c-301ba2c95bb2)
 

#### Anything else you may wish to add:
Nil.

**Comment by ItsSelis** [comment]
Different kinds of automatic archive functions have been added to mitigate this issue.
