### ISSUE TITLE
[GENERAL] Tabard Dress Sprite missing sprites

### ISSUE THREAD

**Issue by SgoilearAlca** [CHOMPStation2/CHOMPStation2#7473]
The Tabard-dress sprite is broken for both the black and white dresses, shows missing sprite error, likely an issue with the file path or the sprite sheet getting deleted

For there to be a Tabard-Dress on the character

The SUIT missing texture sprite appears instead

#### Steps to reproduce
- (Step 1) Go to Character Loadout
- (Step 2) Go to the Casual Dress tab
- (Step 3) Select Tabard-dress Selection
- (Step 4) Choose either the Black or White tabard dress

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: [e2017824f22ec378c0e9d16ffc578da86530c7ef](https://github.com/CHOMPStation2/CHOMPStation2/commit/e2017824f22ec378c0e9d16ffc578da86530c7ef)
TGS version: 4.15.7
DMAPI version: 5.3.0
The following pull requests are currently test merged:
[#7419: 'Adding some sprites I've had sitting around unfinished' by BlackMajor at commit 0457f2329c](https://github.com/CHOMPStation2/CHOMPStation2/pull/7419)
[#7465: '[WIP] New shadekin ability' by TheGreatKitsune at commit 39df2de435](https://github.com/CHOMPStation2/CHOMPStation2/pull/7465)
 

#### Anything else you may wish to add:
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/154709857/a40a0ab2-bd7d-47c4-9551-29e1669bf336)

**Comment by JesusChristItsJasonBourne** [comment]
While the item icons for these tabards do exist at the bottom of icons\inventory\uniform\item.dmi , none of the dmi's modified by the PR that ported this contain 4 sided sprites for wearing these tabards, additionally the tabards don't exist in icons\inventory\uniform\mob.dmi where you would think it should go - or really any mob.dmi that I could check, so unless I've missed something the sprites weren't ever ported in consequently and need to be sourced or created. - here is the PR that ported them https://github.com/CHOMPStation2/CHOMPStation2/pull/7340/files for reference

**Comment by JesusChristItsJasonBourne** [comment]
the wearable sprites should they be found to actually be missing can be obtained from Cit's RP github at the bottom of this DMI file https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/master/icons/mob/clothing/uniform.dmi
