### ISSUE TITLE
[GENERAL] Tesh feathers sprite bug

### ISSUE THREAD

**Issue by Echopsychotic** [CHOMPStation2/CHOMPStation2#7540]
#### Brief description of the bug
When selecting the tesh feathers marking it doesnt appear. 

EDIT: custom species tesh do not have this problem, but base species tesh do

#### What you expected to happen
I wanna not have a black smudge on my tesh form

#### What actually happened
I have perma black wing feathers

#### Steps to reproduce
go to char creator, select teshari, select feathers marking, try to recolor

**Comment by Kashargul** [comment]
Does this still happen?
