### ISSUE TITLE
[GENERAL] AI shells losing the ability to see emotes

### ISSUE THREAD

**Issue by SpaceMan-Jim** [CHOMPStation2/CHOMPStation2#7663]
#### Brief description of the bug
AI would be unable to see emotes or any other similar messages in the chat, ranging from emotes to heath analyzer scans. It seems to be caused when using the 'Transfer-to-Shell' verb.

#### What you expected to happen
To see a emote or a message when I point at something while in a AI shell.

#### What actually happened
I infact did not see a message in the chatbox saying "X points at X!", or any emotes from other players or myself.

#### Steps to reproduce
- (Step 1) Play AI and acquire two AI shells.
- (Step 2) Jump into one shell, then use the 'Transfer-to-shell' verb in robot commands tab to appear in the second shell.
- (Step 3) Attempt to emote.
 

#### Anything else you may wish to add: 
Additionally, it would display a emote in a odd manner. With the text (BODY) next to the message containing it or even /says from myself or others if you were near the original shell that you used 'Transfer-to-shell' verb to jump out of and into another. I have been told it is a thing similar to Aghost. ...While I'd think it would be cool if AI shells could still hear around them even when the AI is not actively in them- Not being able to see emotes or posts is kinda alarming.

![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/127170206/bd839521-7710-4851-a35c-36b462751518)

![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/127170206/7282fa1c-d50f-4ee1-929f-e5339f4d6815)

**Comment by Kashargul** [comment]
Issue in the chomp sideloading proc

Normal back and forth works:
Deploy-to-Shell 
AI to shell
