### ISSUE TITLE
[GENERAL] TGS Status command not properly responding

### ISSUE THREAD

**Issue by ItsSelis** [CHOMPStation2/CHOMPStation2#7759]
#### Brief description of the bug
On the 15.02.2024 a bug/issue ocurred that made the bot unavailable to respond the status command. It is yet unknown if this was just a one-time issue or will re-appear in the future.

#### What you expected to happen
To show some manifest information like current round time and active/online players.

#### What actually happened
Bot responded with "TGS: Command processed but no DMAPI response returned!"

#### Steps to reproduce
- (Step 1) Go into #ss13-bot
- (Step 2) Write "@ Cerberus status"

**Comment by Kashargul** [comment]
Seems to work now. We should still take a look why we have null clients in the client list.
