### ISSUE TITLE
Micro exiting bag on his own with inventory open causes the micro sprite to remain on screen.

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#78]
#### Brief description of the issue
If a micro is in a bag, and they exit while you have the bag open it will cause the icon to stick, preventing you from removing it.

#### What you expected to happen
- Micro jumps out of bag on his own
- The micro's icon doesn't stick to the screen.

#### What actually happened
- Micro jumps out of the bag.
- Micro icon is now stuck on the screen.

#### Steps to reproduce
- Get a micro
- Put them in a bag
- Keep bag inventory open
- Tell micro to get out of bag

**Comment by Razgriz1032** [comment]
This is an issue with base code that has been around for millennia. It's not just micros, it's whenever any item is removed from your bag. This is not a priority fix.
