### ISSUE TITLE
[UI] Ticket System scrollbar not functioning correctly

### ISSUE THREAD

**Issue by ItsSelis** [CHOMPStation2/CHOMPStation2#7828]
#### Brief description of the bug
If the list of tickets get long enough (for example when viewing the tickets with the "All States" filter to see even closed ones) the scrollbar doesn't really appear and it scrolls the entire window instead of just that little part of it.

#### Steps to reproduce
- (Step 1) Have enough tickets that it fills the list of the Tickets UI
- (Step 2) See that the scroll bar is not really there for the list

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: [5baf424d031f69af5370d6cdf32f149dc303ebd5](https://github.com/CHOMPStation2/CHOMPStation2/commit/5baf424d031f69af5370d6cdf32f149dc303ebd5)
TGS version: 6.2.0
DMAPI version: 5.8.0
The following pull requests are currently test merged:
[#7783: 'The 515 MegaPR early downport' by cadyn at commit 54ebabd9e9](https://github.com/CHOMPStation2/CHOMPStation2/pull/7783)
[#7796: 'Ports TGS event handler' by ItsSelis at commit 197b3af751](https://github.com/CHOMPStation2/CHOMPStation2/pull/7796)
[#7812: 'Breaking down the Vorepanel.jsx file' by ItsSelis at commit f2453aa2e2](https://github.com/CHOMPStation2/CHOMPStation2/pull/7812)

**Comment by Kashargul** [comment]
Seems like the `Section` element needs the `fill` attribute, but that requires some adjusting of the layout.

**Comment by Kashargul** [comment]
Same issue on the vorepanel belly subtab. It also would need a small adjustment
