### ISSUE TITLE
[UI] TGUI can't open >1 Window anymore

### ISSUE THREAD

**Issue by CMDRYouth** [CHOMPStation2/CHOMPStation2#7862]
#### Brief description of the bug
Title.  TGUI used to be able to support opening more than one window back in the start of February, but had inexplicable issues introduced aside this before the end of January.

#### What you expected to happen
Being able to have more than 1 TGUI Window open at the same time, IE using multiple Chem Machines instead of one at a time.

#### What actually happened
Only one window stays open, and trying to open any other results in a white box that fails to initialize or something.

#### Steps to reproduce
Try to open more than 1 TGUI Window at the same time, IE:
- (Step 1) Click on a Chem Dispenser
- (Step 2) Click on the ChemMaster

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: [5de38fdc17eafc721237cbbbebac4c0f886bda87](https://github.com/CHOMPStation2/CHOMPStation2/commit/5de38fdc17eafc721237cbbbebac4c0f886bda87)
TGS version: 6.3.1
DMAPI version: 5.9.0
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/11749157/b9b9ef24-4fb5-4521-9d65-42541e005d82)

**Comment by CMDRYouth** [comment]
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/11749157/d8507ef1-3edf-4705-950b-cddd4af4fbd4)

**Comment by RandoGuy999** [comment]
Having a similar issue, but I figured out that if you press refresh tgui right after the white box appears, the windows will both display correctly after a few seconds.

**Comment by Raeschen** [comment]
Please clear your BYOND cache and your IE cache. There's an explanation of how to do this in discord in the announcements channel here [https://discord.com/channels/180538463655821312/408623786200399892/1209115266626224158](url) but i'll paste it here too

BYOND cache:
Make sure no BYOND applications are running. BYOND window > Gear wheel, top right > preferences > games > Clear Cache

IE cache:
If you use the 515(beta) client, you will also need to CLEAR YOUR IE cache. This is "Delete cookies or temporary files" in start, and then 'General' > Browsing history > Delete... > Temporary internet files and website files, and cookies and website data.

**Comment by Kashargul** [comment]
Can not reproduce this.

**Comment by Kashargul** [comment]
Verify that you are using latest 515. Clear IE cache. Report back within 1 week, else I close this.
