### ISSUE TITLE
Cannot hear the jukebox behind the bartender counter

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#79]
#### Brief description
The title is literally the entire problemo, I wanna listen to smooth jazz while making drinks maaaaan.

**Comment by TheFurryFeline** [comment]
Mapping issue, as stated on discord dev channel. Multiple areas for multiple parts of the bar, kitchen, cafeteria sections done for obvious reasons. Bar has its own APC for the shutters to stay shut, and kitchen for ditto. Jukebox code, as it is, only allows one to hear music within the same area. Unsure if it's possible to expand on viewrange.

**Comment by Kazzc** [comment]
Not much I can do map-wise in this regard, so removing it from map.
Might be able to do something in regards of coding. I found a proc called "Master_Area", maybe that can force it to play in more than one area?, unsure, check it out.
