### ISSUE TITLE
[UI] UI bugged/icons missing for resleeve console and bottle/pill designs

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#7919]
#### Brief description of the bug
Icons/images on the UI for the resleeve console and synthesiser are missing

Bottle images and the images of the growing pods on the UI menu are replaced with "X"

Images should be present but aren't

#### Steps to reproduce
Just open up the console UI for the resleever console and it's on the first page. For the bottles and pills, try and change the bottle design in the synthesiser or ChemMaster

**Comment by Kashargul** [comment]
UIs using assets to check:

- [ ] CloningConsole.jsx
- [ ] ResleevingConsole.jsx
- [ ] ChemSynthesizer.jsx
- [ ] ChemMaster.jsx
- [ ] NanoMap.jsx

**Comment by Kashargul** [comment]
Need to check the NTOS some more
