### ISSUE TITLE
gameTimestamp() proc always returning 15:59:59

### ISSUE THREAD

**Issue by ItsSelis** [CHOMPStation2/CHOMPStation2#7945]
#### Brief description of the bug

Currently this proc seems to always return "15:59:59", not mattering which time it currently is.

A good example to check this out is inside of tickets.

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: [26d49eb2f7689792231d7494d694aabfb2b06b52](https://github.com/CHOMPStation2/CHOMPStation2/commit/26d49eb2f7689792231d7494d694aabfb2b06b52)
TGS version: 6.4.0
DMAPI version: 5.9.0
The following pull requests are currently test merged:
[#7797: 'ViewVariables Updates' by ItsSelis at commit 448dc35d16](https://github.com/CHOMPStation2/CHOMPStation2/pull/7797)
[#7906: 'New planet: Thor' by tacoguy7765093 at commit 3d25bad6ba](https://github.com/CHOMPStation2/CHOMPStation2/pull/7906)

**Comment by Kashargul** [comment]
usr.say(time2text(world.time, "hh:mm:ss"))

works... so we should check the offset math

/proc/gameTimestamp(format = "hh:mm:ss", wtime=null)
	if(!wtime)
		wtime = world.time
	return time2text(wtime - GLOB.timezoneOffset, format)

**Comment by Kashargul** [comment]
https://www.byond.com/forum/post/2916778

**Comment by Kashargul** [comment]
Fixed in byond 515.1634
