### ISSUE TITLE
[UI] Icons in vore belly ~~won't load~~ don't collapse into a list when there's too many

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#7968]
#### Brief description of the bug
Eating too many items causes the item icons to not ~~load in the vore panel UI (bug noticed as prey)~~ collapse into a compact list

#### What you expected to happen
~~Icons display in each section for each item (screenshot posted to discord)~~ Upon reaching 21 items, the icon display should compact into a list display instead

#### What actually happened
Icons display as an "X" and do not collapse into a list

#### Steps to reproduce
- Get ate
- Have a ton of items in the belly (I noticed this effect at about 21 items not including myself)
- Icons disappear after the "21st" item is dropped in, UI does not collapse into a list

**Comment by Kashargul** [comment]
Screenshot here please. Wasn't that a hardcoded limit for when icons change to lists?

**Comment by Missile597** [comment]
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/150307788/92ff3d05-650d-4628-bda2-0f9bea6b83c1)
I think that screenshot worked?
This was also mentioned on discord. I think the issue is not the icons but that the UI isn't collapsing into a list like it should? So it stops pulling the icons but the UI doesn't collapse into a list but stays in icon mode

**Comment by Kashargul** [comment]
That is strange, something to look into for sure. Ye. It should be a list at that point

**Comment by Kashargul** [comment]
I found the issue, oversight, I will add it later today.
