### ISSUE TITLE
[GENERAL] Changing to a mob-shadekin in VR bugs out the player

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#7980]
#### Brief description of the bug
Using the "transform into creature" verb in VR to turn into a shadekin causes the player to warp into a void and get stuck there. Potentially also causes a server crash? Unsure about this though. Live crashed shortly after this was reported but my private instance did not crash when replicating.

#### What you expected to happen
Transform into a mob shadekin on the spot, in VR

#### What actually happened
Black screen

#### Steps to reproduce
- Observe in round
- Enter VR
- Use "transform into creature" verb and transform into a shadekin

#### Code Revision
Might be relevant - Kashargul mentioned a potential issue with a verb testmerge somewhere. Am unable to check for myself though

**Comment by Kashargul** [comment]
Exception has occurred: Attempted to add a new component of type [/datum/component/hearer] to a qdeleting parent of type [/mob/living/simple_mob/shadekin]!
Exception has occurred: Attempted to add a new component of type [/datum/component/character_setup] to a qdeleting parent of type [/mob/living/simple_mob/shadekin]!
Exception has occurred: Attempted to add a new component of type [/datum/component/vore_panel] to a qdeleting parent of type [/mob/living/simple_mob/shadekin]!
