### ISSUE TITLE
✨ Make RD networks require multitool linking opposed to being global

### ISSUE THREAD

**Issue by ReoDaProtovali** [CHOMPStation2/CHOMPStation2#8048]
#### Brief description of the feature
Research is currently a global thing. This causes many issues ranging from outsiders having access to NT's research network to allowing powergaming by building a protolathe outside of science.

Adding this would also set the stage for eventual departmental lathes.

#### What you want to happen
I would like research's network to require linking devices via Multitool, or be Z-Level. Maybe links persist with the circuit board to make it less of a pain to reorganize RND setups, while still requiring new machines to get linked.

**Comment by Kashargul** [comment]
We are going to use a board that forbids linking all together UI wise.

**Comment by ReoDaProtovali** [comment]
I feel like that's a bandaid fix being pushed to be a feature, but alright. Disks mostly exist so people can make backups in places where antagonists are likely to delete all the research, or as a way for anagonists to steal research. Forcing people to use them in place of proper linking mechanics just feels like polaris move, honestly.

**Comment by Kashargul** [comment]
We want more interaction between outsiders and the station. This is one way to trade research without having an outsider simply push research 15 minutes into the round.

**Comment by ReoDaProtovali** [comment]
and adding a linking system doesn't prevent that. it makes building research using systems easier. If you're afraid of the station just giving a link to outsiders, it could be against the rules to do so without head approval, kind of like accessing the armory. This really isn't a reason to not have links.

**Comment by Kashargul** [comment]
> and adding a linking system doesn't prevent that. it makes building research using systems easier. If you're afraid of the station just giving a link to outsiders, it could be against the rules to do so without head approval, kind of like accessing the armory. This really isn't a reason to not have links.

If you want it, code it. Currently the focus is on performance and stability.
