### ISSUE TITLE
[UI] Outsider RD consoles can still be synced to servers even if sync = 0

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8051]
#### Brief description of the bug
The new outsider console /obj/machinery/computer/rdconsole/public has their sync var set to 0 to prevent outsiders from syncing with the station, but even then, clicking the "Connect to Research Network" button will resync it back to station.

#### What you expected to happen
Outsider consoles being unable to set sync = 1 by any means necessary 

#### What actually happened
sync = 1 after pushing a button.

#### Steps to reproduce
- (Step 1) Use a  /obj/machinery/computer/rdconsole/public in any situation
- (Step 2) Click the settings tab
- (Step 3) Click  "Connect to Research Network"

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)
- This is TGUI stuff so I cant work on this

https://github.com/CHOMPStation2/CHOMPStation2/assets/10555869/95f13895-ea67-4d3a-8203-ecee9819b4d3

**Comment by Kashargul** [comment]
Todo me
