### ISSUE TITLE
[GENERAL] RPD Disposal junctions bugged

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#8056]
#### Brief description of the bug
So I tried taking a look at this RPD and disposals code but it was just too confusing for me so leaving it to someone smarter than I. The flipped disposals junctions do not pull through correctly on the RPD menu. The unflipped ones work fine, but to get a flipped one currently you have to place an unflipped one, then flip manually. The flipped junctions display like an atmos pipe, and when attemtping to place one, the junction that is placed is bugged out (directions do not match icon, contents spat out from the junction when attempting to use). Also when rotating the bugged junctions it doesn't seem to rotate properly.

#### What you expected to happen
Contents passes through the junction in the direction it looks like in-round. Icons in RPD menu display the correct icon of a flipped junction.

#### What actually happened
Contents spat out at junction, likely to direction arguments not being correct and not matching the icon_state. Icons display in menu as a straight atmos pipe.

#### Steps to reproduce
- Grab an RPD from engineering
- Build some disposals segments and weld into place. Use one of the "bugged" junctions that display as a pipe
- Attempt to pass something through the pipework

#### Anything else you may wish to add:
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/150307788/b55d847c-8e0c-4080-8bb5-921fade52c67)
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/150307788/52f5b42b-5038-419d-8786-b37494c309ac)
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/150307788/8606a981-5259-46af-a385-eddc57771485)
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/150307788/0e204673-1a04-4299-a434-88fda6768883)

**Comment by Kashargul** [comment]
icons for those directions simply don't exist, neither for the junctions, nor the tvalves, therefore they can't be displayed.

Seemingly the direction of those states is off.

**Comment by Kashargul** [comment]
fixed with #8176
