### ISSUE TITLE
Map view on computers is offset, shows z-levels it shouldn't

### ISSUE THREAD

**Issue by TheCaramelion** [CHOMPStation2/CHOMPStation2#8066]
#### Brief description of the bug
This happens both in the Atmospheric Control one and the Medical's Crew Monitor.
Clicking on the Map view shows the alarms and crew offset from the map.

#### What you expected to happen
Crew and alarms positioned correctly on the map, and to not show places like CentCom or z-level shuttle transits

#### What actually happened
Crew and alarms are very off-set from the map, and showing all z-levels.

#### Steps to reproduce
- (Step 1) Go to either Medical's or Engineering's computer
- (Step 2) Click on Map view

**Comment by Kashargul** [comment]
Strange, if the console is placed on a station level, it only should get station levels....
