### ISSUE TITLE
[UI] Inserting design disks in the RD console perma bricks it via TGUI crash.

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8070]
#### Brief description of the bug
Putting a design disk (/obj/item/weapon/disk/design_disk) in any RD console and selecting 'Disk Operations' will cause a TGUI bluescreen, permanently bricking the console until someone deconstructs and  reconstructs it, wiping all data off it.

#### What you expected to happen
Being able to use the disk to copy RD designs on the disk, not crashing.

#### What actually happened
TGUI bluescreen forever

#### Steps to reproduce
- (Step 1) Spawn a /obj/machinery/computer/rdconsole/core  or any other subtype that exists.
- (Step 2) Insert a /obj/item/weapon/disk/design_disk inside of the console
- (Step 3) Click Disk Operations within the RD console UI
- (Step 4) Bluescreen
 

#### Anything else you may wish to add:

https://github.com/CHOMPStation2/CHOMPStation2/assets/10555869/a7f5558f-29b7-43bb-ab91-1d20fb1062c3

**Comment by Kashargul** [comment]
Tgui 5 oversight, will PR a fix later today

**Comment by Kashargul** [comment]
closed with #8074
