### ISSUE TITLE
[UI] TGUI crash on rdconsole when switching tabs (But only on material tab)

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8075]
#### Brief description of the bug
In the RD console, switching machine tabs while the material amounts of said machines are displayed will TGUI crash it. The RD console does not stay bricked and re-opening the window will show the correct contents.

#### What you expected to happen
Not to crash when switching from Protolathe to Circuit Imprinter while your Mat Storage is shown

#### What actually happened
You get a TGUI bluescreen, but closing and reopening the RnD console displays back

#### Steps to reproduce
- (Step 1) Open up the RD console window
- (Step 2) Click on Mat Storage in whatever machine you're selected in
- (Step 3) Click Circuit Imprinter and get a bluescreen

 

#### Anything else you may wish to add:
Tested in private instance too, same issue

<Video removed, in devchat cause ckey>

**Comment by Kashargul** [comment]
useState inside map...

**Comment by Kashargul** [comment]
fixed with #8101
