### ISSUE TITLE
Certain Hairstyles Not Appearing on Character [GENERAL] 

### ISSUE THREAD

**Issue by granodd** [CHOMPStation2/CHOMPStation2#8096]
#### Brief description of the bug
Certain hairstyles do not render properly onto the character due to not having the proper file path in the Chomp override (or so I'm told). This issue report is mostly just to provide a list of the hairstyles affected. Prior, I only had a rough list, but while making this issue report I took the time to go through all the hairstyles to see which ones were and weren't working. Here is a list of the affected styles:\
• Bobcut Over Eye
• Bobcut Over Eye 2
• Bobcut Over Eye 3
• Bonnie
• Bonnie Alt
• Bonnie, Long
• Bonnie Alt, Long
• Bonnie, Short
• Bonnie Alt, Short
• Dawn
• Diagonal Bangs
• Eagle
• Falcon
• Fluffy
• Fluffy, Long
• Hummingbird
• Inari
• Macaw
• Magpie
• Over Ear, Right
• Over Ear, Left
• Owl
• Ponytail Thin
• Ponytail Thin, Long
• Princess
• Starling
• Stork
• Taro
• Twintails
• Twintails, Long
• Twintails, Short
• Volaju, pompless
• Zone Braid

#### What you expected to happen
The hairstyle is selected and it renders properly.

#### What actually happened
The hairstyle renders, but is invisible due to not being in the Chomp override.

#### Steps to reproduce
• Select one of the listed hairstyles
• It's invisible
#### Anything else you may wish to add:
Moderately related to all of this, I also discovered that this hairstyle was offset one pixel to the right of where it should be.
• Afropuff, Right

**Comment by Kashargul** [comment]
Override: https://github.com/CHOMPStation2/CHOMPStation2/blob/master/modular_chomp/code/modules/mob/new_player/sprite_accessories.dm
