### ISSUE TITLE
[GENERAL] Unable to hear voice sounds of self or others when held by someone

### ISSUE THREAD

**Issue by Raeschen** [CHOMPStation2/CHOMPStation2#8126]
Be micro/teshari
Get held/picked up
speak / wait for others to speak
No sounds :(

**Comment by Fracshun** [comment]
I've also noted not seeing the red vore messages for when someone is attempting to or succeeds in putting others in a belly while picked up. So you can be scooped and oblivious to it all until suddenly vorefx and in a belly. Might be related?
