### ISSUE TITLE
[GENERAL] Spawning with the incorrect PDA

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#8213]
#### Brief description of the bug
Spawning in with a default PDA instead of a slider PDA. This bug happened to another CE too.

#### What you expected to happen
Should spawn in with PDA set in settings

#### What actually happened
Spawned in with a different PDA

#### Steps to reproduce
Unsure how to reliably reproduce but for me I:
- Have slider PDA type chosen
- Set job to Chief Engineer
- Join round on arrivals shuttle and have wrong PDA
 

#### Anything else you may wish to add:
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/150307788/6df8a948-6d6a-41de-b6d4-3343d53266c6)

**Comment by Kashargul** [comment]
Related to: https://github.com/CHOMPStation2/CHOMPStation2/pull/8147

New()
    ...()

calls initialize before the execution of the rest of the proc in badly written overrides.
