### ISSUE TITLE
[GENERAL] overlay bug with rigsuits and plasma cutters

### ISSUE THREAD

**Issue by cadyn** [CHOMPStation2/CHOMPStation2#8230]
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/35672377/8dd8f027-ec0a-4bb8-87d3-46cc210e6040)
something something overlays not getting cut

**Comment by JonyAlcoGames** [comment]
hi, i'm the one getting this runtime almost every round, my rig suit goes garrysmod error almost instantly after putting it on 
![5ae8dff477705276df9b219975e77ac2-1](https://github.com/CHOMPStation2/CHOMPStation2/assets/139018559/fa4208fb-5b33-46e0-8c91-5378144c5e9f)

**Comment by Kashargul** [comment]
> hi, i'm the one getting this runtime almost every round, my rig suit goes garrysmod error almost instantly after putting it on ![5ae8dff477705276df9b219975e77ac2-1](https://private-user-images.githubusercontent.com/139018559/322315201-fa4208fb-5b33-46e0-8c91-5378144c5e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNjU3OTcsIm5iZiI6MTcxMzE2NTQ5NywicGF0aCI6Ii8xMzkwMTg1NTkvMzIyMzE1MjAxLWZhNDIwOGZiLTViMzMtNDZlMC04YzkxLTUzNzgxNDRjNWU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNzE4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2NiZWY4OWQxNTc1ZjRhNjlkN2IyMjhhYmIzYzdlNjNlODgxMjA0MjY3OGE5N2EwZWEzOWE5NTAzYjQxMzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YuEobTDeflkW38Vq8PpoLmb8cN1eE14paLrGG6TVW9M)

Useless without further information

**Comment by Kashargul** [comment]
https://github.com/CHOMPStation2/CHOMPStation2/blob/027e93ba43542bf021d0e985121d174020c2c220/code/modules/clothing/spacesuits/rig/rig.dm#L604-L606

https://github.com/CHOMPStation2/CHOMPStation2/blob/027e93ba43542bf021d0e985121d174020c2c220/code/modules/clothing/spacesuits/rig/rig.dm#L618
