### ISSUE TITLE
[MAP] Bridge office and dorms sorting junctions incorrectly tagged

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#8233]
#### Brief description of the bug
Some junctions incorrectly tagged as CMO office

#### What you expected to happen
Tagged package comes out at CMO office

#### What actually happened
Package comes out at dorms

#### Steps to reproduce
- Head to mailroom and use wrapping paper to wrap a random item
- Use the tagger and tag for CMO office
- Throw into disposals

**Comment by Kashargul** [comment]
Do a full test and list which elements exactly don't work.

**Comment by Missile597** [comment]
Might have found an issue with other prefabs in the disposals loop. Will try and test and possibly resolve

**Comment by Missile597** [comment]
Issue to be resolved in my misc fixes PR... will link to this issue in the PR

**Comment by Missile597** [comment]
PR #8223 should resolve this

**Comment by Missile597** [comment]
> PR #8223 should resolve this

PR closed, this still needs fixing
