### ISSUE TITLE
[GENERAL] Mindbinded objects can no longer speak

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8234]
#### Brief description of the bug
If you use a mind binder against someone and put them onto a object, they are unable to send messages completely, they cant see them and people around cant see them either. However using emote sounds and subtles are OK, /me and say do not work.

#### What you expected to happen
A mind binded user is able to chat and /me normally.

#### What actually happened
Unable to send says and /mes, however things like *emotes and subtles are OK.

#### Steps to reproduce
- (Step 1) Get a mind binder and bind someones body.
- (Step 2) Apply mind binder on an object of any kind
- (Step 3) Try chatting as the object.

**Comment by Kashargul** [comment]
/mob/living/voice/custom_emote(var/m_type = VISIBLE_MESSAGE, var/message = null, var/range = world.view)
	if(!comm) return
	..(m_type,message,comm.video_range)

voices could never use /me. And nothing too easy to change
