### ISSUE TITLE
[GENERAL] All energy weapon icon_state start as empty sprite icon

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8300]
#### Brief description of the bug
When you spawn an energy weapon like a size gun, laser rifle, etcetc, it will show the same icon as if it was depleted of ammo. This is likely due to all of the icons being new() rather then initialize()

#### What you expected to happen
Spawn a gun in and it shows a normal full sprite

#### What actually happened
The sprite appears to be empty, however shooting once will update the icon back to its correct one.

#### Steps to reproduce
- (Step 1) Spawn or find a laser weapon
- (Step 2) ![dreamseeker_P23YzijbT2](https://github.com/CHOMPStation2/CHOMPStation2/assets/10555869/15d642b9-65f2-4444-92f1-180083791376)

**Comment by Kashargul** [comment]
I could not reproduce this on the latest code. Could you give me the path of the weapon?

**Comment by tacoguy7765093** [comment]
Hmm, try looking for any weapons map loaded round start, VR Armory, and phase weapons loaded in have this issue
