### ISSUE TITLE
[GENERAL] Martian Miner's Coat Does Not Protect From Cold

### ISSUE THREAD

**Issue by crabcube** [CHOMPStation2/CHOMPStation2#8338]
#### Brief description of the bug
Martian miner's coat, usually found in abandoned crates, does not protect you from cold, but does make cold warnings go away.

#### What you expected to happen
Comforble (not taking burn damage)

#### What actually happened
Cold, ow oooh my bones

#### Steps to reproduce
- (Step 1) Dont have temp adapt cold and instead have temp adapt heat
- (Step 2) put on coat
- (Step 3) Be cold

- (Location if it's a mapping issue, screenshots, sprites, etc.)
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/88477406/ec2290e6-f124-44ab-a750-2d002b7a40af)

**Comment by FluffMedic** [comment]
Do you have an mask and an oxygen tank active?

**Comment by crabcube** [comment]
> Do you have an mask and an oxygen tank active? You need both your body and the air you breath to be warm with warm adapt

Character has breathless trait, but was not taking cold damage in the normal mining winter coat 
the martian coat also doesn't mention cold protection!
