### ISSUE TITLE
[UI] [SILICON] Borg image taking and viewing options are both missing.

### ISSUE THREAD

**Issue by Skysteak** [CHOMPStation2/CHOMPStation2#8374]
#### Brief description of the bug
The UI options for borgs to take images and view them is missing.

#### What you expected to happen
For borgs to have options in the UI to permit image taking and viewing.

#### What actually happened

Certain TGUI changes (I am unsure which specifically) moved various borg abilities/options around. However the options to take and view images are now missing, permitting no other (as far as I know) way to use this feature. 

#### Steps to reproduce
- (Step 1)Join or spawn in as a borg.
- (Step 2)Prune the UI for the ability to take and view images.
- (Step 3) Lament as your dreams of being positronic paparazzi peter out. 

#### Anything else you may wish to add:
- I am unaware if this effects the AI or any shells it's in.

**Comment by Kashargul** [comment]
Looking into this again after #8085 has been merged. Stale until then.
