### ISSUE TITLE
[GENERAL] [SILICON] Borgs cannot drag PDAs

### ISSUE THREAD

**Issue by Skysteak** [CHOMPStation2/CHOMPStation2#8375]
#### Brief description of the bug
Borgs cannot drag PDAs that are on the ground.

#### What you expected to happen
For borgs to be capable of dragging PDAs around like any other item of that size (that's unanchored). 

#### What actually happened
Borgs are incapable of dragging PDAs around at all. The style of the PDA in question, or if it has an ID in or not has NO bearing on this. 

#### Steps to reproduce
- (Step 1)Join or spawn in as a borg.
- (Step 2) Locate a PDA on the ground.
- (Step 3) Attempt to drag it behind yourself. 
- (Step 4) Lament at the  unexpected inability to do so.

#### Anything else you may wish to add:
I am unaware if this affects AI in shells.

**Comment by Kashargul** [comment]
Worked without issue for me, please get in touch for an ingame examination of it.
