### ISSUE TITLE
[GENERAL] >200% resizes done in the shadekin retreat are not reverted to <=200% on exiting it. 

### ISSUE THREAD

**Issue by Raeschen** [CHOMPStation2/CHOMPStation2#8389]
Just reported by a player ingame

You can resize yourself above 200% in the shadekin retreat. This is intentional, the retreat is intended to be a sort of RP/dorm-like place.

However, on exit, the cue to resize you back to less or equal to 200% apparently is missed, allowing a way for people to be above 200% size outside of dorms.

**Comment by Kashargul** [comment]
To check:
- [ ] Portals
- [ ] Translocators
- [ ] Leaving inside someone
