### ISSUE TITLE
Xenobiologist to Xenobotanist occupation name change does not work.

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#84]
#### Brief description of the issue
Title above. While changing xenobiologist to xenobotanist does work in character setup, and does save, it does not actually happen once you join the shift. Your role is xenobiologist when you enter the round, not xenobotanist. This happens even if your occupation name was changed to xenobotanist, and saved.

#### What you expected to happen
- Change xenobiologist name to xenobotanist.
- When you save it and enter you round you join as a xenobotanist.

#### What actually happened
- Change xenobiologist name to xenobotanist.
- When you save it and enter a round you join as a xenobiologist, not a xenobotanist.
- Character setup says you have it set to xenobotanist.

#### Steps to reproduce
- Go to character setup.
- Change xenobiologist name to xenobotanist.
- Join the round as the xenobiologist/xenobotanist role.

**Comment by MisterGrimm** [comment]
Seems roboticist is the same way.

**Comment by Razgriz1032** [comment]
Fixed with #94
