### ISSUE TITLE
[UI] Fixing Idle Emotes, and Idle Messages

### ISSUE THREAD

**Issue by Hunter-Dovetail** [CHOMPStation2/CHOMPStation2#8430]
After some experimentation it seems that Idle Emotes/Messages play the instance someone enters the hold/digestion/absorbtion/etc. belly. However, the description states that messages play, every 60 seconds. There are 2 issues with this.
Firstly:
The delay is not necessarily 60 seconds, it depends on what the Idle Emote Delay is set to.
Secondly:
Hold/Digestion/Absorption/etc. Idle Emotes/Messages don't only play after "60 seconds", or whatever time the Idle Emote Delay is set to, they actually play immediately when the prey has entered the belly, which contradicts what the description states.

Therefore, I propose that the Idle Messages description box be updated, to clarify when Idle Emotes/Messages actually play, and what they actually do, by:
Removing the "every minute" quote in the first line, and replacing it with "after Idle Emote Delay"
Mentioning that emotes will also play the instance a prey enters a holding/digestion/absorption/etc. belly. Not just after the Idle Emote Delay.
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/170564111/0d460577-5e22-4eb3-8549-ba033695065f)

**Comment by Kashargul** [comment]
The latter won't be possible. It's attached to the constant processing timer. So it depends on activity if it sends right away or after the time. But the interval in which it sends will always depends on the delay time of the emote. The first I've addressed in an Upstream PR.

**Comment by Hunter-Dovetail** [comment]
> The latter won't be possible. It's attached to the constant processing timer. So it depends on activity if it sends right away or after the time. But the interval in which it sends will always depends on the delay time of the emote. The first I've addressed in an Upstream PR.

Ok thank you! Im fairly new, I first downloaded Byond 3 months ago, so i gather only playing emotes after the Idle Emote delay will not be possible.

Also may I ask what an Upstream PR is?

**Comment by Kashargul** [comment]
> > The latter won't be possible. It's attached to the constant processing timer. So it depends on activity if it sends right away or after the time. But the interval in which it sends will always depends on the delay time of the emote. The first I've addressed in an Upstream PR.
> 
> Ok thank you! Im fairly new, I first downloaded Byond 3 months ago, so i gather that means emotes will always play the instance prey enters a belly.
> 
> Also may I ask what an Upstream PR is?

Once the first "object" enters, from then on, every delay_time seconds again as long as the belly is processing.

Our upstream is Virgo, you can see their merged PR's when MIRROR bot PR's show up here.
