### ISSUE TITLE
[GENERAL] Timer assemblies count down by 0.1 instead of seconds

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8460]
#### Brief description of the bug
Timer assemblies (/obj/item/device/assembly/timer) when you set the time, lets say if you type in 30, it should be 30 seconds, but in reality it actually is 300 seconds that counts down by 0.1 per second instead, giving misleading times when the TGUI renders it in the 0:00 format.

#### What you expected to happen
Putting 30 in the time should show 0:30 and count down by 1 per second.

#### What actually happened
Time will be stuck at a 0:29, with the true value being 29.9, 29.8, etc etc

#### Steps to reproduce
- (Step 1) Spawn a /obj/item/device/assembly/timer
- (Step 2) Click on the time amount and enter just '30' manually, clicking off to set the time for real.
- (Step 3) Click count down and re examine the text by clicking on the entry to see its true value

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Kashargul** [comment]
Was the item used plain or build into something?

**Comment by tacoguy7765093** [comment]
This was on both grenades, and TTVs, and the tank transfer valve opens up the timers UI.

**Comment by Kashargul** [comment]
I think I see my oversight will look into it later.

Could you test a chem grenade? It might show even larger numbers due to having it's own multiplier still.
