### ISSUE TITLE
[UI] Protean abilities duplicated in UI

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#8496]
#### Brief description of the bug
Protean abilities are in two places on the UI and one of these places has verbs that don't function

#### What you expected to happen
Either they work in both places or they only exist in one place

#### What actually happened
There's multiple places the verbs exist, and the highlighted ones don't seem to work?
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/150307788/4f5da1f4-eb22-4e8a-b94a-df5628aafc0e)

**Comment by Missile597** [comment]
Also some abilities in the Abilities UI don't appear in the Protean tab either

**Comment by Kashargul** [comment]
> Also some abilities in the Abilities UI don't appear in the Protean tab either

The tab is explicitly for abilities with icons usually. The general abilities always have been under abilities.

For the non working ones, it seems like the hidden = 1 gets ignored. So I'll have to delete those procs assignment likely. They shouldn't be visible.
