### ISSUE TITLE
✨New Belly/Gullet Gif Visuals Complete-AWAITING SOMEONE TO ADD TO CHOMP

### ISSUE THREAD

**Issue by Hunter-Dovetail** [CHOMPStation2/CHOMPStation2#8566]
It has been about a month since i started on this, but I am glad to say all of my **Gullet** and **Belly** **visual** **Gifs** are complete. 

**I now need is someone/anyone to PUT them into CHOMP!**

I am very new to **Chomp**, i joined about 4 months ago, I feel everyone contributes as much as they can, so this is _my favour in return!_

I have approx. **_20 still-image visuals_** ready to go for:
- **Herbivores**
- **Felines**
- **Orcas**
- **Dinosaurs**
- **Dragons**
- **Crocs**
- **Humans** (at long last!)

**Once these 3 attached BELLY/GULLET Gifs have been put into Chompstation by someone/anyone, I shall post the rest of the still-image VISUALS on Github.**
- All still images are of similar quality and style, that is; renders, that I have mildly pixelated befitting the Chomp style, I have vetted some of them with Reo and Kasssc.

**Gullet/Belly Gifs:**:
 https://www.dropbox.com/scl/fo/6id6vixa7hi4tsabnrizx/AAPWJUkZJDTcP0xkLPx5DFE?rlkey=up03x07mrl77hgs9dxcv7o8ui&st=3kfhf76k&dl=0

In return, I only ask for 2 things:                                                                                                                                 
- To be given credit (as my discord username).
- AND that I am the only one who can change/edit my own visuals (i.e. any changes/requests go through me). The final BELLY VISUALS for Chomp should only be submitted from MY Dropbox link.

My Discord is Hunter_53073

@Kazzc @ResidentCody @Raeschen @ReoDaProtovali @SpadesNeil @Nadyr
  @Razgriz 
  @Raeschen
  @GhostActual 
  @Selis
  @Kashargul

**Comment by SpadesNeil** [comment]
![it begins](https://github.com/CHOMPStation2/CHOMPStation2/assets/6484985/47916c40-3f3c-4970-8b76-8e40ab511a69)
