### ISSUE TITLE
[GENERAL] New soulcatcher preventing ventcrawling

### ISSUE THREAD

**Issue by Dinnel** [CHOMPStation2/CHOMPStation2#8604]
#### Brief description of the bug
The new soulcatcher stuff prevent vore-capable mobs from traveling through vents, even if they don't have anything inside their soulcatcher. I tried to ventcrawl as a slugcat but I was unable to because of my 'Mind imprintation matrix'. Changing the name of it also changes the name of what is preventing the ventcrawl.

#### What you expected to happen
To be able to ventcrawl, despite having a soulcatcher.

#### What actually happened
Unable to ventcrawl with the message "You can't carry Mind imprintation matrix while ventcrawling!"

#### Steps to reproduce
- Be a mob that can vore
- Attempt to ventcrawl

#### Code Revision
Server revision: Unknown
TGS version: 6.5.0
DMAPI version: 5.9.0
 

#### Anything else you may wish to add:
![image](https://github.com/CHOMPStation2/CHOMPStation2/assets/21001987/09e3d4bd-d12e-44eb-b837-f82c27ef9a18)

**Comment by Kashargul** [comment]
Should be resolved.
