### ISSUE TITLE
[GENERAL] Attempting to transfer a soul from a soulgem into a MMI doesn't work

### ISSUE THREAD

**Issue by RandoGuy999** [CHOMPStation2/CHOMPStation2#8689]
#### Brief description of the bug
Attempting to transfer a soul from a soulgem into a MMI doesn't work cause the line of code thats suppose to check if the target obj is actually an mmi actually checks to see if the mob is an mmi, which always fails.

#### What you expected to happen
For the captured soul to get transfered into the MMI

#### What actually happened
Nothing.
@Kashargul You might be able to just throw this fix in with #8687

**Comment by Kashargul** [comment]
Feel free to test the branch, I'm more worried I broke some things on it by adding new features
