### ISSUE TITLE
[GENERAL] All medium and large ammos do not shoot proper projectiles. Ammo overrides don't work.

### ISSUE THREAD

**Issue by tacoguy7765093** [CHOMPStation2/CHOMPStation2#8732]
#### Brief description of the bug
Despite every gun in modular_chomp.code\modules.projectiles.ammo_refactor.ammo_overrides.dm overriding the projectile that it is supposed to fire, it ends up firing the ammo casing itself which has an inaccurate damage compared to the gun.

For example, loading a weapon with /obj/item/ammo_casing/simple/medium/rubber, regardless of gun will return real bullets instead.
For example, the 50 cal sniper and the AWP fire the same projectile despite having different projectiles,
Things like handguns still work as intended, modular_chomp/code/modules/projectiles/ammo_refactor/ammo_types.dm where rubber shot/special bullet flags apply as intended, but medium and large ammos do not work properly, **returning only the bullet casing's** projectile instead of the override.

This is something I cannot find as the proc is supposed to make a entirely new custom bullet 

#### What you expected to happen
Loading a gun with medium rubber bullets make a non lethal weapon.

Loading a Hectate 50 cal with large ammo to fire projectile/bullet/rifle/a145

#### What actually happened
The medium rifle fires real 25 damage bullets being a harmful weapon, probably firing the ammo_casing/simple/mediums proj, /obj/item/projectile/bullet/rifle/a545

The Hectate fires projectile/bullet/rifle/a338 instead, the projectile of /ammo_casing/simple/large, doing way less damage then intended.

#### Steps to reproduce
- (Step 1) For the rubber bullet bug, spawn a weapon that fires medium ammo, I use the /obj/item/weapon/gun/projectile/garand but any weapon works 
- (Step 2) Unload the gun and insert /obj/item/ammo_magazine/clip/medium/rubber in it, it should be loaded with rubber bullets 
- (Step 3) Fire the weapon at someone and look at the damage and halloss values and realize you didnt peace keep at all!

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Kashargul** [comment]
*caugh* 

https://github.com/CHOMPStation2/CHOMPStation2/blob/e4f77e7311d754062faed46f3a5e0ffb13be5b1b/modular_chomp/code/modules/projectiles/ammo_refactor/ammo_types.dm#L79

https://github.com/CHOMPStation2/CHOMPStation2/blob/e4f77e7311d754062faed46f3a5e0ffb13be5b1b/modular_chomp/code/modules/projectiles/ammo_refactor/ammo_types.dm#L87
