### ISSUE TITLE
[General] Selective mode bellies Vore HP Bars in the chat incorrect

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#8736]
#### Brief description of the bug
When in a selective mode belly, the HP bars in the chat window display as "Selectiving" instead of the relevant belly type (Draining, digesting etc)

#### What you expected to happen
If my selective mose is set to digest, it should say "Digesting", same with absorb and drain etc.

#### What actually happened
Instead, it says "Selectiveing" next to the HP bars

#### Steps to reproduce
- Create a belly with selective mode on
- Eat prey with selective mode set to something like digest
- HP bars pop up with incorrect text

**Comment by Kashargul** [comment]
No UI issue. Game issue.
