### ISSUE TITLE
[GENERAL] Vore soulcatcher transfers do not work.

### ISSUE THREAD

**Issue by RandoGuy999** [CHOMPStation2/CHOMPStation2#8743]
#### Brief description of the bug
Transfer (put the soul in an MMI or something), Transfer control (Give body control to a captured soul), and transfer self (the verb) all do not work for various reasons.
I found these while testing on an unmodified copy of the local master branch.
#### Anything else you may wish to add:
- Caught souls DO NOT seem to actually have their prefs, causing several procs to fail.
- is_taken_over() returns true if and only if "own_mind" is true and "owner.mind" and is false, it seems to have been preventing some procs from working when they should. Though I'm not actually sure what those 2 variables are so maybe it is working correctly.
- find_transfer_objects() only finds sleevemates, and normal MMIs, subtypes of MMIs (AKA posibrains) aren't found by it. This might be how it is supposed to work, but I'm not sure.

@Kashargul You do know how to check stuff that requires 2 clients by yourself (without making an alt account), right?

**Comment by Kashargul** [comment]
-> Prefs are reloaded on capture, so if you don't save them, you won't have them. That's intended as anything else would be a mess to handle.
-> You are only supposed to transfer yourself after entering / self capture, not after giving away control, that might lack a null check though.
-> if finds the subtypes without any issues on a quick unit test. Posi is a subtype of mmi. But I see some complications in the proc overrides of MMIs which might cause issues.

**Comment by Kashargul** [comment]
I simply don't have the time to test every little thing. I'm doing this in my freetime and 90% of the time on mobile devices instead of a PC. The entire thing was for weeks on TM for those things to be tested. Seemingly interest of players wasn't really there to test either.
