### ISSUE TITLE
Solar grubs not spawning anywhere except southern part of station

### ISSUE THREAD

**Issue by Razgriz1032** [CHOMPStation2/CHOMPStation2#876]
#### Brief description of the issue
Solar grubs not spawning anywhere except southern part of station. They are also primarily spawning on Deck 2 and Deck 3
They are also still spawning in the docks despite the exclusionary code.
`var/in_area = get_area(temp_vent)
        if(istype(in_area, /area/crew_quarters/sleep) || istype(in_area, /area/hallway/secondary/entry) || istype(in_area, /area/surface/outpost/main/dorms))
            continue`

#### What you expected to happen
Spawns need to be way more diverse across the station.

#### What actually happened
Literally the rest of the station is fine. The announcement after 50+ spawns of the event shows no indications of infestation in any of the departments. A tour around the station shows all departments are untouched. Deck 1 is untouched.
![image](https://user-images.githubusercontent.com/15962836/99741910-87162f00-2a8f-11eb-9d24-6cf3a5f1ba22.png)
![image](https://user-images.githubusercontent.com/15962836/99741900-81b8e480-2a8f-11eb-949e-6a2ae4a6edbb.png)
![image](https://user-images.githubusercontent.com/15962836/99741993-be84db80-2a8f-11eb-9085-6153d84275e7.png)

Current open PR to address this is #856

**Comment by Darlantanis** [comment]
Fixed by #856
