### ISSUE TITLE
The Morph ability "take over prey" no longer functions. 

### ISSUE THREAD

**Issue by Arbon777** [CHOMPStation2/CHOMPStation2#8845]
#### Brief description of the bug
The ability 'Take over Prey' on the Morph does not do anything when activated.

#### What you expected to happen
Either taking over the prey's body after you've eaten them, or an equivalent to shift-clicking on them while they're inside the vorgan.

#### What actually happened
I'm not sure when it changed, but the Morph maintinence hunter has an ability called "take over prey" that previously allowed them to become a copy of someone the morph has eaten. When used now, both on the station proper and in the VR-spawn, it does nothing. If you are copying something then it sends the message "You must restore to your original form first!" while if you are in your original form then it does nothing at all. As a result if you want to swap bodies around to mimic specific people, you need to spit them out, then shift-click them, then swallow them back up.

#### Steps to reproduce
- Become morph.
- Place person inside of the morph. Have tested this on SSD targets, awake targets, and targets both with and without "allow impersonation" toggled on. 
- Attempt to use the ability.

**Comment by Kashargul** [comment]
```
	if(morphed)
		to_chat(src, "<span class='warning'>You must restore to your original form first!</span>")
		return
	var/list/possible_mobs = list()
	for(var/obj/belly/B in src.vore_organs)
		for(var/mob/living/H in B)
			if( (ishuman(H) || isrobot(H)) && H.ckey )
				possible_mobs += H
			else
				continue
```

in morphed form, the return was always there, usually you should be able to select mobs from within your bellies. The question is, are you able to after putting someone into a vorebelly, or do you not get any popup for a selection at all?

**Comment by Arbon777** [comment]
The popup selection did not show up for me at all. First attempted by putting an SSD body inside, then assumed that it must simply not work on SSD people. Then tested on an active player, no feedback of any kind, assumed it was because of permissions somewhere. Finally tested on an active player with full allowances. 

Simple mobs do not allow the ability to trigger either, though I've only tested this on mice and raccoons.

**Comment by Kashargul** [comment]
> The popup selection did not show up for me at all. First attempted by putting an SSD body inside, then assumed that it must simply not work on SSD people. Then tested on an active player, no feedback of any kind, assumed it was because of permissions somewhere. Finally tested on an active player with full allowances.
> 
> Simple mobs do not allow the ability to trigger either, though I've only tested this on mice and raccoons.

Simple mobs are included, it needs to be a current active player character. To be more accurate, a carbon/human, on what kind of player was this test? Aka species?

**Comment by Arbon777** [comment]
All the carbon mobs tested were (presumably) custom species. My own that was a custom species I ghosted out of, a kobold being played as I tested on them, and a shergon. If they were a different species that simply had the species section renamed then I wouldn't be able to tell.

**Comment by Kashargul** [comment]
> All the carbon mobs tested were (presumably) custom species. My own that was a custom species I ghosted out of, a kobold being played as I tested on them, and a shergon. If they were a different species that simply had the species section renamed then I wouldn't be able to tell.

I see no issue directly, so this would need reproduction with 2 players.
