### ISSUE TITLE
Inconsistence in vore soulcatcher "transfer self" proc

### ISSUE THREAD

**Issue by RandoGuy999** [CHOMPStation2/CHOMPStation2#8848]
Well technically, there's nothing actually wrong with that proc, the problem is between the `find_transfer_objects` and `transfer_mob` procs.
find_transfer_objects returns:
- nearby MMIs
- nearby sleevemates
- other nearby soulcatchers
`transfer_mob `takes what the previous proc returns, the problem is that transfer_mob only has code for handling:
- transfering into MMIs
- transferring into sleevemates
When trying to transfer into one of the soulcatchers, transfer_mob just silently fails.
@Kashargul This seems to be the last issue with the soulcatcher.

**Comment by Kashargul** [comment]
transfer_mob_soulcatcher(selected_soul, gem)

is what should be called.

**Comment by Kashargul** [comment]
Try this, quickly written on phone though.

https://github.com/CHOMPStation2/CHOMPStation2/pull/8849

**Comment by RandoGuy999** [comment]
> have you checked that both parties had the pref enabled? SOULCATCHER_ALLOW_TRANSFER

Yeah, wasn't working, #8849 Fixes that, seems to work fine.
