### ISSUE TITLE
[GENERAL] Station alert console sprite not updating

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#8901]
#### Brief description of the bug
Station alert console sprite updates when an alarm is registered but it doesn't switch back after the alarm is cleared

#### What you expected to happen
Flashing red light goes off when all alarms clear

#### What actually happened
Light keeps flashing
![image](https://github.com/user-attachments/assets/d2e746f2-bc20-42bc-85a8-f5fb076a942b)

#### Steps to reproduce
- Trigger an alarm (usually outpost eventually has a power alarm)
- Console starts to flash
- Fix the issue causing the alarm (i.e. start the R-UST to clear the outpost alarm)
- Check the console. It's still flashing as if there's an alarm but no alarms are on

**Comment by Kashargul** [comment]
https://github.com/CHOMPStation2/CHOMPStation2/blob/4860596113fe9d016ec9d91a06098f69dbdaa1b9/code/game/machinery/computer/station_alert.dm#L47-L56

either the list isn't empty or the proc not called on change

**Comment by Kashargul** [comment]
They shouldn't work at all...

```
call(ProcRef)(Arguments)
call(Object,ProcName)(Arguments)
```
