### ISSUE TITLE
[GENERAL] Unable to see own Soulcatcher ARs

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#8999]
#### Brief description of the bug
You can't see anyone in your vore panel soulcatcher that's AR projecting unless you have AR glasses or the NIF equivalent

#### What you expected to happen
To be able to see at least the AR projections from my own soulcatcher even without AR glasses

#### What actually happened
AR projection is invisible

#### Steps to reproduce
- Soulcatch someone
- Have no AR equipment (NIF or AR glasses)
- Caught soul AR projects
- Person with the soulcatcher can't see the projection or anything that it does

**Comment by Kashargul** [comment]
Intended, get AR glasses
