### ISSUE TITLE
Unable to build CHOMPStation.

### ISSUE THREAD

**Issue by StarskyDarkstripe** [CHOMPStation2/CHOMPStation2#9036]
#### Brief description of the bug

When I try to build the files as the instructions say, following the git version not the zip, I get an error.

#### What you expected to happen

When I build the files it would work and I could play the newest version privately.

#### What actually happened

Upon going to build from either build.cmd or bin/build.cmd it starts fine and does what it needs to before, building yarn and tgui and such. Then after it finishes tgui it says;
code\datums\mutable_appearance.dm:8:warning (no_parent): ..: ..() has no parent proc to call
code\datums\mutable_appearance.dm:7:error: New: undefined proc
vorestation.dmb - 1 error, 1 warning (9/24/24 3:30 am)
Total time: 1:28
=> Target 'dm' failed in 87.726s, exit code: 4294967295
=> Target 'build' failed
=> Please inspect the error and close the window.

#### Steps to reproduce
Right click anywhere and type git clone https://github.com/CHOMPStation2/CHOMPStation2.git
Paste previous config and data as it said
Double click on either build.cmd in the main folder or bin/build.cmd
Wait and it will give it.

**Comment by Kashargul** [comment]
> Before you ask, yes I did try without my previous config and data, same result.

You are using 1643, that version is not used by any station currently due to some issues. USE 1642
