### ISSUE TITLE
Genaprawns, the quirks they have, and the bugs that could be fixed.

### ISSUE THREAD

**Issue by MisterGrimm** [CHOMPStation2/CHOMPStation2#91]
#### Brief description of the issue
This is a compendium of all of the current mechanic side problems I could find for Genaprawns. This is more of a post to track some stuff, and not all of it is a flat out bug. Some of it is just things that don't make sense for a Genaprawn to have.

**Names in issue changed from Xenomorph to Genaprawn, to prevent confusion.**

#### Known problems/bugs
- Genaprawns do not have a UI button to stop themselves from pulling something.
- ~~Genaprawns cannot see in the dark, WTF? Can easily be fixed by giving them the major dark vision trait, or giving them night vision.~~ **Fixed with PR** #579 
- ~~Genaprawns Queens cannot lay eggs, gives the message "You begin to lay an egg, but hesitate. You suspect it isn't allowed." before deleting the ability to lay eggs. Might not require it due to the Transform oddity, but it would restrict all Genaprawns to one type.~~ **Fixed with PR** #524 , #1359
- ~~Genaprawns sometimes lay pure white weeds, instead of purple weeds.~~ **Fixed via upstream.**
- Genaprawns cannot fight Beepsky without using acid spit, or a melee weapon. Assuming it is the same for other bots.
- ~~Facehuggers are commented out of the code, making it impossible to reproduce without eating and transforming people.~~ **Facehuggers removed, technically fixed.**
- ~~Due to removal of facehuggers, and restriction of egg laying, queen is functionally useless compared to the other castes.~~ **Fixed, see** #524 
- Tackle ability pops up a menu, even if there is only one non-Genaprawn nearby. Why isn't this a disarm attack?

#### Known oddities (Not necessarily bad things, just odd little quirks.) 
- Genaprawns can be hurt by polytrinic acid and sulfuric acid via ingestion, splashing, and injection. So much for having acid for blood.
- Genaprawns can use the 'Transform (Change Species and Taur half)' belly ability to turn people into Genaprawns of the same type, complete with the correct abilities, and their language being reset to Xenolingua and hivemind.
- ~~Genaprawns can force open bolted doors, unbolting them in the process. Isn't that what corrosive acid is for?~~ **Fixed with PR** #526 , #795
- ~~Genaprawns can still put on external clothing and helmets, but cannot take them off. They require external help, or admin help to remove them.~~ **Fixed with PR** #564 
- Genaprawns cannot take toxin damage, but will sometimes throw up because of it.
- ~~Genaprawns eat radiation like candy, and get fat from it. I wasn't expecting that.~~ **Fixed with** #524 
- Genaprawns cannot properly knock down people like a simple mob Xenomorph without the 'tackle' ability. Disarm just acts like a human disarm.
- ~~Only drone and queen can lay weeds, which wouldn't be a problem if queens could lay eggs, and facehuggers existed. One is forced to be a drone if they wish to survive long term in a hostile environment, due to healing oneself with weeds.~~ **Redundant, technically fixed now due to** #524 
- Genaprawns can heal themselves with any medicine or healing objects, just like a normal carbon. Doctor Xeno is in the house.
- Genaprawns Larva can drag people. This can cause problems when they run as fast as a teshari on drugs.
- ~~Genaprawns are often called "alien" when evolving into different castes.~~ **Fixed with PR** #1682 
- ~~Genaprawns do not scream.~~ **Fixed with PR** #775 , **PR** #585 **is a infrastructure requirement for PR 775.**

**Comment by Rykka-Stormheart** [comment]
The unable to lay eggs bit is due to the fact that code-wise it checks for if an area has a flag for allowing egg-laying. Of course, most of our areas lack that flag, so it's impossible.

**Comment by Darlantanis** [comment]
Did your xenomorphs PR fix this?

**Comment by MisterGrimm** [comment]
Updated as of 12/9/2020. Most problems were fixed, some still exist.

**Comment by MisterGrimm** [comment]
Issue being closed, fixes are being done in virgo upstream now to properly divy out fixes.
