### ISSUE TITLE
[GENERAL] Potassium Chloride isn't a poison

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#9177]
#### Brief description of the bug
Potassium chloride is supposed to be a heart-stopping poison but it just doesn't work that way

#### What you expected to happen
Injected chem to deal some form of oxyloss and toxin etc

#### What actually happened
Injected chem does nothing at all unless you overdose on it

#### Steps to reproduce
- Make potassium chloride
- Inject 15u
- Nothing happens
- Inject another 20u
- OD symptoms trigger, but these should be the base effects really

**Comment by Kashargul** [comment]
As discussed the salt itself is mostly harmless in low doses. High doses are dangerous, though. You are free to add a suggested change for the tooltip.

**Comment by Missile597** [comment]
Oops I thought this got closed
