### ISSUE TITLE
[GENERAL] Depthours being reset for most players

### ISSUE THREAD

**Issue by ro3ger** [CHOMPStation2/CHOMPStation2#9191]
#### Anything else you may wish to add:
Vote made 10/09/24 during high population time, vote was over if their depthours were reset
![bug](https://github.com/user-attachments/assets/3be05c51-76b8-433f-9f50-5c979eb80060)

**Comment by ro3ger** [comment]
Allright after a round, I have found that the currently system for Depthours is not tracking. So good luck to the programers

**Comment by Kashargul** [comment]
Known issue. Database has been fixed. Ahelp to get your hours back.

Notes:
- Admins can only edit the hours of your currently selected job
- You'll need to play 30 minutes actively without disconnecting for the first write to be securely performed
