### ISSUE TITLE
✨Prussian Blue's effect does not match its desciption

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#9255]
#### Brief description of the feature
Prussian Blue claims to pause the effects of radiation poisoning. It would be neat if it actually did that.
![image](https://github.com/user-attachments/assets/69f786ef-340a-4554-85de-97bea90071b5)
Currently all it does is have a small chance of removing some toxin damage
![image](https://github.com/user-attachments/assets/877d9caf-25b1-44b0-81c0-c475ca988ccd)
I tested this by injecting radium into two sleeves. One with and one without prussian in the blood. They all got the same amount of rad poisoning and roughly the same damage from the radiation poisoning, with the only difference being like, two or three points less toxins in the prussian patient. The chemical doesn't do what it says it does and isn't really worth using.

#### What you want to happen
Either change the description or have it so that the negative effects of radiation poisoning (burn, toxin, genetic damage etc) stop happening while you have prussian in your system (but radiation poisoning remains)

**Comment by Kashargul** [comment]
Toxin is stacking up from the radium here.

Wrong usage of the drug.

https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L256

https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L314-L315

**Comment by Missile597** [comment]
> Toxin is stacking up from the radium here.
> 
> Wrong usage of the drug.
> 
> https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L256
> 
> https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L314-L315
> 
> https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L459

This isn't relevant to the suggestion made

**Comment by Kashargul** [comment]
> > Toxin is stacking up from the radium here.
> > Wrong usage of the drug.
> > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L256
> > 
> > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L314-L315
> > 
> > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L459
> 
> This isn't relevant to the suggestion made Edit: Context: While you have prussian in your system you still suffer effects of radiation poisoning, so instead of being a suggestion, this might instead be a bug report as it's not functioning how it's supposed to

it's only supposed to halt the actual radiation damage caused by radiation itself. Not any toxin effects. 

So your test case here doesn't reflect the usecase. Try it during a radiation storm event, or with a lingering radiation dose on someone. Not with injected toxins.

**Comment by Missile597** [comment]
> > > Toxin is stacking up from the radium here.
> > > Wrong usage of the drug.
> > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L256
> > > 
> > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L314-L315
> > > 
> > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L459
> > 
> > 
> > This isn't relevant to the suggestion made Edit: Context: While you have prussian in your system you still suffer effects of radiation poisoning, so instead of being a suggestion, this might instead be a bug report as it's not functioning how it's supposed to
> 
> it's only supposed to halt the actual radiation damage caused by radiation itself. Not any toxin effects.
> 
> So your test case here doesn't reflect the usecase. Try it during a radiation storm event, or with a lingering radiation dose on someone. Not with injected toxins.

I can see if I can do another test but if this is the case, the in-game description is even more wrong somehow

**Comment by Kashargul** [comment]
> > > > Toxin is stacking up from the radium here.
> > > > Wrong usage of the drug.
> > > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L256
> > > > 
> > > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L314-L315
> > > > 
> > > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L459
> > > 
> > > 
> > > This isn't relevant to the suggestion made Edit: Context: While you have prussian in your system you still suffer effects of radiation poisoning, so instead of being a suggestion, this might instead be a bug report as it's not functioning how it's supposed to
> > 
> > 
> > it's only supposed to halt the actual radiation damage caused by radiation itself. Not any toxin effects.
> > So your test case here doesn't reflect the usecase. Try it during a radiation storm event, or with a lingering radiation dose on someone. Not with injected toxins.
> 
> I can see if I can do another test but if this is the case, the in-game description is even more wrong somehow

Not exactly it's doing what is says. Depending on the stacked radiation effect visible to medical in Gy on a living. It will prevent further effects of this dosis like random mutations, etc.

**Comment by Missile597** [comment]
> > > > > Toxin is stacking up from the radium here.
> > > > > Wrong usage of the drug.
> > > > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L256
> > > > > 
> > > > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L314-L315
> > > > > 
> > > > > https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/modules/mob/living/carbon/human/life.dm#L459
> > > > 
> > > > 
> > > > This isn't relevant to the suggestion made Edit: Context: While you have prussian in your system you still suffer effects of radiation poisoning, so instead of being a suggestion, this might instead be a bug report as it's not functioning how it's supposed to
> > > 
> > > 
> > > it's only supposed to halt the actual radiation damage caused by radiation itself. Not any toxin effects.
> > > So your test case here doesn't reflect the usecase. Try it during a radiation storm event, or with a lingering radiation dose on someone. Not with injected toxins.
> > 
> > 
> > I can see if I can do another test but if this is the case, the in-game description is even more wrong somehow
> 
> Not exactly it's doing what is says. Depending on the stacked radiation effect visible to medical in Gy on a living. It will prevent further effects of this dosis like random mutations, etc.

The description says it's supposed to "pause the effects of radiation poisoning", which to me sounds like it should mean the passive effects of having radiation damage (toxin buildup, random burns and genetic damage etc)

The effect you described is more akin to being "immune to radiation in the area" which
- Doesn't match the chemical description
- Is also not doing that currently either (left has prussian in a rad storm, right does not)
![image](https://github.com/user-attachments/assets/79da9527-a343-4517-9582-68a2a53e237b)
As you can see in the image, the only difference in a rad storm is the small amount of toxin healing that prussian does by default. It is not creating any immunity to gaining rads nor is it preventing any effects of radiation poisoning

**Comment by Kashargul** [comment]
You are merely in the initial stage of radiation. Try it with ~ 1600 and you'll see the difference clearly.

**Comment by Missile597** [comment]
At this point I feel like I've demonstrated that what it's doing doesn't match the description. I might take a look at that test branch but I won't be able to test it until next week at the earliest
