### ISSUE TITLE
[GENERAL] Washing hands cleans clothes

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#9256]
#### Brief description of the bug
Not sure if this is intended behaviour or not but it seems kinda goofy so I'm reporting it. When you wash your hands in a sink, it cleans all your clothes, not just your gloves.

#### What you expected to happen
Hands and gloves get cleaned.

#### What actually happened
Other clothing such as boots get cleaned

#### Steps to reproduce
- Step in oil and get dirty boots
- Wash hands in a sink
- Boots get cleaned as well

**Comment by Kashargul** [comment]
https://github.com/CHOMPStation2/CHOMPStation2/blob/8e76e89e775c874247f9b40972ca9e33183fa252/code/game/objects/structures/watercloset.dm#L562

the closer straight on calls clean blood what removes all blood overlays on any item

**Comment by Kashargul** [comment]
closed with #9265
