### ISSUE TITLE
[CODE BASE]  Hostile Pred mobs arnt hostile/ghost roleable

### ISSUE THREAD

**Issue by ShadeKage** [CHOMPStation2/CHOMPStation2#9530]
#### Brief description of the bug
Mobs that are designated as "preds" have several ai bugs, possibly fully disabled code, idk, I dont have assess to that level of depth into the code, none of the labeled bugs apply to the prey ghsot roles (mostly just mice, rats, and raccoons)

#### What you expected to happen
If a mob, such as large snake, sees a player they attack/attempt to eat the player, as theyre are supposed to act as a vorny alternative to space carp, space snakes, etc. And if someone is a ghost, the giant snake should show up as a valid role to take control of int eh menu and have a pink arrow in ghost mode next to it to control it, to allow for rp outside of pure crew to crew

#### What actually happens
Its varyable in it but, most of the time the mob does nothing, they act like a pat ai, idling with occasional random movements, they never attempt to attack the player unless either provoked, which makes them act like base SS13 hostiles and just beat the player to death, or under certain cases where some of their old code will trigger (such as seeing a critical person), causing them to eat them. Also, every single pred mob, does not show up in the ghost role menu, nor has the pink arrow to actually take control of them, as they are supposed to. And I know for a fact theyre supposed to, as their entire mechanic shows up in the VORE station wiki

#### Steps to reproduce
- (Option 1) Play as shaft miner or explorer and find any pred mob, they wont attack on site like theyre supposed to
- (Option 2) Open the ghost pod (ghost role) menu and look as the only things that show up are prey roles, you can use the ghost teleport to confirm that the mobs ARE spawning, but are NOT controlable in anyways

#### Anything else you may wish to add:
A link to VORE stations wiki, which is up to date on what the code does, and shows "maint preds" and exactly what i explained
https://wiki.vore-station.net/Maintenance_Preds

**Comment by Kashargul** [comment]
You are mixing things up here. Ghost pods / maint preds are specific events that allow a player to spawn as a mob. Random world mobs can not be controlled except for a few subtypes like mice.

**Comment by ShadeKage** [comment]
> You are mixing things up here. Ghost pods / maint preds are specific events that allow a player to spawn as a mob. Random world mobs can not be controlled except for a few subtypes like mice.

Yes, however they are still not hostile to players as intended

**Comment by Kashargul** [comment]
> Also the wiki does state some of these map spawned mobs are SUPPOSED to be controlable, not all of them, but some, if not most, not JUST mice

That's in our decision which we allow. There won't be any changes on the list.

Hostility depends on the faction and setting, a lot of mobs are set to passive by default.

**Comment by ShadeKage** [comment]
Did some more in-game testing
The vore preds ATTACK but dont vore
Friend literally got beat to death, crit, died, and it never ate him at all
Like i said, its varyable between mobs

**Comment by ShadeKage** [comment]
Further testing results:
The spiders, which are intended to vore, as i mentioned before, only attack and aim for crit
and even if a bait toy is sued on them to FORCE the vore interaction, it does not work

**Comment by Kashargul** [comment]
There are no vore capable spiders. I heavily suggest to chat with someone about which mobs even have the capability and which don't. Or to take a proper look into the code sections. 

code\modules\mob\living\simple_mob\subtypes\vore

Anyway, closing this here.
