### ISSUE TITLE
[GENERAL] Pilot and Explo Bowman headsets not correctly set up

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#9576]
#### Brief description of the bug
The bowman variants of exploration and pilot headsets, both in loadout and in map spawn, do not have any channels

#### What you expected to happen
Both bowman headsets should be set up for exploration channel (I believe common is there by default?). I think Pilots might have supply channel as well? Not sure on that one

#### What actually happened
No explo channel.

#### Steps to reproduce
- Log in as explo
- Grab a bowman headset from the locker
- Check channels on headset - explo is missing

**Comment by ShadeKage** [comment]
Also can note
If you spawn as expedition lead with the bowman, you are missing explo radio and command radio
