### ISSUE TITLE
[GENERAL] Plating on the z below blocks downwards movement

### ISSUE THREAD

**Issue by Missile597** [CHOMPStation2/CHOMPStation2#9616]
#### Brief description of the bug
When you are above empty space and try to move down, if the z level below you has plating your movement is blocked.

#### What you expected to happen
Plating should only block vertical z movement if it's on the level above, not the level below

#### What actually happened
Movement is blocked in both cases

#### Steps to reproduce
- Go to the toxins test area walkway in space on southern cross deck two with an engineering hardsuit
- Turn on the jetpack and move up a Z, no issues
- Try to move down a z: "movement is blocked by the plating"

**Comment by Kashargul** [comment]
Needs the full error message it gives ingame.

**Comment by Missile597** [comment]
> Needs the full error message it gives in game.

I did mention it but here's the exact text for you
![image](https://github.com/user-attachments/assets/f85fa806-bcc7-4af0-9a73-ad4d103d84f9)

**Comment by Kashargul** [comment]
> > Needs the full error message it gives in game.
> 
> I did mention it but here's the exact text for you ![image](https://private-user-images.githubusercontent.com/150307788/394769386-f85fa806-bcc7-4af0-9a73-ad4d103d84f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzUxMDMsIm5iZiI6MTczMzkzNDgwMywicGF0aCI6Ii8xNTAzMDc3ODgvMzk0NzY5Mzg2LWY4NWZhODA2LWJjYzctNGFmMC05YTczLWFkNGQxMDNkODRmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNjMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWFhOWEzODQ3N2FhMGYwYzU2ZWE2OGFkOTFkOWYwYmEzNjQ2YmQwYmJmZDdlOWRmNTEzOGJhNzdlM2E1YmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CPJ4xpfW22Ks7fiqLICsqff8CJd0H4f6vN3ATMv9Mfc)

if the wording is not 100% identical, one will never find the lines in the code. Hence why reports should contain a 1:1 copy and not some "it might be like" this message.

**Comment by Kashargul** [comment]
Should be resolved with #9634
