### ISSUE TITLE
[GENERAL] dullahan Engineering sprite scales differently from the other dullahan sprites.

### ISSUE THREAD

**Issue by RandoGuy999** [CHOMPStation2/CHOMPStation2#9630]
For some reason dullahan engineering is just "dogborg" instead of "dogborg/tall" like the rest of them, so the vis_height is set differently.
Engineering path:
`/datum/robot_sprite/dogborg/engineering/dullahan`
Others:
`/datum/robot_sprite/dogborg/tall/crisis/dullahan`
`/datum/robot_sprite/dogborg/tall/mining/dullahan`
`/datum/robot_sprite/dogborg/tall/clown/dullahan`

**Comment by Kashargul** [comment]
fixed with #9631
