### ISSUE TITLE
Adding text to the vore mobs that didn't receive text

### ISSUE THREAD

**Issue by Aluka-Wolf** [CHOMPStation2/CHOMPStation2#964]
#### Brief overview of the feature
seeing how like the giant rodents have text, solar grubs have text and such but not like other vore mobs like the dire wolfs, red dragon, the voracious lizard, lizardman etc etc.

#### What you want to happen
Would love to see some text added to the vore mobs that never received text to get some text! if its possible! could be good and nice and such instead of seeing the usual like been swallowed up by said vore mob and its warm considering your in said vore mob etc etc.
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Darlantanis** [comment]
Pretty easy to add if somebody feels like contributing writing.

**Comment by SolanAsasora** [comment]
Is there somewhere that a person feeling so inclined (read: me) could contribute text for these?
