### ISSUE TITLE
[GENERAL] Distillery Reactions don't work

### ISSUE THREAD

**Issue by NickBelmont** [CHOMPStation2/CHOMPStation2#9693]
#### Brief description of the bug
The distillery seems entirely broken, nothing reacts anymore.

#### What you expected to happen
When the proper temperature is reached and the right reagents are in the distillery, a message and noise are displayed, and the contents of the distillery begin to react.

#### What actually happened
Both on turning on the distillery and trying to manually mix things, the distillery does nothing.

#### Steps to reproduce
- Add reagents to distillery and set temperature
- Turn on distillery
- Attempt manual mixing

**Comment by NickBelmont** [comment]
In addition, phoron reacting with blood (I assume that's from the new virology system since blood is a sort of virus culture?) makes the distillery biomass reaction a bit annoying, but that can at least be worked around since stuff doesn't do non-distillery reactions once in the distillery.

**Comment by Missile597** [comment]
What was the pressure of the has in the distillery. I need to check at some point that nothing broke but the distillery has worked for me in the past. Too low pressure can break it though

**Comment by NickBelmont** [comment]
Not sure, didn't realize that could cause issues. I can check next opportunity I get though.

**Comment by NickBelmont** [comment]
It seems like there's pressure in the system, and the distillery is hooked up to it, given the temperature adjusts with the rest of the gas.

**Comment by NickBelmont** [comment]
Nevermind, it works now for some reason.

**Comment by NickBelmont** [comment]
The wiki temperatures are wrong, but that's always been the case. Not sure why it wasn't working a few shifts ago.

**Comment by NickBelmont** [comment]
I'll close this unless something else comes up, then.

**Comment by Missile597** [comment]
> The wiki temperatures are wrong, but that's always been the case. Not sure why it wasn't working a few shifts ago.

I'll message you the actual temperatures. There's been some adjustments and also the code temps are formatted weird. Instead if being "use this temp" it is formatted as like "X degrees away from this arbitrary temperature" it's weird
