### ISSUE TITLE
[GENERAL] Borg sleepers cannot digest mobs

### ISSUE THREAD

**Issue by Fennec82** [CHOMPStation2/CHOMPStation2#9695]
#### Brief description of the bug
Cyborgs with sleeper modules (borg bellies) cannot digest mobs using the self-clean function

#### What you expected to happen
Play as a cyborg and eat + digest someone

#### What actually happened
Carbon mobs can be consumed and show up in sleeper. Chems can be injected but self-clean does not appear to function despite being enabled in the code (Dogborg_sleeper_vr). May be an issue with the cyborg modularization as their code does not appear to have been reworked

#### Steps to reproduce
- Spawn as Cyborg
- Pick module and sprite with sleeper (Pick your flavor of vore borg, all seem to be affected)
- Eat a player mob using sleeper/belly brig/matter decompiler/insert borg belly here
- Activate Self-clean to digest mob
- Mob takes no damage and dead mobs do not digest
- Health analyzers and injectors work fine

#### Code Revision
Unknown, tested on downstream project (A direct Chomp fork) with no borg code changes except reenabling ERT borg sword tail.
 
#### Anything else you may wish to add:
- Proof of issue 
![Screenshot 2024-12-27 111147](https://github.com/user-attachments/assets/0900a0a7-94c0-4453-862e-25e123a64378)

**Comment by Kashargul** [comment]
When preferences don't match you can't, no.

**Comment by Fennec82** [comment]
To explain the screenshot: Mobs do not take any kind of damage when using self clean. I manually gave an adminspawned mob (carbon/human) 200 oxy damage to kill them and then consumed them with my Crisis Raptorborg's mounted sleeper and activated self clean. The mob did not digest like they should.

**Comment by Fennec82** [comment]
Oh, weird

The prefs matched when I checked

**Comment by Fennec82** [comment]
Digest was enabled in testing mob prefs

**Comment by Fennec82** [comment]
![Screenshot 2024-12-27 113235](https://github.com/user-attachments/assets/18df6d80-6f2d-4e92-a811-8cf5ae9eccba)

These are my test mob's prefs, am I missing something?

**Comment by Fennec82** [comment]
> When preferences don't match you can't, no.

Should I test this with a live player?

**Comment by Kashargul** [comment]
What subtype is the mob? Don't tell me a dummy.

**Comment by Fennec82** [comment]
> What subtype is the mob? Don't tell me a dummy.

Mob/living/carbon/human

**Comment by Kashargul** [comment]
> > What subtype is the mob? Don't tell me a dummy.
> 
> Mob/living/carbon/human

Just ran a test, it passed fine. You might have spawned an uninitialized mob by doing admin spawning.

**Comment by Fennec82** [comment]
Got it, thank you
