### ISSUE TITLE
Insane amounts of Admin Log entries concerning Volatile Alluvium Blob Spores

### ISSUE THREAD

**Issue by MrMacint0sh** [CHOMPStation2/CHOMPStation2#97]
#### Brief description of the bug
Blob spores from the Alluvium Blob create a chemical explosion. This makes an admin log entry called 
ADMIN LOG: A chemical smoke reaction has taken place in (Location | X,Y). No associated key.
#### What you expected to happen
Not a bajillion of them when a bunch of spores fired at a single target
#### What actually happened
Insane amounts of admin log entries
#### Steps to reproduce
- Spawn Alluvium Blob
- Let it spawn Spores
- Go near Spores
- Have them fire at you
- Enjoy the admin long getting flooded with messages.

#### Code Revision
- I have no clue how to change this. 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by ExabyteDiscord** [comment]
Considering I forgot to clarify, while this is a rather large issue with the blob type for the admins, we likely won't have any need to use this blob type in particular while the bug remains, so low priority. Granted a fix will be nice regardless.

**Comment by VictorZisthus** [comment]
Adding this to my massive TODO list.
